from _common import build

QUESTIONS = [
    # ── Separation of mixtures ──
    {"t": "The separation technique used to obtain a solid from a solution is:", "o": ["Filtration", "Evaporation", "Distillation", "Sublimation"], "a": 1, "e": "Evaporation removes the solvent, leaving the solid.", "d": 1},
    {"t": "Filtration is used to separate:", "o": ["Two liquids", "An insoluble solid from a liquid", "A soluble solid from a liquid", "Two gases"], "a": 1, "e": "Filtration separates insoluble solids from liquids.", "d": 1},
    {"t": "The method used to separate a mixture of liquids with different boiling points is:", "o": ["Filtration", "Fractional distillation", "Evaporation", "Decantation"], "a": 1, "e": "Fractional distillation separates liquids by boiling point.", "d": 1},
    {"t": "A mixture of salt and water can be separated by:", "o": ["Filtration", "Evaporation", "Magnetisation", "Sieving"], "a": 1, "e": "Evaporate the water to recover the salt.", "d": 1},
    {"t": "Which technique separates a mixture of iron filings and sand?", "o": ["Filtration", "Magnetic separation", "Distillation", "Chromatography"], "a": 1, "e": "A magnet attracts the iron filings.", "d": 1},
    {"t": "Chromatography is used to separate:", "o": ["Coloured components of a mixture", "Solids from liquids", "Immiscible liquids", "Metals"], "a": 0, "e": "Chromatography separates coloured solutes.", "d": 1},
    {"t": "The process by which a solid changes directly to gas is:", "o": ["Melting", "Sublimation", "Evaporation", "Condensation"], "a": 1, "e": "Sublimation is solid → gas directly (e.g. iodine).", "d": 1},
    {"t": "A mixture of two immiscible liquids is best separated using a:", "o": ["Filter", "Separating funnel", "Condenser", "Magnet"], "a": 1, "e": "Immiscible liquids are separated with a separating funnel.", "d": 1},
    {"t": "A pure substance has:", "o": ["A variable boiling point", "A sharp, fixed melting point", "Many components", "No definite composition"], "a": 1, "e": "Pure substances melt/boil at a fixed temperature.", "d": 1},
    {"t": "Which of these is a physical change?", "o": ["Burning wood", "Melting ice", "Rusting iron", "Fermenting sugar"], "a": 1, "e": "Melting is a change of state, not a new substance.", "d": 1},

    # ── Chemical combination ──
    {"t": "The law of conservation of mass states that mass is:", "o": ["Created in reactions", "Conserved in reactions", "Destroyed in reactions", "Variable"], "a": 1, "e": "Mass is neither created nor destroyed.", "d": 1},
    {"t": "The law of definite proportions states that a compound always contains:", "o": ["Variable proportions", "The same elements in the same ratio", "Only one element", "No fixed ratio"], "a": 1, "e": "A compound has a fixed composition by mass.", "d": 1},
    {"t": "One mole of any substance contains ___ particles (Avogadro's number).", "o": ["6.02 × 10²³", "3.01 × 10²³", "6.02 × 10²²", "1 × 10²³"], "a": 0, "e": "Avogadro's number is 6.02 × 10²³.", "d": 1},
    {"t": "The molar mass of water (H₂O) is: (H=1, O=16)", "o": ["18 g/mol", "17 g/mol", "16 g/mol", "20 g/mol"], "a": 0, "e": "2×1 + 16 = 18 g/mol.", "d": 1},
    {"t": "The number of moles in 44 g of CO₂ (C=12, O=16) is:", "o": ["1 mol", "2 mol", "0.5 mol", "44 mol"], "a": 0, "e": "Molar mass CO₂ = 44 g/mol; 44/44 = 1 mol.", "d": 2},
    {"t": "The empirical formula shows the:", "o": ["Simplest whole-number ratio of atoms", "Actual number of atoms", "Molecular mass", "Atomic mass"], "a": 0, "e": "Empirical formula = simplest ratio.", "d": 1},
    {"t": "The molecular formula shows the:", "o": ["Simplest ratio", "Actual number of atoms in a molecule", "Valency", "Charge"], "a": 1, "e": "Molecular formula gives actual atom counts.", "d": 1},
    {"t": "The valency of oxygen is:", "o": ["1", "2", "3", "4"], "a": 1, "e": "Oxygen has valency 2.", "d": 1},
    {"t": "The valency of hydrogen is:", "o": ["1", "2", "3", "4"], "a": 0, "e": "Hydrogen has valency 1.", "d": 1},
    {"t": "The formula of sodium chloride is:", "o": ["NaCl", "NaCl₂", "Na₂Cl", "Na₂Cl₂"], "a": 0, "e": "Na⁺ and Cl⁻ combine 1:1 → NaCl.", "d": 1},
    {"t": "The chemical formula of sulphuric acid is:", "o": ["H₂SO₄", "H₂SO₃", "HSO₄", "H₂S"], "a": 0, "e": "Sulphuric acid is H₂SO₄.", "d": 1},
    {"t": "A chemical equation must be balanced to obey:", "o": ["The law of conservation of mass", "Newton's law", "Charles's law", "Boyle's law"], "a": 0, "e": "Balancing conserves atoms (mass).", "d": 1},

    # ── Kinetic theory & gas laws ──
    {"t": "According to the kinetic theory, gas particles are in:", "o": ["Fixed positions", "Constant random motion", "Slow vibration only", "No motion"], "a": 1, "e": "Gas particles move constantly and randomly.", "d": 1},
    {"t": "The three states of matter are:", "o": ["Solid, liquid, gas", "Solid, vapour, plasma", "Liquid, gas, energy", "Solid, liquid, steam"], "a": 0, "e": "States of matter: solid, liquid, gas.", "d": 1},
    {"t": "Diffusion is fastest in:", "o": ["Solids", "Liquids", "Gases", "All equally"], "a": 2, "e": "Gases diffuse fastest due to large inter-particle spaces.", "d": 1},
    {"t": "Boyle's law states that at constant temperature, PV is:", "o": ["Constant", "Variable", "Zero", "Infinite"], "a": 0, "e": "PV = constant at constant T.", "d": 1},
    {"t": "Charles's law states V ∝ T at constant:", "o": ["Pressure", "Volume", "Mass", "Temperature"], "a": 0, "e": "V ∝ T at constant pressure.", "d": 1},
    {"t": "The ideal gas equation is:", "o": ["PV = nRT", "PT = nRV", "PV = nT", "P = nRT"], "a": 0, "e": "PV = nRT.", "d": 1},

    # ── Atomic structure & bonding ──
    {"t": "The atom consists of a nucleus and:", "o": ["Electrons", "Only protons", "Only neutrons", "Ions"], "a": 0, "e": "Electrons orbit the nucleus.", "d": 1},
    {"t": "The subatomic particles in the nucleus are:", "o": ["Protons and electrons", "Protons and neutrons", "Neutrons and electrons", "Ions"], "a": 1, "e": "The nucleus holds protons and neutrons.", "d": 1},
    {"t": "The atomic number equals the number of:", "o": ["Neutrons", "Protons", "Electrons + neutrons", "Nucleons"], "a": 1, "e": "Atomic number = protons.", "d": 1},
    {"t": "The mass number equals protons plus:", "o": ["Electrons", "Neutrons", "Ions", "Charge"], "a": 1, "e": "Mass number = protons + neutrons.", "d": 1},
    {"t": "The maximum number of electrons in the first shell is:", "o": ["2", "8", "18", "32"], "a": 0, "e": "The first shell holds 2 electrons.", "d": 1},
    {"t": "The maximum number of electrons in the second shell is:", "o": ["2", "8", "18", "32"], "a": 1, "e": "The second shell holds 8 electrons.", "d": 1},
    {"t": "The electronic configuration of sodium (Z=11) is:", "o": ["2, 8, 1", "2, 8, 8", "2, 8, 2", "2, 1"], "a": 0, "e": "Na: 2, 8, 1.", "d": 1},
    {"t": "The electronic configuration of chlorine (Z=17) is:", "o": ["2, 8, 7", "2, 8, 8", "2, 8, 18", "2, 7"], "a": 0, "e": "Cl: 2, 8, 7.", "d": 1},
    {"t": "An ionic bond is formed by:", "o": ["Sharing of electrons", "Transfer of electrons", "Sharing of protons", "Transfer of neutrons"], "a": 1, "e": "Ionic bonds involve electron transfer.", "d": 1},
    {"t": "A covalent bond is formed by:", "o": ["Transfer of electrons", "Sharing of electrons", "Loss of protons", "Gain of neutrons"], "a": 1, "e": "Covalent bonds involve electron sharing.", "d": 1},
    {"t": "Which of the following is an ionic compound?", "o": ["CH₄", "NaCl", "CO₂", "H₂O"], "a": 1, "e": "NaCl is ionic (metal + non-metal).", "d": 1},
    {"t": "Which of the following is a covalent compound?", "o": ["NaCl", "MgO", "H₂O", "KCl"], "a": 2, "e": "H₂O is covalent (non-metal + non-metal).", "d": 1},
    {"t": "Isotopes have the same number of protons but different:", "o": ["Electrons", "Neutrons", "Charge", "Atomic number"], "a": 1, "e": "Isotopes differ in neutron number.", "d": 1},
    {"t": "The relative atomic mass of an element is measured relative to:", "o": ["Hydrogen-1", "Carbon-12", "Oxygen-16", "Nitrogen-14"], "a": 1, "e": "Atomic masses are relative to carbon-12.", "d": 1},
    {"t": "The number of neutrons in ²³Na (Z=11) is:", "o": ["11", "12", "23", "34"], "a": 1, "e": "Neutrons = 23 − 11 = 12.", "d": 2},

    # ── Air ──
    {"t": "The most abundant gas in air is:", "o": ["Oxygen", "Nitrogen", "Carbon dioxide", "Argon"], "a": 1, "e": "Nitrogen is about 78% of air.", "d": 1},
    {"t": "The approximate percentage of oxygen in air is:", "o": ["78%", "21%", "1%", "50%"], "a": 1, "e": "Oxygen ≈ 21%.", "d": 1},
    {"t": "The gas used by plants for photosynthesis is:", "o": ["Oxygen", "Carbon dioxide", "Nitrogen", "Argon"], "a": 1, "e": "Plants take in CO₂.", "d": 1},
    {"t": "The gas that supports combustion is:", "o": ["Nitrogen", "Oxygen", "Carbon dioxide", "Helium"], "a": 1, "e": "Oxygen supports burning.", "d": 1},
    {"t": "The active part of air is:", "o": ["Nitrogen", "Oxygen", "Argon", "Carbon dioxide"], "a": 1, "e": "Oxygen is the reactive component.", "d": 1},

    # ── Water ──
    {"t": "Pure water boils at (at standard pressure):", "o": ["100°C", "0°C", "212°C", "90°C"], "a": 0, "e": "Water boils at 100°C at 1 atm.", "d": 1},
    {"t": "Water is said to be hard when it contains dissolved:", "o": ["Sodium salts", "Calcium or magnesium salts", "Sugar", "Oxygen"], "a": 1, "e": "Hard water has Ca²⁺/Mg²⁺ salts.", "d": 1},
    {"t": "Temporary hardness of water is caused by:", "o": ["Calcium hydrogen carbonate", "Calcium sulphate", "Sodium chloride", "Magnesium chloride"], "a": 0, "e": "Temporary hardness is from calcium hydrogen carbonate.", "d": 2},
    {"t": "Temporary hardness can be removed by:", "o": ["Boiling", "Adding more salt", "Cooling", "Freezing"], "a": 0, "e": "Boiling precipitates calcium carbonate.", "d": 1},
    {"t": "Water is purified for drinking by:", "o": ["Adding salt", "Filtration and chlorination", "Adding sugar", "Heating only"], "a": 1, "e": "Filtration + chlorination disinfects water.", "d": 1},

    # ── Solubility ──
    {"t": "Solubility is the amount of solute that dissolves in:", "o": ["100 g of solvent", "1 g of solvent", "Any volume", "100 g of solute"], "a": 0, "e": "Solubility = g solute per 100 g solvent at a temperature.", "d": 1},
    {"t": "A saturated solution contains:", "o": ["No solute", "The maximum dissolved solute", "Any amount", "Only solvent"], "a": 1, "e": "A saturated solution holds maximum solute.", "d": 1},
    {"t": "For most solids, solubility ___ with increasing temperature.", "o": ["Decreases", "Increases", "Is unchanged", "Becomes zero"], "a": 1, "e": "Most solids dissolve more when heated.", "d": 1},
    {"t": "The solubility of gases in water generally ___ with increasing temperature.", "o": ["Increases", "Decreases", "Stays constant", "Doubles"], "a": 1, "e": "Gases are less soluble at higher temperature.", "d": 2},
    {"t": "A supersaturated solution is:", "o": ["Unstable", "Stable", "Dilute", "Unsaturated"], "a": 0, "e": "Supersaturated solutions hold more than normal and are unstable.", "d": 2},

    # ── Environmental pollution ──
    {"t": "The gas mainly responsible for acid rain is:", "o": ["Oxygen", "Sulphur dioxide", "Nitrogen", "Hydrogen"], "a": 1, "e": "SO₂ dissolves in rain to form acid rain.", "d": 1},
    {"t": "The main greenhouse gas produced by burning fossil fuels is:", "o": ["Oxygen", "Carbon dioxide", "Nitrogen", "Argon"], "a": 1, "e": "CO₂ is the main greenhouse gas.", "d": 1},
    {"t": "The depletion of the ozone layer is caused mainly by:", "o": ["CFCs", "Oxygen", "Nitrogen", "Water vapour"], "a": 0, "e": "Chlorofluorocarbons destroy ozone.", "d": 1},
    {"t": "Air pollution can be reduced by:", "o": ["Burning more fuel", "Using renewable energy", "Cutting trees", "More cars"], "a": 1, "e": "Renewable energy reduces emissions.", "d": 1},
    {"t": "Water pollution is caused by:", "o": ["Industrial waste", "Rainwater", "Oxygen", "Sunlight"], "a": 0, "e": "Industrial waste pollutes water.", "d": 1},

    # ── Acids, bases & salts ──
    {"t": "An acid is a substance that donates:", "o": ["Electrons", "Protons (H⁺)", "Neutrons", "OH⁻"], "a": 1, "e": "Acids donate protons (H⁺).", "d": 1},
    {"t": "A base is a substance that accepts:", "o": ["Electrons", "Protons (H⁺)", "Neutrons", "Electrons pairs"], "a": 1, "e": "Bases accept protons.", "d": 1},
    {"t": "The pH of a neutral solution is:", "o": ["0", "7", "14", "1"], "a": 1, "e": "Neutral pH = 7.", "d": 1},
    {"t": "The pH of an acidic solution is:", "o": ["Greater than 7", "Less than 7", "Equal to 7", "Always 14"], "a": 1, "e": "Acids have pH < 7.", "d": 1},
    {"t": "The pH of a basic solution is:", "o": ["Less than 7", "Greater than 7", "Equal to 7", "Always 0"], "a": 1, "e": "Bases have pH > 7.", "d": 1},
    {"t": "The colour of litmus in an acid is:", "o": ["Blue", "Red", "Green", "Yellow"], "a": 1, "e": "Blue litmus turns red in acid.", "d": 1},
    {"t": "The colour of litmus in a base is:", "o": ["Red", "Blue", "Green", "Colourless"], "a": 1, "e": "Red litmus turns blue in base.", "d": 1},
    {"t": "The salt formed when an acid reacts with a base is a ___ reaction.", "o": ["Neutralisation", "Redox", "Precipitation", "Decomposition"], "a": 0, "e": "Acid + base → salt + water is neutralisation.", "d": 1},
    {"t": "The general equation for neutralisation is:", "o": ["Acid + base → salt + water", "Acid + salt → base + water", "Base + salt → acid", "Acid + water → base"], "a": 0, "e": "Acid + base → salt + water.", "d": 1},
    {"t": "The salt formed from hydrochloric acid (HCl) and sodium hydroxide (NaOH) is:", "o": ["Sodium chloride", "Sodium sulphate", "Sodium nitrate", "Sodium carbonate"], "a": 0, "e": "HCl + NaOH → NaCl + H₂O.", "d": 1},
    {"t": "The salt of sulphuric acid is a:", "o": ["Chloride", "Sulphate", "Nitrate", "Carbonate"], "a": 1, "e": "H₂SO₄ forms sulphates.", "d": 1},
    {"t": "The salt of nitric acid is a:", "o": ["Chloride", "Sulphate", "Nitrate", "Carbonate"], "a": 2, "e": "HNO₃ forms nitrates.", "d": 1},
    {"t": "An indicator used in titrations is:", "o": ["Methyl orange", "Salt", "Sugar", "Water"], "a": 0, "e": "Methyl orange is an acid-base indicator.", "d": 1},
    {"t": "Which of the following is a strong acid?", "o": ["Ethanoic acid", "Hydrochloric acid", "Citric acid", "Carbonic acid"], "a": 1, "e": "HCl is a strong (fully dissociated) acid.", "d": 1},
    {"t": "Which of the following is an alkali?", "o": ["HCl", "NaOH", "H₂SO₄", "HNO₃"], "a": 1, "e": "Sodium hydroxide is a soluble base (alkali).", "d": 1},

    # ── Redox ──
    {"t": "Oxidation is the:", "o": ["Loss of electrons", "Gain of electrons", "Loss of protons", "Gain of protons"], "a": 0, "e": "Oxidation = loss of electrons.", "d": 1},
    {"t": "Reduction is the:", "o": ["Loss of electrons", "Gain of electrons", "Loss of protons", "Gain of protons"], "a": 1, "e": "Reduction = gain of electrons.", "d": 1},
    {"t": "An oxidising agent:", "o": ["Gains electrons", "Loses electrons", "Loses protons", "Gains protons"], "a": 0, "e": "An oxidising agent accepts (gains) electrons.", "d": 1},
    {"t": "A reducing agent:", "o": ["Gains electrons", "Loses electrons", "Gains protons", "Loses protons"], "a": 1, "e": "A reducing agent donates (loses) electrons.", "d": 1},
    {"t": "The oxidation number of oxygen in most compounds is:", "o": ["−2", "+2", "0", "−1"], "a": 0, "e": "Oxygen is usually −2.", "d": 1},
    {"t": "The oxidation number of a free element is:", "o": ["1", "0", "−1", "2"], "a": 1, "e": "Free elements have oxidation number 0.", "d": 1},
    {"t": "The oxidation number of hydrogen in compounds is usually:", "o": ["+1", "−1", "0", "2"], "a": 0, "e": "Hydrogen is +1 (except in metal hydrides).", "d": 1},
    {"t": "In the reaction Zn + Cu²⁺ → Zn²⁺ + Cu, zinc is:", "o": ["Oxidised", "Reduced", "Unchanged", "Precipitated"], "a": 0, "e": "Zn loses electrons (oxidised).", "d": 2},

    # ── Electrolysis ──
    {"t": "Electrolysis is the decomposition of a substance by:", "o": ["Heat", "Electric current", "Light", "Pressure"], "a": 1, "e": "Electrolysis uses an electric current.", "d": 1},
    {"t": "The positive electrode in electrolysis is the:", "o": ["Cathode", "Anode", "Electrolyte", "Cell"], "a": 1, "e": "The anode is positive.", "d": 1},
    {"t": "The negative electrode in electrolysis is the:", "o": ["Anode", "Cathode", "Electrolyte", "Cell"], "a": 1, "e": "The cathode is negative.", "d": 1},
    {"t": "The substance that conducts electricity when molten or in solution and is decomposed is the:", "o": ["Electrode", "Electrolyte", "Conductor", "Insulator"], "a": 1, "e": "An electrolyte conducts and is decomposed.", "d": 1},
    {"t": "During electrolysis, cations move to the:", "o": ["Anode", "Cathode", "Surface", "Nowhere"], "a": 1, "e": "Positive cations move to the negative cathode.", "d": 1},
    {"t": "During electrolysis of dilute NaCl, the gas at the cathode is:", "o": ["Chlorine", "Hydrogen", "Oxygen", "Nitrogen"], "a": 1, "e": "H₂ is liberated at the cathode.", "d": 2},
    {"t": "During electrolysis of dilute NaCl, the gas at the anode is:", "o": ["Hydrogen", "Chlorine", "Oxygen", "Nitrogen"], "a": 2, "e": "O₂ (from OH⁻) is liberated at the anode in dilute NaCl.", "d": 2},
    {"t": "Electroplating uses electrolysis to coat a metal with:", "o": ["Another metal", "Paint", "Oil", "Plastic"], "a": 0, "e": "Electroplating deposits a metal coating.", "d": 1},
    {"t": "Faraday's first law of electrolysis relates the mass deposited to:", "o": ["The quantity of electricity", "Temperature", "Pressure", "Volume"], "a": 0, "e": "Mass ∝ charge passed.", "d": 1},
    {"t": "Which of the following is a strong electrolyte?", "o": ["Sugar solution", "Sodium chloride solution", "Distilled water", "Alcohol"], "a": 1, "e": "NaCl solution ionises fully.", "d": 1},

    # ── Energy changes ──
    {"t": "A reaction that releases heat to the surroundings is:", "o": ["Endothermic", "Exothermic", "Isothermal", "Adiabatic"], "a": 1, "e": "Exothermic reactions release heat.", "d": 1},
    {"t": "A reaction that absorbs heat from the surroundings is:", "o": ["Exothermic", "Endothermic", "Isothermal", "Spontaneous"], "a": 1, "e": "Endothermic reactions absorb heat.", "d": 1},
    {"t": "Burning of fuel is an example of a(n) ___ reaction.", "o": ["Endothermic", "Exothermic", "Reversible", "Redox only"], "a": 1, "e": "Combustion releases heat (exothermic).", "d": 1},
    {"t": "The enthalpy change, ΔH, for an exothermic reaction is:", "o": ["Negative", "Positive", "Zero", "Infinite"], "a": 0, "e": "Exothermic ΔH < 0.", "d": 1},
    {"t": "The enthalpy change for an endothermic reaction is:", "o": ["Negative", "Positive", "Zero", "Constant"], "a": 1, "e": "Endothermic ΔH > 0.", "d": 1},
    {"t": "Photosynthesis is an example of a(n) ___ reaction.", "o": ["Exothermic", "Endothermic", "Neutralisation", "Precipitation"], "a": 1, "e": "Photosynthesis absorbs energy (endothermic).", "d": 1},

    # ── Rates of reaction ──
    {"t": "The rate of a chemical reaction increases when:", "o": ["Temperature decreases", "Temperature increases", "Pressure decreases", "Concentration decreases"], "a": 1, "e": "Higher temperature speeds reactions.", "d": 1},
    {"t": "A catalyst speeds up a reaction by:", "o": ["Increasing activation energy", "Lowering activation energy", "Changing the products", "Being consumed"], "a": 1, "e": "Catalysts lower activation energy.", "d": 1},
    {"t": "A catalyst is a substance that:", "o": ["Is used up in the reaction", "Speeds the reaction without being consumed", "Stops the reaction", "Changes the products"], "a": 1, "e": "Catalysts are not consumed.", "d": 1},
    {"t": "Increasing the concentration of reactants generally:", "o": ["Decreases the rate", "Increases the rate", "Has no effect", "Stops the reaction"], "a": 1, "e": "More particles → more collisions → faster rate.", "d": 1},
    {"t": "Increasing the surface area of a solid reactant:", "o": ["Decreases the rate", "Increases the rate", "Has no effect", "Stops the reaction"], "a": 1, "e": "Greater surface area increases contact.", "d": 1},
    {"t": "The minimum energy needed for a reaction to occur is the:", "o": ["Kinetic energy", "Activation energy", "Potential energy", "Bond energy"], "a": 1, "e": "Activation energy is the minimum required energy.", "d": 1},
    {"t": "An enzyme is a biological:", "o": ["Reactant", "Catalyst", "Product", "Solvent"], "a": 1, "e": "Enzymes are biological catalysts.", "d": 1},
    {"t": "Which factor does NOT affect the rate of a reaction?", "o": ["Temperature", "Concentration", "Colour of container", "Surface area"], "a": 2, "e": "Container colour does not affect reaction rate.", "d": 2},

    # ── Chemical equilibrium ──
    {"t": "At equilibrium, the rates of the forward and reverse reactions are:", "o": ["Equal", "Different", "Zero", "Increasing"], "a": 0, "e": "At equilibrium, forward and reverse rates are equal.", "d": 1},
    {"t": "A reversible reaction is denoted by:", "o": ["→", "⇌", "=", "≈"], "a": 1, "e": "⇌ indicates a reversible reaction.", "d": 1},
    {"t": "Le Chatelier's principle predicts the effect of:", "o": ["Changing conditions on equilibrium", "Catalysts only", "Light", "Gravity"], "a": 0, "e": "Le Chatelier's principle describes equilibrium shifts.", "d": 1},
    {"t": "Adding more reactant to a system at equilibrium shifts the equilibrium:", "o": ["Toward products", "Toward reactants", "Not at all", "To zero"], "a": 0, "e": "Adding reactant favours the forward (product) direction.", "d": 2},
    {"t": "For an exothermic reaction, increasing temperature shifts equilibrium:", "o": ["Toward reactants", "Toward products", "Not at all", "Randomly"], "a": 0, "e": "Heat is a product; adding heat favours the reverse.", "d": 2},
    {"t": "A catalyst affects equilibrium by:", "o": ["Shifting it", "Reaching it faster", "Stopping it", "Creating products"], "a": 1, "e": "A catalyst reaches equilibrium faster but does not shift it.", "d": 2},

    # ── Non-metals ──
    {"t": "The most electronegative element is:", "o": ["Oxygen", "Fluorine", "Chlorine", "Nitrogen"], "a": 1, "e": "Fluorine is the most electronegative.", "d": 1},
    {"t": "The most abundant non-metal in the Earth's crust is:", "o": ["Nitrogen", "Oxygen", "Carbon", "Silicon"], "a": 1, "e": "Oxygen is the most abundant.", "d": 1},
    {"t": "The halogen in Group 7 with the smallest atomic size is:", "o": ["Iodine", "Bromine", "Chlorine", "Fluorine"], "a": 3, "e": "Fluorine is the smallest halogen.", "d": 2},
    {"t": "The noble gases are in Group:", "o": ["0", "1", "2", "7"], "a": 0, "e": "Noble gases are in Group 0 (18).", "d": 1},
    {"t": "Noble gases are unreactive because they have:", "o": ["Incomplete outer shells", "A full outer shell", "No electrons", "Only neutrons"], "a": 1, "e": "Full outer shells make them stable.", "d": 1},
    {"t": "The gas used in advertising signs (neon lights) is:", "o": ["Neon", "Oxygen", "Hydrogen", "Chlorine"], "a": 0, "e": "Neon glows in discharge tubes.", "d": 1},
    {"t": "The gas produced when a metal reacts with dilute acid is:", "o": ["Oxygen", "Hydrogen", "Nitrogen", "Carbon dioxide"], "a": 1, "e": "Metal + acid → salt + hydrogen.", "d": 1},
    {"t": "Carbon dioxide turns limewater:", "o": ["Blue", "Milky", "Red", "Yellow"], "a": 1, "e": "CO₂ turns limewater milky.", "d": 1},
    {"t": "The gas that relights a glowing splint is:", "o": ["Hydrogen", "Oxygen", "Nitrogen", "CO₂"], "a": 1, "e": "Oxygen relights a glowing splint.", "d": 1},
    {"t": "The gas that gives a 'pop' with a lit splint is:", "o": ["Oxygen", "Hydrogen", "CO₂", "Nitrogen"], "a": 1, "e": "Hydrogen burns with a pop.", "d": 1},

    # ── Metals ──
    {"t": "Which metal is the most reactive?", "o": ["Gold", "Potassium", "Copper", "Silver"], "a": 1, "e": "Potassium is at the top of the reactivity series.", "d": 1},
    {"t": "Which metal is the least reactive?", "o": ["Gold", "Sodium", "Iron", "Zinc"], "a": 0, "e": "Gold is very unreactive.", "d": 1},
    {"t": "The process of extracting a metal from its ore is:", "o": ["Distillation", "Metallurgy", "Electrolysis only", "Chromatography"], "a": 1, "e": "Metallurgy is extraction of metals.", "d": 1},
    {"t": "Rusting of iron requires:", "o": ["Oxygen and water", "Carbon dioxide only", "Nitrogen", "Helium"], "a": 0, "e": "Rusting needs O₂ and water.", "d": 1},
    {"t": "Rusting of iron can be prevented by:", "o": ["Exposing to air", "Galvanising", "Adding water", "Heating"], "a": 1, "e": "Galvanising (zinc coating) prevents rusting.", "d": 1},
    {"t": "An alloy is a mixture of:", "o": ["Two or more metals (or metal + non-metal)", "Two non-metals", "A metal and water", "Two gases"], "a": 0, "e": "Alloys are metallic mixtures.", "d": 1},
    {"t": "Bronze is an alloy of:", "o": ["Copper and tin", "Iron and carbon", "Copper and zinc", "Lead and tin"], "a": 0, "e": "Bronze = copper + tin.", "d": 1},
    {"t": "Brass is an alloy of:", "o": ["Copper and zinc", "Copper and tin", "Iron and carbon", "Aluminium and copper"], "a": 0, "e": "Brass = copper + zinc.", "d": 1},
    {"t": "Steel is an alloy of:", "o": ["Iron and carbon", "Copper and tin", "Aluminium and zinc", "Lead and tin"], "a": 0, "e": "Steel = iron + carbon.", "d": 1},
    {"t": "Which metal is extracted by electrolysis of its molten ore?", "o": ["Gold", "Aluminium", "Copper", "Silver"], "a": 1, "e": "Aluminium is extracted by electrolysis.", "d": 1},

    # ── Organic compounds ──
    {"t": "Organic chemistry is the study of compounds of:", "o": ["Oxygen", "Carbon", "Nitrogen", "Hydrogen only"], "a": 1, "e": "Organic chemistry studies carbon compounds.", "d": 1},
    {"t": "The simplest hydrocarbon is:", "o": ["Ethane", "Methane", "Propane", "Butane"], "a": 1, "e": "Methane (CH₄) is the simplest hydrocarbon.", "d": 1},
    {"t": "The general formula for alkanes is:", "o": ["CₙH₂ₙ₊₂", "CₙH₂ₙ", "CₙH₂ₙ₋₂", "CₙH₂ₙ₊₁"], "a": 0, "e": "Alkanes: CₙH₂ₙ₊₂.", "d": 1},
    {"t": "The general formula for alkenes is:", "o": ["CₙH₂ₙ₊₂", "CₙH₂ₙ", "CₙH₂ₙ₋₂", "CₙH₂ₙ₊₁"], "a": 1, "e": "Alkenes: CₙH₂ₙ.", "d": 1},
    {"t": "The general formula for alkynes is:", "o": ["CₙH₂ₙ₊₂", "CₙH₂ₙ", "CₙH₂ₙ₋₂", "CₙH₂ₙ₊₁"], "a": 2, "e": "Alkynes: CₙH₂ₙ₋₂.", "d": 1},
    {"t": "Alkanes are saturated hydrocarbons, meaning they contain only:", "o": ["Double bonds", "Single bonds", "Triple bonds", "Benzene rings"], "a": 1, "e": "Saturated = single bonds only.", "d": 1},
    {"t": "Alkenes contain at least one:", "o": ["Single bond", "Double bond", "Triple bond", "Ionic bond"], "a": 1, "e": "Alkenes have a C=C double bond.", "d": 1},
    {"t": "The functional group of alcohols is:", "o": ["−COOH", "−OH", "−CHO", "−NH₂"], "a": 1, "e": "Alcohols contain −OH.", "d": 1},
    {"t": "The functional group of carboxylic acids is:", "o": ["−OH", "−COOH", "−CHO", "−CO"], "a": 1, "e": "Carboxylic acids contain −COOH.", "d": 1},
    {"t": "The functional group of aldehydes is:", "o": ["−OH", "−COOH", "−CHO", "−NH₂"], "a": 2, "e": "Aldehydes contain −CHO.", "d": 1},
    {"t": "The functional group of ketones is:", "o": ["−OH", "−COOH", "−CHO", ">C=O"], "a": 3, "e": "Ketones contain a carbonyl >C=O.", "d": 2},
    {"t": "Ethanol is produced from sugars by:", "o": ["Fermentation", "Distillation", "Electrolysis", "Combustion"], "a": 0, "e": "Fermentation of sugar yields ethanol.", "d": 1},
    {"t": "The monomer of polythene is:", "o": ["Propene", "Ethene", "Butene", "Ethane"], "a": 1, "e": "Polythene is polymerised ethene.", "d": 1},
    {"t": "The process of joining monomers to form polymers is:", "o": ["Cracking", "Polymerisation", "Isomerism", "Fermentation"], "a": 1, "e": "Polymerisation joins monomers.", "d": 1},
    {"t": "Compounds with the same molecular formula but different structures are:", "o": ["Isotopes", "Isomers", "Allotropes", "Polymers"], "a": 1, "e": "Isomers share a formula but differ in structure.", "d": 1},

    # ── Chemistry & industry ──
    {"t": "The Haber process is used to manufacture:", "o": ["Sulphuric acid", "Ammonia", "Nitric acid", "Soap"], "a": 1, "e": "Haber process: N₂ + 3H₂ ⇌ 2NH₃.", "d": 1},
    {"t": "The Contact process manufactures:", "o": ["Ammonia", "Sulphuric acid", "Hydrochloric acid", "Soap"], "a": 1, "e": "Contact process makes H₂SO₄.", "d": 1},
    {"t": "Soap is made by the saponification of:", "o": ["Alcohols", "Fats and oils with alkali", "Alkanes", "Acids only"], "a": 1, "e": "Saponification: fat/oil + alkali → soap + glycerol.", "d": 1},
    {"t": "The catalyst used in the Haber process is:", "o": ["Platinum", "Iron", "Nickel", "Copper"], "a": 1, "e": "Finely divided iron catalyses the Haber process.", "d": 1},
    {"t": "The catalyst used in the Contact process is:", "o": ["Iron", "Vanadium(V) oxide", "Nickel", "Platinum"], "a": 1, "e": "Vanadium(V) oxide catalyses the Contact process.", "d": 1},
    {"t": "Plastics and synthetic fibres are examples of:", "o": ["Monomers", "Polymers", "Isomers", "Ores"], "a": 1, "e": "Plastics are polymers.", "d": 1},
    {"t": "The main component of natural gas is:", "o": ["Ethane", "Methane", "Propane", "Butane"], "a": 1, "e": "Natural gas is mainly methane.", "d": 1},
    {"t": "Crude oil is separated into fractions by:", "o": ["Fractional distillation", "Filtration", "Crystallisation", "Sublimation"], "a": 0, "e": "Fractional distillation separates crude oil.", "d": 1},

    # ── More mixed ──
    {"t": "The symbol for the element sodium is:", "o": ["S", "Na", "So", "Sn"], "a": 1, "e": "Sodium's symbol is Na (from natrium).", "d": 1},
    {"t": "The symbol for potassium is:", "o": ["P", "K", "Po", "Pt"], "a": 1, "e": "Potassium's symbol is K (kalium).", "d": 1},
    {"t": "The symbol for iron is:", "o": ["I", "Fe", "Ir", "In"], "a": 1, "e": "Iron's symbol is Fe (ferrum).", "d": 1},
    {"t": "The symbol for gold is:", "o": ["G", "Au", "Ag", "Go"], "a": 1, "e": "Gold's symbol is Au (aurum).", "d": 1},
    {"t": "The symbol for silver is:", "o": ["S", "Ag", "Si", "Sv"], "a": 1, "e": "Silver's symbol is Ag (argentum).", "d": 1},
    {"t": "The symbol for lead is:", "o": ["L", "Pb", "Le", "Ld"], "a": 1, "e": "Lead's symbol is Pb (plumbum).", "d": 1},
    {"t": "The chemical formula for table salt is:", "o": ["NaCl", "KCl", "Na₂CO₃", "CaCl₂"], "a": 0, "e": "Table salt is NaCl.", "d": 1},
    {"t": "The chemical formula for baking soda is:", "o": ["NaHCO₃", "NaCl", "Na₂CO₃", "NaOH"], "a": 0, "e": "Baking soda is sodium hydrogen carbonate, NaHCO₃.", "d": 1},
    {"t": "The chemical formula for limestone is:", "o": ["CaCO₃", "CaO", "Ca(OH)₂", "CaCl₂"], "a": 0, "e": "Limestone is calcium carbonate, CaCO₃.", "d": 1},
    {"t": "The gas produced when limestone is heated strongly is:", "o": ["Oxygen", "Carbon dioxide", "Hydrogen", "Nitrogen"], "a": 1, "e": "CaCO₃ → CaO + CO₂.", "d": 1},
    {"t": "The melting of ice is an example of a:", "o": ["Chemical change", "Physical change", "Redox reaction", "Combustion"], "a": 1, "e": "Melting changes state only (physical).", "d": 1},
    {"t": "Which of these is a chemical change?", "o": ["Melting", "Rusting", "Freezing", "Boiling"], "a": 1, "e": "Rusting forms a new substance (chemical).", "d": 1},
    {"t": "The process by which a liquid becomes a gas at its surface is:", "o": ["Boiling", "Evaporation", "Sublimation", "Condensation"], "a": 1, "e": "Evaporation occurs at the surface.", "d": 1},
    {"t": "The process by which a gas becomes a liquid is:", "o": ["Evaporation", "Condensation", "Sublimation", "Freezing"], "a": 1, "e": "Condensation = gas → liquid.", "d": 1},
    {"t": "The density of a substance equals:", "o": ["Mass/volume", "Volume/mass", "Mass × volume", "Weight/area"], "a": 0, "e": "Density = mass/volume.", "d": 1},
    {"t": "The relative molecular mass of CO₂ is (C=12, O=16):", "o": ["44", "28", "22", "32"], "a": 0, "e": "12 + 2×16 = 44.", "d": 1},
    {"t": "The number of atoms in one molecule of H₂SO₄ is:", "o": ["7", "6", "5", "8"], "a": 0, "e": "2 H + 1 S + 4 O = 7 atoms.", "d": 2},
    {"t": "The charge on a proton is:", "o": ["Positive", "Negative", "Neutral", "Variable"], "a": 0, "e": "Protons are positively charged.", "d": 1},
    {"t": "The charge on an electron is:", "o": ["Positive", "Negative", "Neutral", "Variable"], "a": 1, "e": "Electrons are negatively charged.", "d": 1},
    {"t": "The pH scale ranges from:", "o": ["0 to 14", "1 to 10", "0 to 7", "1 to 14"], "a": 0, "e": "pH ranges 0–14.", "d": 1},
    # ── More mixed (organic + general) ──
    {"t": "The molecular formula of ethane is:", "o": ["C₂H₆", "C₂H₄", "C₂H₂", "CH₄"], "a": 0, "e": "Ethane is C₂H₆.", "d": 1},
    {"t": "The molecular formula of ethene is:", "o": ["C₂H₆", "C₂H₄", "C₂H₂", "CH₄"], "a": 1, "e": "Ethene is C₂H₄.", "d": 1},
    {"t": "The molecular formula of ethyne (acetylene) is:", "o": ["C₂H₆", "C₂H₄", "C₂H₂", "CH₄"], "a": 2, "e": "Ethyne is C₂H₂.", "d": 1},
    {"t": "The IUPAC name of CH₃CH₂CH₃ is:", "o": ["Propane", "Butane", "Ethane", "Pentane"], "a": 0, "e": "Three carbons = propane.", "d": 2},
    {"t": "The IUPAC name of CH₃COOH is:", "o": ["Methanol", "Ethanoic acid", "Ethanol", "Methanoic acid"], "a": 1, "e": "CH₃COOH is ethanoic (acetic) acid.", "d": 2},
    {"t": "The IUPAC name of C₂H₅OH is:", "o": ["Methanol", "Ethanol", "Propanol", "Ethanal"], "a": 1, "e": "C₂H₅OH is ethanol.", "d": 1},
    {"t": "The gas used to extinguish fires is often:", "o": ["Oxygen", "Carbon dioxide", "Hydrogen", "Helium"], "a": 1, "e": "CO₂ does not support combustion.", "d": 1},
    {"t": "The gas that is lighter than air and used in balloons is:", "o": ["Hydrogen", "Oxygen", "CO₂", "Chlorine"], "a": 0, "e": "Hydrogen (or helium) is lighter than air.", "d": 1},
    {"t": "The element with atomic number 6 is:", "o": ["Nitrogen", "Carbon", "Oxygen", "Boron"], "a": 1, "e": "Carbon has atomic number 6.", "d": 1},
    {"t": "The element with atomic number 8 is:", "o": ["Carbon", "Nitrogen", "Oxygen", "Fluorine"], "a": 2, "e": "Oxygen has atomic number 8.", "d": 1},
    {"t": "The element with atomic number 20 is:", "o": ["Calcium", "Potassium", "Sodium", "Magnesium"], "a": 0, "e": "Calcium has atomic number 20.", "d": 1},
    {"t": "The group number of the alkali metals is:", "o": ["Group 1", "Group 2", "Group 7", "Group 0"], "a": 0, "e": "Alkali metals are Group 1.", "d": 1},
    {"t": "The group number of the alkaline earth metals is:", "o": ["Group 1", "Group 2", "Group 7", "Group 0"], "a": 1, "e": "Alkaline earth metals are Group 2.", "d": 1},
    {"t": "The group number of the halogens is:", "o": ["Group 1", "Group 2", "Group 7", "Group 0"], "a": 2, "e": "Halogens are Group 7 (17).", "d": 1},
    {"t": "The group number of the noble gases is:", "o": ["Group 1", "Group 2", "Group 7", "Group 0"], "a": 3, "e": "Noble gases are Group 0 (18).", "d": 1},
    {"t": "Which element is a metalloid?", "o": ["Sodium", "Silicon", "Magnesium", "Chlorine"], "a": 1, "e": "Silicon is a metalloid (semiconductor).", "d": 2},
    {"t": "The bond in a molecule of hydrogen (H₂) is:", "o": ["Ionic", "Covalent", "Metallic", "Hydrogen"], "a": 1, "e": "H₂ shares electrons (covalent).", "d": 1},
    {"t": "The bond in sodium chloride is:", "o": ["Covalent", "Ionic", "Metallic", "Hydrogen"], "a": 1, "e": "NaCl has ionic bonding.", "d": 1},
    {"t": "The bond between metal atoms in a metal is:", "o": ["Ionic", "Covalent", "Metallic", "Hydrogen"], "a": 2, "e": "Metals have metallic bonding (sea of electrons).", "d": 1},
    {"t": "The SI unit of amount of substance is the:", "o": ["Mole", "Gram", "Litre", "Kilogram"], "a": 0, "e": "Amount of substance is in moles.", "d": 1},
    {"t": "One mole of a gas at STP occupies:", "o": ["22.4 dm³", "11.2 dm³", "44.8 dm³", "1 dm³"], "a": 0, "e": "Molar volume at STP = 22.4 dm³.", "d": 1},
    {"t": "STP stands for:", "o": ["Standard temperature and pressure", "Specific thermal point", "Standard time and pressure", "Single temperature point"], "a": 0, "e": "STP = standard temperature and pressure (0°C, 1 atm).", "d": 1},
    {"t": "The process of converting alkanes to smaller hydrocarbons by heating is:", "o": ["Cracking", "Polymerisation", "Fermentation", "Distillation"], "a": 0, "e": "Cracking breaks large alkanes into smaller ones.", "d": 1},
    {"t": "Which of these is a saturated hydrocarbon?", "o": ["Ethene", "Methane", "Ethyne", "Benzene"], "a": 1, "e": "Methane (alkane) is saturated.", "d": 1},
    {"t": "The main gas produced during fermentation of sugar is:", "o": ["Oxygen", "Carbon dioxide", "Hydrogen", "Nitrogen"], "a": 1, "e": "Fermentation produces ethanol and CO₂.", "d": 1},
    {"t": "The colour of copper(II) sulphate solution is:", "o": ["Blue", "Green", "Yellow", "Colourless"], "a": 0, "e": "CuSO₄ solution is blue.", "d": 1},
    {"t": "The colour of anhydrous copper(II) sulphate is:", "o": ["Blue", "White", "Green", "Black"], "a": 1, "e": "Anhydrous CuSO₄ is white.", "d": 1},
    {"t": "The test for water using anhydrous copper(II) sulphate turns it:", "o": ["White", "Blue", "Green", "Red"], "a": 1, "e": "Water turns white anhydrous CuSO₄ blue.", "d": 1},
    {"t": "The flame colour of sodium in a flame test is:", "o": ["Yellow", "Green", "Red", "Blue"], "a": 0, "e": "Sodium gives a yellow flame.", "d": 1},
    {"t": "The flame colour of potassium is:", "o": ["Yellow", "Lilac", "Red", "Green"], "a": 1, "e": "Potassium gives a lilac flame.", "d": 1},
    {"t": "The flame colour of calcium is:", "o": ["Yellow", "Brick-red", "Green", "Blue"], "a": 1, "e": "Calcium gives a brick-red flame.", "d": 1},
    {"t": "Which of the following is a good conductor of electricity?", "o": ["Graphite", "Diamond", "Plastic", "Wood"], "a": 0, "e": "Graphite conducts electricity (delocalised electrons).", "d": 1},
    {"t": "Diamond and graphite are allotropes of:", "o": ["Oxygen", "Carbon", "Silicon", "Sulphur"], "a": 1, "e": "Diamond and graphite are carbon allotropes.", "d": 1},
    {"t": "The allotrope of oxygen is:", "o": ["Ozone", "Carbon dioxide", "Water", "Hydrogen"], "a": 0, "e": "Ozone (O₃) is an allotrope of oxygen.", "d": 1},
    {"t": "The relative molecular mass of H₂SO₄ is (H=1, S=32, O=16):", "o": ["98", "82", "66", "100"], "a": 0, "e": "2 + 32 + 64 = 98.", "d": 2},
]

build("che", "Chemistry", QUESTIONS[:200])
