from _common import build

QUESTIONS = [
    # ── Nature & scope ──
    {"t": "Economics is best defined as the study of:", "o": ["Money only", "How scarce resources are allocated to satisfy wants", "Stock markets", "Government only"], "a": 1, "e": "Economics studies allocation of scarce resources.", "d": 1},
    {"t": "The fundamental economic problem is:", "o": ["Inflation", "Scarcity", "Unemployment", "Taxation"], "a": 1, "e": "Scarcity of resources vs unlimited wants.", "d": 1},
    {"t": "The term 'economics' is derived from the Greek word meaning:", "o": ["Wealth", "Household management", "Trade", "Money"], "a": 1, "e": "'Oikonomia' means household management.", "d": 1},
    {"t": "Microeconomics is concerned with:", "o": ["The whole economy", "Individual units like households and firms", "National income", "Inflation"], "a": 1, "e": "Microeconomics studies individual units.", "d": 1},
    {"t": "Macroeconomics is concerned with:", "o": ["Individual firms", "The economy as a whole", "Households", "Single markets"], "a": 1, "e": "Macroeconomics studies the whole economy.", "d": 1},
    {"t": "The father of modern economics is:", "o": ["Karl Marx", "Adam Smith", "Keynes", "Ricardo"], "a": 1, "e": "Adam Smith is the father of economics.", "d": 1},
    {"t": "Adam Smith's famous book is:", "o": ["Das Kapital", "The Wealth of Nations", "Principles of Economics", "General Theory"], "a": 1, "e": "'The Wealth of Nations' (1776).", "d": 1},
    {"t": "Opportunity cost is best defined as:", "o": ["The money cost of a good", "The value of the next best alternative forgone", "Total cost", "Sunk cost"], "a": 1, "e": "Opportunity cost = the next best alternative sacrificed.", "d": 1},
    {"t": "Goods that are used to produce other goods are called:", "o": ["Consumer goods", "Capital goods", "Free goods", "Luxury goods"], "a": 1, "e": "Capital goods produce other goods.", "d": 1},
    {"t": "Goods that directly satisfy wants are:", "o": ["Capital goods", "Consumer goods", "Producer goods", "Intermediate goods"], "a": 1, "e": "Consumer goods satisfy wants directly.", "d": 1},

    # ── Basic economic problems ──
    {"t": "The basic economic questions include all EXCEPT:", "o": ["What to produce", "How to produce", "For whom to produce", "Why to consume"], "a": 3, "e": "The three questions are what, how and for whom to produce.", "d": 1},
    {"t": "The scale of preference is a list of wants arranged in order of:", "o": ["Size", "Priority/importance", "Cost", "Alphabet"], "a": 1, "e": "Wants are ranked by importance.", "d": 1},
    {"t": "The curve showing the maximum combinations of two goods an economy can produce is the:", "o": ["Demand curve", "Production possibility curve", "Supply curve", "Indifference curve"], "a": 1, "e": "The PPC shows production possibilities.", "d": 1},
    {"t": "A point inside the production possibility curve represents:", "o": ["Full employment", "Under-utilisation of resources", "Impossible output", "Maximum output"], "a": 1, "e": "Inside the PPC = resources not fully used.", "d": 2},
    {"t": "A point outside the production possibility curve represents:", "o": ["Full employment", "Unattainable output", "Efficient output", "Unemployment"], "a": 1, "e": "Outside the PPC is currently unattainable.", "d": 2},
    {"t": "Free goods are goods that are:", "o": ["Scarce", "Abundant and have no opportunity cost", "Expensive", "Limited"], "a": 1, "e": "Free goods (like air) are abundant.", "d": 1},
    {"t": "Economic goods are goods that are:", "o": ["Free", "Scarce relative to demand", "Unlimited", "Valueless"], "a": 1, "e": "Economic goods are scarce.", "d": 1},

    # ── Production & factors ──
    {"t": "The creation of utility is known as:", "o": ["Consumption", "Production", "Distribution", "Exchange"], "a": 1, "e": "Production creates utility.", "d": 1},
    {"t": "The four factors of production are:", "o": ["Land, labour, capital, entrepreneur", "Land, money, labour, goods", "Capital, profit, rent, wages", "Land, labour, demand, supply"], "a": 0, "e": "The four factors: land, labour, capital, entrepreneurship.", "d": 1},
    {"t": "The reward for land is:", "o": ["Wages", "Rent", "Interest", "Profit"], "a": 1, "e": "Rent is the reward for land.", "d": 1},
    {"t": "The reward for labour is:", "o": ["Rent", "Wages", "Interest", "Profit"], "a": 1, "e": "Wages reward labour.", "d": 1},
    {"t": "The reward for capital is:", "o": ["Rent", "Interest", "Wages", "Profit"], "a": 1, "e": "Interest rewards capital.", "d": 1},
    {"t": "The reward for entrepreneurship is:", "o": ["Rent", "Profit", "Wages", "Interest"], "a": 1, "e": "Profit rewards the entrepreneur.", "d": 1},
    {"t": "Labour as a factor of production is:", "o": ["Only physical work", "Human effort (mental and physical) used in production", "Only skilled work", "Machines"], "a": 1, "e": "Labour is human effort in production.", "d": 1},
    {"t": "Capital in economics refers to:", "o": ["Money only", "Man-made resources used in production", "Land", "Labour"], "a": 1, "e": "Capital is man-made producer goods.", "d": 1},
    {"t": "The entrepreneur's main function is to:", "o": ["Provide labour", "Organise and bear risks", "Provide land", "Lend money"], "a": 1, "e": "The entrepreneur organises and bears risks.", "d": 1},
    {"t": "The factor of production that is fixed and free gift of nature is:", "o": ["Labour", "Land", "Capital", "Entrepreneur"], "a": 1, "e": "Land is a free gift of nature.", "d": 1},
    {"t": "Division of labour is the:", "o": ["Splitting of a task into smaller specialised tasks", "Working long hours", "Reducing the workforce", "Hiring more workers"], "a": 0, "e": "Division of labour splits work into tasks.", "d": 1},
    {"t": "Specialisation leads to:", "o": ["Lower productivity", "Increased productivity and efficiency", "Higher costs", "Less output"], "a": 1, "e": "Specialisation raises productivity.", "d": 1},
    {"t": "One disadvantage of division of labour is:", "o": ["Higher efficiency", "Monotony/boredom", "More output", "Lower costs"], "a": 1, "e": "Repetitive work causes monotony.", "d": 1},

    # ── Economic systems ──
    {"t": "An economic system where resources are owned and controlled by the government is:", "o": ["Capitalism", "Socialism", "Mixed economy", "Laissez-faire"], "a": 1, "e": "Socialism = government control.", "d": 1},
    {"t": "An economic system based on private ownership and free markets is:", "o": ["Socialism", "Capitalism", "Communism", "Traditional"], "a": 1, "e": "Capitalism = private ownership.", "d": 1},
    {"t": "An economy combining private and public ownership is a:", "o": ["Pure capitalism", "Mixed economy", "Pure socialism", "Traditional economy"], "a": 1, "e": "A mixed economy combines both.", "d": 1},
    {"t": "Nigeria operates a:", "o": ["Pure capitalist economy", "Mixed economy", "Pure socialist economy", "Command economy"], "a": 1, "e": "Nigeria has a mixed economy.", "d": 1},
    {"t": "An economic system based on customs and traditions is:", "o": ["Capitalism", "Traditional economy", "Socialism", "Mixed economy"], "a": 1, "e": "Traditional economies follow customs.", "d": 1},

    # ── Demand & supply ──
    {"t": "The quantity of a good consumers are willing and able to buy at a price is:", "o": ["Supply", "Demand", "Utility", "Production"], "a": 1, "e": "Demand = willingness + ability to buy.", "d": 1},
    {"t": "The law of demand states that, other things being equal, as price falls:", "o": ["Quantity demanded falls", "Quantity demanded rises", "Demand falls", "Supply rises"], "a": 1, "e": "Price and quantity demanded are inversely related.", "d": 1},
    {"t": "The law of supply states that, other things being equal, as price rises:", "o": ["Quantity supplied falls", "Quantity supplied rises", "Supply falls", "Demand rises"], "a": 1, "e": "Price and quantity supplied are directly related.", "d": 1},
    {"t": "The demand curve slopes:", "o": ["Upward", "Downward from left to right", "Horizontally", "Vertically"], "a": 1, "e": "The demand curve slopes downward.", "d": 1},
    {"t": "The supply curve slopes:", "o": ["Downward", "Upward from left to right", "Horizontally", "Vertically"], "a": 1, "e": "The supply curve slopes upward.", "d": 1},
    {"t": "The price at which quantity demanded equals quantity supplied is the:", "o": ["Market price", "Equilibrium price", "Maximum price", "Minimum price"], "a": 1, "e": "Equilibrium price clears the market.", "d": 1},
    {"t": "A movement along the demand curve is caused by a change in:", "o": ["Income", "Price of the good", "Tastes", "Population"], "a": 1, "e": "A price change moves along the curve.", "d": 2},
    {"t": "A shift of the demand curve is caused by a change in:", "o": ["Price of the good", "Income or tastes", "Quantity demanded", "Nothing"], "a": 1, "e": "Non-price factors shift the curve.", "d": 2},
    {"t": "Goods for which demand increases as income increases are:", "o": ["Inferior goods", "Normal goods", "Giffen goods", "Luxury goods only"], "a": 1, "e": "Normal goods see demand rise with income.", "d": 1},
    {"t": "Goods for which demand falls as income rises are:", "o": ["Normal goods", "Inferior goods", "Substitutes", "Complements"], "a": 1, "e": "Inferior goods are bought less as income rises.", "d": 1},
    {"t": "Goods that are used together (e.g. car and petrol) are:", "o": ["Substitutes", "Complements", "Inferior", "Giffen"], "a": 1, "e": "Complements are used together.", "d": 1},
    {"t": "Goods that can replace each other (e.g. tea and coffee) are:", "o": ["Complements", "Substitutes", "Inferior", "Normal"], "a": 1, "e": "Substitutes replace each other.", "d": 1},
    {"t": "If the price of a substitute rises, the demand for the good:", "o": ["Falls", "Rises", "Is unchanged", "Becomes zero"], "a": 1, "e": "Demand shifts to the cheaper substitute.", "d": 2},
    {"t": "If the price of a complement rises, the demand for the good:", "o": ["Rises", "Falls", "Is unchanged", "Doubles"], "a": 1, "e": "Complements are used together; demand falls.", "d": 2},
    {"t": "A Giffen good is one whose demand:", "o": ["Falls as price falls", "Rises as price rises", "Is constant", "Is zero"], "a": 1, "e": "Giffen goods defy the law of demand.", "d": 2},
    {"t": "Excess supply occurs when price is:", "o": ["Below equilibrium", "Above equilibrium", "At equilibrium", "Zero"], "a": 1, "e": "Above-equilibrium prices cause surplus.", "d": 1},
    {"t": "Excess demand occurs when price is:", "o": ["Above equilibrium", "Below equilibrium", "At equilibrium", "Infinite"], "a": 1, "e": "Below-equilibrium prices cause shortage.", "d": 1},

    # ── Elasticity ──
    {"t": "Price elasticity of demand measures:", "o": ["Responsiveness of quantity demanded to price changes", "Total demand", "Total supply", "Income only"], "a": 0, "e": "PED measures responsiveness to price.", "d": 1},
    {"t": "Demand is elastic when the elasticity value is:", "o": ["Zero", "Greater than 1", "Equal to 1", "Less than 1"], "a": 1, "e": "Elastic demand > 1.", "d": 1},
    {"t": "Demand is inelastic when the elasticity value is:", "o": ["Greater than 1", "Less than 1", "Equal to 1", "Infinite"], "a": 1, "e": "Inelastic demand < 1.", "d": 1},
    {"t": "Demand is perfectly inelastic when elasticity equals:", "o": ["1", "0", "Infinity", "−1"], "a": 1, "e": "Perfectly inelastic = 0.", "d": 1},
    {"t": "Goods with no close substitutes tend to have:", "o": ["Elastic demand", "Inelastic demand", "Perfectly elastic demand", "Zero demand"], "a": 1, "e": "Few substitutes → inelastic demand.", "d": 2},
    {"t": "The cross elasticity of demand for complements is:", "o": ["Positive", "Negative", "Zero", "Infinite"], "a": 1, "e": "Complements have negative cross elasticity.", "d": 2},
    {"t": "Income elasticity of demand for normal goods is:", "o": ["Negative", "Positive", "Zero", "Infinite"], "a": 1, "e": "Normal goods have positive income elasticity.", "d": 2},

    # ── Utility & consumer behaviour ──
    {"t": "Utility in economics means:", "o": ["Usefulness only", "Satisfaction derived from consuming a good", "Profit", "Cost"], "a": 1, "e": "Utility = satisfaction from consumption.", "d": 1},
    {"t": "The additional satisfaction from consuming one more unit is:", "o": ["Total utility", "Marginal utility", "Average utility", "Net utility"], "a": 1, "e": "Marginal utility is the extra satisfaction.", "d": 1},
    {"t": "The law of diminishing marginal utility states that as more units are consumed:", "o": ["Marginal utility rises", "Marginal utility falls", "Total utility falls immediately", "Price rises"], "a": 1, "e": "Marginal utility diminishes with each extra unit.", "d": 1},
    {"t": "The law of diminishing marginal utility explains the ___ slope of the demand curve.", "o": ["Upward", "Downward", "Horizontal", "Vertical"], "a": 1, "e": "Diminishing utility → downward demand curve.", "d": 2},
    {"t": "Total utility is maximised when marginal utility is:", "o": ["Maximum", "Zero", "Negative", "Infinite"], "a": 1, "e": "TU peaks when MU = 0.", "d": 2},

    # ── Cost & revenue ──
    {"t": "Fixed costs are costs that:", "o": ["Vary with output", "Do not vary with output", "Are always zero", "Equal revenue"], "a": 1, "e": "Fixed costs are constant regardless of output.", "d": 1},
    {"t": "Variable costs are costs that:", "o": ["Are constant", "Vary with output", "Are zero", "Equal fixed costs"], "a": 1, "e": "Variable costs change with output.", "d": 1},
    {"t": "Total cost equals:", "o": ["Fixed cost + variable cost", "Fixed cost × variable cost", "Revenue − profit", "Price × quantity"], "a": 0, "e": "TC = FC + VC.", "d": 1},
    {"t": "Average cost is:", "o": ["Total cost ÷ quantity", "Total cost × quantity", "Variable cost only", "Fixed cost only"], "a": 0, "e": "AC = TC/Q.", "d": 1},
    {"t": "Marginal cost is the cost of:", "o": ["Producing one more unit", "The first unit", "All units", "Fixed inputs"], "a": 0, "e": "MC = extra cost of one more unit.", "d": 1},
    {"t": "Total revenue equals:", "o": ["Price × quantity", "Cost × quantity", "Profit + cost", "Price + quantity"], "a": 0, "e": "TR = P × Q.", "d": 1},
    {"t": "Profit equals:", "o": ["Total revenue − total cost", "Total cost − revenue", "Revenue + cost", "Price × cost"], "a": 0, "e": "Profit = TR − TC.", "d": 1},
    {"t": "The break-even point occurs when:", "o": ["Revenue exceeds cost", "Revenue equals cost", "Revenue is zero", "Cost is zero"], "a": 1, "e": "Break-even: TR = TC (zero profit).", "d": 1},

    # ── Market structures ──
    {"t": "A market with many buyers and sellers of identical products is:", "o": ["Perfect competition", "Monopoly", "Oligopoly", "Monopolistic competition"], "a": 0, "e": "Perfect competition: many firms, identical goods.", "d": 1},
    {"t": "A market with a single seller is a:", "o": ["Monopoly", "Oligopoly", "Duopoly", "Monopsony"], "a": 0, "e": "Monopoly = one seller.", "d": 1},
    {"t": "A market with a few large sellers is an:", "o": ["Monopoly", "Oligopoly", "Perfect competition", "Monopsony"], "a": 1, "e": "Oligopoly = few sellers.", "d": 1},
    {"t": "A market with a single buyer is a:", "o": ["Monopoly", "Monopsony", "Oligopoly", "Duopoly"], "a": 1, "e": "Monopsony = one buyer.", "d": 1},
    {"t": "A market with two sellers is a:", "o": ["Monopoly", "Duopoly", "Oligopoly", "Monopsony"], "a": 1, "e": "Duopoly = two sellers.", "d": 1},
    {"t": "In perfect competition, firms are price:", "o": ["Makers", "Takers", "Setters", "Leaders"], "a": 1, "e": "Firms are price takers in perfect competition.", "d": 1},
    {"t": "A monopolist is a price:", "o": ["Taker", "Maker", "Follower", "Discounter"], "a": 1, "e": "A monopolist sets price.", "d": 1},
    {"t": "Barriers to entry are highest in:", "o": ["Perfect competition", "Monopoly", "Monopolistic competition", "Oligopoly"], "a": 1, "e": "Monopoly has the highest entry barriers.", "d": 1},
    {"t": "Product differentiation is a feature of:", "o": ["Perfect competition", "Monopolistic competition", "Pure monopoly", "Monopsony"], "a": 1, "e": "Monopolistic competition features differentiation.", "d": 1},
    {"t": "The market where shares are bought and sold is the:", "o": ["Commodity market", "Stock exchange", "Black market", "Factor market"], "a": 1, "e": "Shares trade on the stock exchange.", "d": 1},

    # ── National income ──
    {"t": "National income is the total value of:", "o": ["Imports", "Goods and services produced in a country in a year", "Exports", "Taxes"], "a": 1, "e": "National income measures annual output value.", "d": 1},
    {"t": "GDP stands for:", "o": ["Gross Domestic Product", "Gross Direct Profit", "General Domestic Price", "Gross Development Plan"], "a": 0, "e": "GDP = Gross Domestic Product.", "d": 1},
    {"t": "GNP stands for:", "o": ["Gross National Product", "General Net Profit", "Gross Net Price", "Gross National Price"], "a": 0, "e": "GNP = Gross National Product.", "d": 1},
    {"t": "The difference between GDP and GNP is:", "o": ["Depreciation", "Net factor income from abroad", "Taxes", "Subsidies"], "a": 1, "e": "GNP = GDP + net factor income from abroad.", "d": 2},
    {"t": "The circular flow of income shows the flow between:", "o": ["Firms and households", "Only firms", "Only households", "Banks only"], "a": 0, "e": "Income flows between households and firms.", "d": 1},
    {"t": "Per capita income is national income divided by:", "o": ["Area", "Population", "Exports", "Number of firms"], "a": 1, "e": "Per capita income = NI/population.", "d": 1},
    {"t": "The three methods of measuring national income are:", "o": ["Income, output, expenditure", "Input, output, profit", "Income, tax, output", "Output, cost, revenue"], "a": 0, "e": "National income is measured by income, output or expenditure.", "d": 1},
    {"t": "Depreciation is also known as:", "o": ["Capital consumption", "Capital gain", "Net investment", "Gross profit"], "a": 0, "e": "Depreciation = capital consumption allowance.", "d": 1},
    {"t": "Net national product equals GNP minus:", "o": ["Taxes", "Depreciation", "Subsidies", "Exports"], "a": 1, "e": "NNP = GNP − depreciation.", "d": 2},

    # ── Money & banking ──
    {"t": "The three functions of money are:", "o": ["Medium of exchange, store of value, unit of account", "Saving, spending, taxing", "Borrowing, lending, trading", "Cash, credit, debit"], "a": 0, "e": "Money's functions: medium of exchange, store of value, unit of account.", "d": 1},
    {"t": "Barter is the exchange of:", "o": ["Goods for money", "Goods for goods", "Money for money", "Services for money"], "a": 1, "e": "Barter = direct exchange of goods.", "d": 1},
    {"t": "The main disadvantage of barter is the:", "o": ["Lack of double coincidence of wants", "Too much money", "Low taxes", "High prices"], "a": 0, "e": "Barter needs a double coincidence of wants.", "d": 1},
    {"t": "The central bank of Nigeria is the:", "o": ["First Bank", "Central Bank of Nigeria", "Union Bank", "Wema Bank"], "a": 1, "e": "The CBN is the central bank.", "d": 1},
    {"t": "The main function of a central bank is to:", "o": ["Maximise profit", "Control money supply and issue currency", "Give consumer loans", "Sell goods"], "a": 1, "e": "The central bank issues currency and controls money supply.", "d": 1},
    {"t": "Commercial banks primarily:", "o": ["Issue currency", "Accept deposits and give loans", "Control inflation", "Set interest rates"], "a": 1, "e": "Commercial banks take deposits and lend.", "d": 1},
    {"t": "The rate at which the central bank lends to commercial banks is the:", "o": ["Exchange rate", "Bank rate (rediscount rate)", "Interest rate", "Inflation rate"], "a": 1, "e": "The bank rate is the central bank's lending rate.", "d": 2},
    {"t": "The current account in a bank is used for:", "o": ["Saving", "Frequent transactions", "Long-term saving", "Pensions"], "a": 1, "e": "Current accounts suit frequent transactions.", "d": 1},
    {"t": "The savings account pays:", "o": ["No interest", "Interest on deposits", "Fees", "Taxes only"], "a": 1, "e": "Savings accounts earn interest.", "d": 1},
    {"t": "A cheque is a:", "o": ["Form of money", "Written order to a bank to pay money", "Loan", "Currency note"], "a": 1, "e": "A cheque orders a bank to pay.", "d": 1},
    {"t": "Near money refers to assets that:", "o": ["Are cash", "Can be easily converted to cash", "Cannot be converted", "Are illegal"], "a": 1, "e": "Near money (e.g. deposits) converts easily to cash.", "d": 2},
    {"t": "The quantity theory of money links money supply to:", "o": ["Price level", "Weather", "Population", "Exports"], "a": 0, "e": "The quantity theory links money to prices.", "d": 2},

    # ── Inflation & deflation ──
    {"t": "Inflation is a persistent rise in the:", "o": ["Value of money", "General price level", "Interest rate", "Exchange rate"], "a": 1, "e": "Inflation = sustained price level rise.", "d": 1},
    {"t": "Deflation is a persistent fall in the:", "o": ["Money supply", "General price level", "Interest rate", "Unemployment"], "a": 1, "e": "Deflation = sustained price fall.", "d": 1},
    {"t": "Demand-pull inflation is caused by:", "o": ["Excess aggregate demand", "Rising production costs", "Falling demand", "Tax cuts only"], "a": 0, "e": "Demand-pull = too much demand.", "d": 1},
    {"t": "Cost-push inflation is caused by:", "o": ["Excess demand", "Rising production costs", "More money", "Lower wages"], "a": 1, "e": "Cost-push = rising costs push prices up.", "d": 1},
    {"t": "Hyperinflation is:", "o": ["Mild inflation", "Extremely rapid inflation", "Zero inflation", "Deflation"], "a": 1, "e": "Hyperinflation is very rapid price rise.", "d": 1},
    {"t": "The effect of inflation on debtors is that they:", "o": ["Lose", "Gain", "Are unaffected", "Default"], "a": 1, "e": "Debtors gain (repay with cheaper money).", "d": 2},
    {"t": "Inflation is measured by the:", "o": ["Consumer Price Index", "Stock exchange", "Tax rate", "Population"], "a": 0, "e": "The CPI measures inflation.", "d": 1},

    # ── Public finance & taxation ──
    {"t": "Taxation is the compulsory levy by:", "o": ["Banks", "Government", "Firms", "Individuals only"], "a": 1, "e": "Taxes are levied by government.", "d": 1},
    {"t": "A direct tax is one levied on:", "o": ["Goods and services", "Income and property", "Imports", "Exports"], "a": 1, "e": "Direct taxes hit income/property (e.g. income tax).", "d": 1},
    {"t": "An indirect tax is levied on:", "o": ["Income", "Goods and services", "Property", "Profits"], "a": 1, "e": "Indirect taxes are on goods/services (e.g. VAT).", "d": 1},
    {"t": "Which of the following is a direct tax?", "o": ["VAT", "Personal income tax", "Customs duty", "Excise duty"], "a": 1, "e": "Income tax is direct.", "d": 1},
    {"t": "Which of the following is an indirect tax?", "o": ["Income tax", "Value Added Tax (VAT)", "Company tax", "Capital gains tax"], "a": 1, "e": "VAT is indirect.", "d": 1},
    {"t": "A progressive tax is one where the rate:", "o": ["Falls as income rises", "Rises as income rises", "Is constant", "Is zero"], "a": 1, "e": "Progressive tax rate rises with income.", "d": 1},
    {"t": "A regressive tax is one where the rate:", "o": ["Falls as income rises", "Rises as income rises", "Is constant", "Is zero"], "a": 0, "e": "Regressive tax takes a smaller share as income rises.", "d": 1},
    {"t": "A proportional (flat) tax has a rate that is:", "o": ["Constant", "Progressive", "Regressive", "Variable"], "a": 0, "e": "Flat tax = same rate for all.", "d": 1},
    {"t": "The government budget is a statement of:", "o": ["Expected revenue and expenditure", "Only expenditure", "Only revenue", "Profits"], "a": 0, "e": "A budget shows revenue and expenditure.", "d": 1},
    {"t": "A budget deficit occurs when:", "o": ["Revenue exceeds expenditure", "Expenditure exceeds revenue", "Revenue equals expenditure", "There is no tax"], "a": 1, "e": "Deficit = spending > revenue.", "d": 1},
    {"t": "A budget surplus occurs when:", "o": ["Expenditure exceeds revenue", "Revenue exceeds expenditure", "They are equal", "There is no spending"], "a": 1, "e": "Surplus = revenue > spending.", "d": 1},

    # ── International trade ──
    {"t": "The exchange of goods and services between countries is:", "o": ["Domestic trade", "International trade", "Barter", "Retail trade"], "a": 1, "e": "International trade crosses borders.", "d": 1},
    {"t": "Goods sold to other countries are:", "o": ["Imports", "Exports", "Capital", "Services"], "a": 1, "e": "Exports are goods sold abroad.", "d": 1},
    {"t": "Goods bought from other countries are:", "o": ["Exports", "Imports", "Capital", "Assets"], "a": 1, "e": "Imports are goods bought from abroad.", "d": 1},
    {"t": "The theory of comparative advantage was developed by:", "o": ["Adam Smith", "David Ricardo", "Keynes", "Marshall"], "a": 1, "e": "Ricardo developed comparative advantage.", "d": 1},
    {"t": "Comparative advantage means a country should specialise in goods it produces at:", "o": ["Higher cost", "Lower opportunity cost", "Any cost", "Zero cost"], "a": 1, "e": "Specialise where opportunity cost is lower.", "d": 1},
    {"t": "A tariff is a:", "o": ["Tax on imports", "Subsidy on exports", "Quota", "Ban on trade"], "a": 0, "e": "A tariff taxes imports.", "d": 1},
    {"t": "A quota is a:", "o": ["Tax", "Limit on the quantity of imports", "Subsidy", "Currency control"], "a": 1, "e": "A quota limits import quantity.", "d": 1},
    {"t": "An embargo is a:", "o": ["Tax", "Total ban on trade with a country", "Quota", "Tariff"], "a": 1, "e": "An embargo bans trade.", "d": 1},
    {"t": "The rate at which one currency exchanges for another is the:", "o": ["Interest rate", "Exchange rate", "Inflation rate", "Bank rate"], "a": 1, "e": "The exchange rate values currencies.", "d": 1},
    {"t": "Devaluation is the:", "o": ["Rise in currency value", "Official lowering of a currency's value", "Rise in prices", "Tax increase"], "a": 1, "e": "Devaluation lowers official currency value.", "d": 1},
    {"t": "The balance of trade is the difference between:", "o": ["Imports and exports of goods", "Tax and spending", "Income and expenditure", "Saving and investment"], "a": 0, "e": "Balance of trade = visible exports − imports.", "d": 1},
    {"t": "The balance of payments records:", "o": ["All economic transactions with other countries", "Only imports", "Only exports", "Taxes"], "a": 0, "e": "BOP records all international transactions.", "d": 1},
    {"t": "Invisible trade refers to trade in:", "o": ["Goods", "Services", "Raw materials", "Manufactured goods"], "a": 1, "e": "Invisible trade = services (banking, tourism).", "d": 1},
    {"t": "Visible trade refers to trade in:", "o": ["Services", "Tangible goods", "Invisibles", "Tourism"], "a": 1, "e": "Visible trade = tangible goods.", "d": 1},

    # ── Economic development & planning ──
    {"t": "Economic growth is measured by an increase in:", "o": ["Population", "Real national income/output", "Prices", "Imports"], "a": 1, "e": "Growth = increase in real output.", "d": 1},
    {"t": "Economic development involves growth plus:", "o": ["Only more money", "Improvement in living standards", "More imports", "Higher taxes"], "a": 1, "e": "Development improves welfare, not just output.", "d": 1},
    {"t": "A developing country is characterised by:", "o": ["High per capita income", "Low per capita income", "No agriculture", "Full industrialisation"], "a": 1, "e": "Developing countries have low per capita income.", "d": 1},
    {"t": "The main objective of economic planning is to:", "o": ["Increase taxes", "Achieve economic growth and development", "Reduce population", "Increase imports"], "a": 1, "e": "Planning aims for growth and development.", "d": 1},
    {"t": "The population census is the:", "o": ["Counting of the population", "Tax register", "Voter list", "Cattle count"], "a": 0, "e": "A census counts the population.", "d": 1},
    {"t": "Unemployment occurs when people who are able and willing to work:", "o": ["Have jobs", "Cannot find jobs", "Refuse work", "Are retired"], "a": 1, "e": "Unemployment = willing workers without jobs.", "d": 1},
    {"t": "Frictional unemployment is:", "o": ["Long-term", "Temporary, between jobs", "Seasonal", "Structural"], "a": 1, "e": "Frictional unemployment is short-term job transition.", "d": 2},
    {"t": "Structural unemployment is caused by:", "o": ["Temporary gaps", "Mismatch of skills and jobs", "Seasons", "Recessions only"], "a": 1, "e": "Structural unemployment is a skills mismatch.", "d": 2},
    {"t": "Seasonal unemployment occurs due to:", "o": ["Skill mismatch", "Seasonal changes in demand", "Recessions", "Retirement"], "a": 1, "e": "Seasonal unemployment follows seasons.", "d": 1},
    {"t": "The labour force consists of:", "o": ["Everyone", "Those able and willing to work", "Only the employed", "Only the unemployed"], "a": 1, "e": "Labour force = employed + unemployed jobseekers.", "d": 1},

    # ── More mixed ──
    {"t": "The price system operates through the forces of:", "o": ["Demand and supply", "Taxes", "Government", "Imports"], "a": 0, "e": "Prices are set by demand and supply.", "d": 1},
    {"t": "A subsidy is a:", "o": ["Tax", "Government financial support to producers", "Fine", "Loan"], "a": 1, "e": "A subsidy supports producers.", "d": 1},
    {"t": "Monopoly power can be controlled by:", "o": ["Encouraging mergers", "Anti-monopoly legislation", "Higher tariffs", "More subsidies"], "a": 1, "e": "Anti-monopoly laws curb monopoly power.", "d": 2},
    {"t": "The World Bank's main role is to:", "o": ["Regulate trade", "Provide development loans", "Set exchange rates", "Print money"], "a": 1, "e": "The World Bank funds development.", "d": 1},
    {"t": "The IMF's main role is to:", "o": ["Provide development loans", "Ensure global monetary stability", "Regulate banks", "Tax countries"], "a": 1, "e": "The IMF promotes monetary cooperation.", "d": 1},
    {"t": "OPEC is an organisation of:", "o": ["Oil-producing countries", "Importing countries", "African nations", "European nations"], "a": 0, "e": "OPEC = oil exporters' organisation.", "d": 1},
    {"t": "ECOWAS stands for:", "o": ["Economic Community of West African States", "European Community", "East African States", "Economic Union"], "a": 0, "e": "ECOWAS is the West African community.", "d": 1},
    {"t": "The stock exchange in Nigeria is located in:", "o": ["Abuja", "Lagos", "Kano", "Port Harcourt"], "a": 1, "e": "The Nigerian Stock Exchange is in Lagos.", "d": 1},
    {"t": "The currency of Nigeria is the:", "o": ["Dollar", "Naira", "Cedi", "Pound"], "a": 1, "e": "Nigeria's currency is the naira.", "d": 1},
    {"t": "The process of transferring public enterprises to private ownership is:", "o": ["Nationalisation", "Privatisation", "Indigenisation", "Commercialisation"], "a": 1, "e": "Privatisation transfers to private hands.", "d": 1},
    {"t": "The process of transferring private enterprises to public ownership is:", "o": ["Privatisation", "Nationalisation", "Liberalisation", "Deregulation"], "a": 1, "e": "Nationalisation transfers to public ownership.", "d": 1},
    {"t": "The marginal propensity to consume (MPC) is the:", "o": ["Total spending", "Fraction of extra income spent", "Total saving", "Tax rate"], "a": 1, "e": "MPC = change in consumption/change in income.", "d": 2},
    {"t": "The multiplier effect shows that an increase in investment:", "o": ["Reduces income", "Increases income by a multiple", "Has no effect", "Increases imports only"], "a": 1, "e": "The multiplier magnifies income changes.", "d": 2},
    {"t": "Savings is defined as:", "o": ["Income minus consumption", "Consumption minus income", "Total spending", "Investment"], "a": 0, "e": "Savings = income − consumption.", "d": 1},
    {"t": "The study of economics is considered a:", "o": ["Pure science", "Social science", "Natural science", "Physical science"], "a": 1, "e": "Economics is a social science.", "d": 1},
    {"t": "A market is any arrangement where:", "o": ["Buyers and sellers interact", "Only goods are sold", "Only services are sold", "Taxes are paid"], "a": 0, "e": "A market brings buyers and sellers together.", "d": 1},
    {"t": "Consumer goods used up in one use are:", "o": ["Durable goods", "Non-durable goods", "Capital goods", "Free goods"], "a": 1, "e": "Non-durables (food) are used up quickly.", "d": 1},
    {"t": "Goods that last a long time (e.g. furniture) are:", "o": ["Non-durable", "Durable goods", "Perishable", "Free goods"], "a": 1, "e": "Durable goods last a long time.", "d": 1},
    # ── More mixed ──
    {"t": "The first bank established in Nigeria was the:", "o": ["First Bank", "African Banking Corporation", "Union Bank", "Wema Bank"], "a": 1, "e": "The African Banking Corporation (1892) was first.", "d": 2},
    {"t": "The Central Bank of Nigeria was established in:", "o": ["1959", "1960", "1958", "1963"], "a": 2, "e": "The CBN was established in 1958.", "d": 2},
    {"t": "The currency used in Nigeria before the naira was the:", "o": ["Dollar", "Pound", "Cedi", "Franc"], "a": 1, "e": "Nigeria used the pound before the naira.", "d": 2},
    {"t": "The naira was introduced in Nigeria in:", "o": ["1973", "1971", "1960", "1963"], "a": 0, "e": "The naira replaced the pound in 1973.", "d": 2},
    {"t": "The coins and notes in circulation form the:", "o": ["Money supply", "Currency", "Deposits", "Reserves"], "a": 1, "e": "Currency = coins and notes in circulation.", "d": 1},
    {"t": "The total stock of money in an economy is the:", "o": ["Currency", "Money supply", "Reserves", "Deposits only"], "a": 1, "e": "Money supply = currency + deposits.", "d": 1},
    {"t": "An inflation that arises from excess demand is:", "o": ["Cost-push", "Demand-pull", "Structural", "Imported"], "a": 1, "e": "Demand-pull inflation is from excess demand.", "d": 1},
    {"t": "The situation of both inflation and unemployment rising together is:", "o": ["Deflation", "Stagflation", "Reflation", "Disinflation"], "a": 1, "e": "Stagflation = stagnation + inflation.", "d": 2},
    {"t": "Reflation is the policy of:", "o": ["Reducing prices", "Reviving the economy after deflation", "Increasing unemployment", "Cutting spending"], "a": 1, "e": "Reflation stimulates the economy.", "d": 2},
    {"t": "The deliberate reduction of the inflation rate is:", "o": ["Reflation", "Disinflation", "Deflation", "Stagflation"], "a": 1, "e": "Disinflation = slowing inflation.", "d": 2},
    {"t": "The price of one currency in terms of another is the:", "o": ["Interest rate", "Exchange rate", "Bank rate", "Inflation rate"], "a": 1, "e": "The exchange rate prices currencies.", "d": 1},
    {"t": "A rise in the value of a currency under a floating system is:", "o": ["Devaluation", "Appreciation", "Depreciation", "Revaluation"], "a": 1, "e": "Appreciation = rise in currency value.", "d": 1},
    {"t": "A fall in the value of a floating currency is:", "o": ["Appreciation", "Depreciation", "Revaluation", "Devaluation"], "a": 1, "e": "Depreciation = fall in floating currency value.", "d": 1},
    {"t": "The official raising of a currency's value is:", "o": ["Depreciation", "Revaluation", "Devaluation", "Appreciation"], "a": 1, "e": "Revaluation = official value increase.", "d": 2},
    {"t": "The market where foreign currencies are traded is the:", "o": ["Stock market", "Foreign exchange market", "Commodity market", "Money market"], "a": 1, "e": "Forex market trades currencies.", "d": 1},
    {"t": "The central bank's control of money supply to influence the economy is:", "o": ["Fiscal policy", "Monetary policy", "Trade policy", "Income policy"], "a": 1, "e": "Monetary policy controls money supply.", "d": 1},
    {"t": "The government's use of taxation and spending is:", "o": ["Monetary policy", "Fiscal policy", "Trade policy", "Exchange policy"], "a": 1, "e": "Fiscal policy uses taxes and spending.", "d": 1},
    {"t": "The instruments of monetary policy include:", "o": ["Taxes", "Open market operations and bank rate", "Subsidies", "Tariffs"], "a": 1, "e": "Monetary tools include OMO and bank rate.", "d": 1},
    {"t": "The central bank sells securities to reduce money supply through:", "o": ["Fiscal policy", "Open market operations", "Tariffs", "Subsidies"], "a": 1, "e": "OMO sells securities to contract money supply.", "d": 2},
    {"t": "The minimum cash banks must hold is the:", "o": ["Interest rate", "Cash reserve ratio", "Exchange rate", "Tax rate"], "a": 1, "e": "The cash reserve ratio sets minimum reserves.", "d": 2},
    {"t": "The total value of a country's exports minus imports of goods is the:", "o": ["Balance of payments", "Balance of trade", "National income", "Budget"], "a": 1, "e": "Balance of trade = visible exports − imports.", "d": 1},
    {"t": "A favourable balance of trade means:", "o": ["Imports exceed exports", "Exports exceed imports", "They are equal", "No trade"], "a": 1, "e": "Favourable = exports > imports.", "d": 1},
    {"t": "An unfavourable balance of trade means:", "o": ["Exports exceed imports", "Imports exceed exports", "They are equal", "No trade"], "a": 1, "e": "Unfavourable = imports > exports.", "d": 1},
    {"t": "The organisation that regulates international trade is the:", "o": ["IMF", "WTO", "World Bank", "OPEC"], "a": 1, "e": "The WTO regulates global trade.", "d": 1},
    {"t": "The headquarters of OPEC is in:", "o": ["Riyadh", "Vienna", "Abuja", "Cairo"], "a": 1, "e": "OPEC's headquarters is in Vienna.", "d": 2},
    {"t": "The headquarters of ECOWAS is in:", "o": ["Lagos", "Abuja", "Accra", "Dakar"], "a": 1, "e": "ECOWAS is headquartered in Abuja.", "d": 2},
    {"t": "The major source of government revenue in Nigeria is:", "o": ["Taxes", "Oil revenue", "Aid", "Tourism"], "a": 1, "e": "Oil revenue dominates Nigerian finances.", "d": 1},
    {"t": "The budget where revenue equals expenditure is a:", "o": ["Deficit budget", "Balanced budget", "Surplus budget", "Capital budget"], "a": 1, "e": "A balanced budget has revenue = spending.", "d": 1},
    {"t": "The budget that covers day-to-day government spending is the:", "o": ["Capital budget", "Recurrent budget", "Supplementary budget", "Deficit budget"], "a": 1, "e": "The recurrent budget covers routine spending.", "d": 1},
    {"t": "The budget for long-term projects (roads, buildings) is the:", "o": ["Recurrent budget", "Capital budget", "Supplementary budget", "Annual budget"], "a": 1, "e": "The capital budget funds projects.", "d": 1},
    {"t": "The total debt owed by the government is the:", "o": ["Budget deficit", "National (public) debt", "Trade deficit", "Current debt"], "a": 1, "e": "National debt is total government borrowing.", "d": 1},
    {"t": "The agency that collects taxes in Nigeria is the:", "o": ["CBN", "FIRS (Federal Inland Revenue Service)", "NNPC", "SEC"], "a": 1, "e": "FIRS collects federal taxes.", "d": 2},
    {"t": "Value Added Tax (VAT) in Nigeria is administered by:", "o": ["CBN", "FIRS", "NDIC", "SEC"], "a": 1, "e": "FIRS administers VAT.", "d": 2},
    {"t": "The agency that insures bank deposits in Nigeria is the:", "o": ["CBN", "NDIC", "SEC", "FIRS"], "a": 1, "e": "NDIC insures deposits.", "d": 2},
    {"t": "The agency that regulates the capital market in Nigeria is the:", "o": ["CBN", "SEC (Securities and Exchange Commission)", "NDIC", "FIRS"], "a": 1, "e": "SEC regulates the capital market.", "d": 2},
    {"t": "The oldest economic system is the:", "o": ["Capitalism", "Traditional economy", "Socialism", "Mixed economy"], "a": 1, "e": "Traditional economies are the oldest.", "d": 1},
    {"t": "The economic term for human wants is that they are:", "o": ["Limited", "Unlimited", "Fixed", "Few"], "a": 1, "e": "Human wants are unlimited.", "d": 1},
    {"t": "The resources used in production are also called:", "o": ["Outputs", "Factors of production", "Products", "Goods"], "a": 1, "e": "Resources = factors of production.", "d": 1},
    {"t": "The reward for the entrepreneur is:", "o": ["Rent", "Profit", "Wages", "Interest"], "a": 1, "e": "The entrepreneur earns profit.", "d": 1},
    {"t": "The situation where one seller serves the entire market most efficiently is a:", "o": ["Oligopoly", "Natural monopoly", "Duopoly", "Monopsony"], "a": 1, "e": "A natural monopoly serves the market most efficiently.", "d": 2},
]

build("eco", "Economics", QUESTIONS[:200])
