from _common import build

QUESTIONS = [
    # ── Measurement & units ──
    {"t": "The SI unit of length is the:", "o": ["Metre", "Kilometre", "Centimetre", "Foot"], "a": 0, "e": "The SI base unit of length is the metre (m).", "d": 1},
    {"t": "The SI unit of mass is the:", "o": ["Gram", "Kilogram", "Newton", "Pound"], "a": 1, "e": "The SI base unit of mass is the kilogram (kg).", "d": 1},
    {"t": "The SI unit of time is the:", "o": ["Minute", "Hour", "Second", "Day"], "a": 2, "e": "The SI base unit of time is the second (s).", "d": 1},
    {"t": "The SI unit of force is the:", "o": ["Joule", "Watt", "Newton", "Pascal"], "a": 2, "e": "Force is measured in newtons (N).", "d": 1},
    {"t": "The SI unit of energy is the:", "o": ["Watt", "Joule", "Newton", "Volt"], "a": 1, "e": "Energy is measured in joules (J).", "d": 1},
    {"t": "The SI unit of power is the:", "o": ["Joule", "Newton", "Watt", "Volt"], "a": 2, "e": "Power is measured in watts (W).", "d": 1},
    {"t": "The SI unit of electric current is the:", "o": ["Volt", "Ohm", "Ampere", "Coulomb"], "a": 2, "e": "Current is measured in amperes (A).", "d": 1},
    {"t": "The SI unit of electric charge is the:", "o": ["Ampere", "Volt", "Coulomb", "Ohm"], "a": 2, "e": "Charge is measured in coulombs (C).", "d": 1},
    {"t": "The SI unit of pressure is the:", "o": ["Newton", "Pascal", "Torr", "Bar"], "a": 1, "e": "Pressure is measured in pascals (Pa).", "d": 1},
    {"t": "Which instrument is used to measure length with high precision?", "o": ["Metre rule", "Vernier calipers", "Stopwatch", "Balance"], "a": 1, "e": "Vernier calipers measure small lengths accurately.", "d": 1},
    {"t": "The SI unit of temperature is the:", "o": ["Celsius", "Kelvin", "Fahrenheit", "Rankine"], "a": 1, "e": "The SI unit of temperature is the kelvin (K).", "d": 1},
    {"t": "Which of these is a derived unit?", "o": ["Metre", "Kilogram", "Second", "Newton"], "a": 3, "e": "Newton (kg·m/s²) is derived; the others are base units.", "d": 1},

    # ── Scalars & vectors ──
    {"t": "Which of the following is a vector quantity?", "o": ["Speed", "Distance", "Displacement", "Mass"], "a": 2, "e": "Displacement has both magnitude and direction.", "d": 1},
    {"t": "Which of the following is a scalar quantity?", "o": ["Velocity", "Force", "Acceleration", "Speed"], "a": 3, "e": "Speed has magnitude only.", "d": 1},
    {"t": "Displacement is best described as:", "o": ["Total path travelled", "Distance in a specified direction", "Speed over time", "Change in speed"], "a": 1, "e": "Displacement is a directed straight-line distance.", "d": 1},
    {"t": "A body moves 3 m east then 4 m north. The magnitude of its displacement is:", "o": ["7 m", "1 m", "5 m", "12 m"], "a": 2, "e": "√(3² + 4²) = 5 m.", "d": 2},
    {"t": "Which quantity is the vector counterpart of speed?", "o": ["Acceleration", "Velocity", "Momentum", "Force"], "a": 1, "e": "Velocity is speed with direction.", "d": 1},
    {"t": "Two forces of 3 N and 4 N act at right angles. The resultant is:", "o": ["7 N", "1 N", "5 N", "12 N"], "a": 2, "e": "R = √(3² + 4²) = 5 N.", "d": 2},

    # ── Motion ──
    {"t": "The slope of a distance–time graph gives:", "o": ["Acceleration", "Speed", "Force", "Displacement"], "a": 1, "e": "Gradient of distance–time = speed.", "d": 1},
    {"t": "The slope of a velocity–time graph gives:", "o": ["Speed", "Distance", "Acceleration", "Force"], "a": 2, "e": "Gradient of velocity–time = acceleration.", "d": 1},
    {"t": "The area under a velocity–time graph gives:", "o": ["Acceleration", "Displacement", "Force", "Speed"], "a": 1, "e": "Area under velocity–time graph = displacement.", "d": 2},
    {"t": "A car accelerates from rest at 2 m/s² for 5 s. Its final velocity is:", "o": ["10 m/s", "5 m/s", "7 m/s", "2.5 m/s"], "a": 0, "e": "v = u + at = 0 + 2×5 = 10 m/s.", "d": 2},
    {"t": "A body moves with uniform velocity. Its acceleration is:", "o": ["Zero", "Constant", "Increasing", "Decreasing"], "a": 0, "e": "Uniform velocity means zero acceleration.", "d": 1},
    {"t": "The acceleration due to gravity, g, is approximately:", "o": ["9.8 m/s²", "98 m/s²", "0.98 m/s²", "980 m/s²"], "a": 0, "e": "g ≈ 9.8 m/s².", "d": 1},
    {"t": "A body is thrown vertically upward. At the highest point, its velocity is:", "o": ["Maximum", "Zero", "Equal to g", "Negative"], "a": 1, "e": "At the peak, velocity is momentarily zero.", "d": 2},
    {"t": "A stone falls freely from rest. After 2 s its speed is (g = 10 m/s²):", "o": ["20 m/s", "10 m/s", "5 m/s", "40 m/s"], "a": 0, "e": "v = gt = 10 × 2 = 20 m/s.", "d": 2},
    {"t": "The distance fallen by a freely falling body in 1 s (g = 10 m/s²) is:", "o": ["5 m", "10 m", "20 m", "2.5 m"], "a": 0, "e": "s = ½gt² = ½ × 10 × 1 = 5 m.", "d": 2},
    {"t": "Uniform motion in a circle is described as having constant:", "o": ["Velocity", "Speed", "Acceleration", "Displacement"], "a": 1, "e": "Speed is constant but direction (hence velocity) changes.", "d": 2},
    {"t": "A car travels 100 m in 4 s. Its average speed is:", "o": ["25 m/s", "400 m/s", "40 m/s", "4 m/s"], "a": 0, "e": "Speed = 100/4 = 25 m/s.", "d": 1},

    # ── Newton's laws & forces ──
    {"t": "Newton's first law is also called the law of:", "o": ["Acceleration", "Inertia", "Action-reaction", "Gravitation"], "a": 1, "e": "First law = law of inertia.", "d": 1},
    {"t": "Newton's second law is expressed as:", "o": ["F = ma", "F = mv", "F = m/a", "F = mg"], "a": 0, "e": "Force = mass × acceleration.", "d": 1},
    {"t": "Newton's third law states that action and reaction are:", "o": ["Unequal and same direction", "Equal and opposite", "Equal and same direction", "Unequal and opposite"], "a": 1, "e": "Action and reaction are equal and opposite.", "d": 1},
    {"t": "The tendency of a body to resist change in its state of motion is:", "o": ["Momentum", "Inertia", "Friction", "Weight"], "a": 1, "e": "Inertia resists changes in motion.", "d": 1},
    {"t": "A force of 10 N acts on a 2 kg body. Its acceleration is:", "o": ["5 m/s²", "20 m/s²", "0.2 m/s²", "10 m/s²"], "a": 0, "e": "a = F/m = 10/2 = 5 m/s².", "d": 2},
    {"t": "The weight of a body is equal to:", "o": ["mg", "ma", "m/g", "mv"], "a": 0, "e": "Weight = mass × g.", "d": 1},
    {"t": "Friction that opposes the start of motion is called:", "o": ["Kinetic friction", "Static friction", "Rolling friction", "Sliding friction"], "a": 1, "e": "Static friction resists the initiation of motion.", "d": 1},
    {"t": "Friction between two surfaces can be reduced by:", "o": ["Roughening them", "Lubrication", "Increasing load", "Drying them"], "a": 1, "e": "Lubrication reduces friction.", "d": 1},
    {"t": "The SI unit of momentum is:", "o": ["kg m/s", "kg m/s²", "N s²", "J s"], "a": 0, "e": "Momentum = mass × velocity → kg m/s.", "d": 1},
    {"t": "A body of mass 5 kg moving at 4 m/s has momentum:", "o": ["20 kg m/s", "1.25 kg m/s", "9 kg m/s", "20 N"], "a": 0, "e": "p = mv = 20 kg m/s.", "d": 2},
    {"t": "In the absence of external forces, total momentum is:", "o": ["Conserved", "Increased", "Decreased", "Zero"], "a": 0, "e": "Law of conservation of momentum.", "d": 1},

    # ── Work, energy & power ──
    {"t": "Work done is calculated as:", "o": ["Force × distance", "Force ÷ distance", "Force × time", "Mass × velocity"], "a": 0, "e": "Work = force × distance (in direction of force).", "d": 1},
    {"t": "A force of 10 N moves a body 5 m. The work done is:", "o": ["50 J", "2 J", "15 J", "5 J"], "a": 0, "e": "W = F × d = 50 J.", "d": 1},
    {"t": "Kinetic energy is given by:", "o": ["½mv²", "mgh", "mv", "½mv"], "a": 0, "e": "KE = ½mv².", "d": 1},
    {"t": "Potential energy of a body at height h is:", "o": ["mgh", "½mgh", "mg/h", "½mv²"], "a": 0, "e": "PE = mgh.", "d": 1},
    {"t": "A 2 kg mass is lifted 3 m (g = 10 m/s²). The work done is:", "o": ["60 J", "6 J", "20 J", "5 J"], "a": 0, "e": "W = mgh = 2 × 10 × 3 = 60 J.", "d": 2},
    {"t": "Power is defined as:", "o": ["Work done per unit time", "Force × time", "Energy × time", "Work × time"], "a": 0, "e": "Power = work/time.", "d": 1},
    {"t": "A machine does 100 J of work in 5 s. Its power is:", "o": ["20 W", "500 W", "50 W", "5 W"], "a": 0, "e": "P = 100/5 = 20 W.", "d": 2},
    {"t": "The principle of conservation of energy states that energy:", "o": ["Can be created", "Cannot be created or destroyed", "Can be destroyed", "Only exists as heat"], "a": 1, "e": "Energy is conserved — only transformed.", "d": 1},
    {"t": "The unit of work is the same as the unit of:", "o": ["Power", "Energy", "Force", "Pressure"], "a": 1, "e": "Both work and energy are measured in joules.", "d": 1},
    {"t": "The efficiency of a machine is the ratio of:", "o": ["Input to output", "Useful output to input", "Loss to input", "Power to work"], "a": 1, "e": "Efficiency = useful output/input.", "d": 1},

    # ── Pressure & fluids ──
    {"t": "Pressure is defined as:", "o": ["Force per unit area", "Force × area", "Area per unit force", "Mass per unit area"], "a": 0, "e": "Pressure = force/area.", "d": 1},
    {"t": "A force of 20 N acts on an area of 4 m². The pressure is:", "o": ["5 Pa", "80 Pa", "0.2 Pa", "16 Pa"], "a": 0, "e": "P = F/A = 20/4 = 5 Pa.", "d": 2},
    {"t": "Pressure in a liquid increases with:", "o": ["Depth", "Surface area", "Temperature only", "Volume"], "a": 0, "e": "Liquid pressure increases with depth.", "d": 1},
    {"t": "The pressure at a point in a liquid is given by:", "o": ["ρgh", "ρg/h", "ρh/g", "mgh"], "a": 0, "e": "P = ρgh.", "d": 2},
    {"t": "Atmospheric pressure at sea level is approximately:", "o": ["76 cm of mercury", "10 cm of mercury", "100 cm of mercury", "1 cm of mercury"], "a": 0, "e": "Standard atmospheric pressure ≈ 760 mmHg = 76 cmHg.", "d": 1},
    {"t": "The barometer is used to measure:", "o": ["Temperature", "Atmospheric pressure", "Humidity", "Wind speed"], "a": 1, "e": "A barometer measures atmospheric pressure.", "d": 1},

    # ── Heat & temperature ──
    {"t": "Temperature is a measure of the average:", "o": ["Kinetic energy of particles", "Potential energy", "Total energy", "Volume"], "a": 0, "e": "Temperature measures average kinetic energy of particles.", "d": 1},
    {"t": "Heat flows from a body at:", "o": ["Lower to higher temperature", "Higher to lower temperature", "Equal temperature", "Any direction"], "a": 1, "e": "Heat flows from hot to cold.", "d": 1},
    {"t": "The instrument used to measure temperature is the:", "o": ["Barometer", "Thermometer", "Hygrometer", "Manometer"], "a": 1, "e": "A thermometer measures temperature.", "d": 1},
    {"t": "0°C in kelvin is:", "o": ["273 K", "−273 K", "373 K", "100 K"], "a": 0, "e": "0°C = 273 K.", "d": 1},
    {"t": "Absolute zero is:", "o": ["0 K", "0°C", "273 K", "100°C"], "a": 0, "e": "Absolute zero = 0 K = −273°C.", "d": 1},
    {"t": "The specific heat capacity of a substance is the heat needed to:", "o": ["Raise 1 kg by 1°C", "Melt 1 kg", "Boil 1 kg", "Raise any mass by 1°C"], "a": 0, "e": "Specific heat capacity = energy to raise 1 kg by 1 K.", "d": 1},
    {"t": "The quantity of heat Q is given by:", "o": ["Q = mcΔθ", "Q = m/Δθ", "Q = cΔθ/m", "Q = mc/Δθ"], "a": 0, "e": "Q = mcΔθ.", "d": 1},
    {"t": "The heat required to change a solid to a liquid at constant temperature is the:", "o": ["Latent heat of fusion", "Specific heat", "Latent heat of vaporisation", "Sensible heat"], "a": 0, "e": "Latent heat of fusion changes solid → liquid.", "d": 1},
    {"t": "The latent heat of vaporisation changes:", "o": ["Liquid to vapour", "Solid to liquid", "Vapour to solid", "Solid to vapour"], "a": 0, "e": "Vaporisation = liquid → gas.", "d": 1},
    {"t": "Heat transfer by direct contact of particles is called:", "o": ["Conduction", "Convection", "Radiation", "Evaporation"], "a": 0, "e": "Conduction transfers heat through direct particle contact.", "d": 1},
    {"t": "Heat transfer in fluids by movement of the fluid itself is:", "o": ["Conduction", "Convection", "Radiation", "Diffusion"], "a": 1, "e": "Convection involves bulk movement of fluid.", "d": 1},
    {"t": "Heat transfer through a vacuum occurs by:", "o": ["Conduction", "Convection", "Radiation", "All of these"], "a": 2, "e": "Radiation needs no medium.", "d": 1},

    # ── Gas laws ──
    {"t": "Boyle's law states that at constant temperature, pressure is:", "o": ["Inversely proportional to volume", "Directly proportional to volume", "Independent of volume", "Equal to volume"], "a": 0, "e": "P ∝ 1/V at constant T.", "d": 1},
    {"t": "Charles's law relates volume to:", "o": ["Pressure", "Temperature (at constant pressure)", "Mass", "Density"], "a": 1, "e": "V ∝ T at constant pressure.", "d": 1},
    {"t": "The pressure law (Gay-Lussac) states pressure ∝:", "o": ["Volume", "Temperature (at constant volume)", "Mass", "Density"], "a": 1, "e": "P ∝ T at constant volume.", "d": 1},
    {"t": "The general gas law is expressed as:", "o": ["PV/T = constant", "PV = T", "P = VT", "PT = V"], "a": 0, "e": "PV/T = constant combines the three laws.", "d": 2},
    {"t": "The ideal gas equation is:", "o": ["PV = nRT", "PV = RT/n", "PT = nRV", "P = nRT/V²"], "a": 0, "e": "PV = nRT.", "d": 2},

    # ── Waves ──
    {"t": "The distance between two successive crests of a wave is the:", "o": ["Amplitude", "Wavelength", "Frequency", "Period"], "a": 1, "e": "Wavelength is crest-to-crest distance.", "d": 1},
    {"t": "The number of complete waves passing a point per second is the:", "o": ["Period", "Wavelength", "Frequency", "Amplitude"], "a": 2, "e": "Frequency = cycles per second (Hz).", "d": 1},
    {"t": "The unit of frequency is the:", "o": ["Hertz", "Metre", "Second", "Decibel"], "a": 0, "e": "Frequency is measured in hertz (Hz).", "d": 1},
    {"t": "The relationship between wave speed v, frequency f and wavelength λ is:", "o": ["v = fλ", "v = f/λ", "v = λ/f", "v = f + λ"], "a": 0, "e": "v = fλ.", "d": 1},
    {"t": "The maximum displacement of a wave from its rest position is the:", "o": ["Wavelength", "Amplitude", "Period", "Frequency"], "a": 1, "e": "Amplitude is maximum displacement.", "d": 1},
    {"t": "The time for one complete oscillation is the:", "o": ["Frequency", "Amplitude", "Period", "Wavelength"], "a": 2, "e": "Period = time for one cycle.", "d": 1},
    {"t": "A wave of frequency 5 Hz has a period of:", "o": ["0.2 s", "5 s", "0.5 s", "2 s"], "a": 0, "e": "T = 1/f = 0.2 s.", "d": 2},
    {"t": "Which of the following is a longitudinal wave?", "o": ["Light", "Sound", "Radio wave", "Water ripple"], "a": 1, "e": "Sound is a longitudinal wave.", "d": 1},
    {"t": "Which of the following is a transverse wave?", "o": ["Sound", "Light", "P-wave", "All of these"], "a": 1, "e": "Light is a transverse (electromagnetic) wave.", "d": 1},

    # ── Sound ──
    {"t": "The speed of sound in air is approximately:", "o": ["330 m/s", "3 × 10⁸ m/s", "33 m/s", "3300 m/s"], "a": 0, "e": "Sound travels at ≈ 330 m/s in air.", "d": 1},
    {"t": "Sound cannot travel through a:", "o": ["Solid", "Liquid", "Vacuum", "Gas"], "a": 2, "e": "Sound needs a medium; a vacuum has none.", "d": 1},
    {"t": "The pitch of a sound is determined by its:", "o": ["Amplitude", "Frequency", "Speed", "Medium"], "a": 1, "e": "Pitch depends on frequency.", "d": 1},
    {"t": "The loudness of a sound depends on its:", "o": ["Frequency", "Amplitude", "Speed", "Wavelength"], "a": 1, "e": "Loudness depends on amplitude.", "d": 1},
    {"t": "The speed of sound is greatest in:", "o": ["Air", "Water", "Steel", "Vacuum"], "a": 2, "e": "Sound travels fastest in solids.", "d": 1},
    {"t": "The reflection of sound is called:", "o": ["Refraction", "Echo", "Diffraction", "Interference"], "a": 1, "e": "An echo is reflected sound.", "d": 1},
    {"t": "Sound waves with frequency above 20,000 Hz are called:", "o": ["Infrasonic", "Ultrasonic", "Audible", "Supersonic"], "a": 1, "e": "Ultrasound > 20 kHz.", "d": 1},
    {"t": "Sound waves with frequency below 20 Hz are:", "o": ["Ultrasonic", "Infrasonic", "Audible", "Subsonic"], "a": 1, "e": "Infrasound < 20 Hz.", "d": 1},

    # ── Light: reflection & refraction ──
    {"t": "The angle of incidence is measured from the:", "o": ["Surface", "Normal", "Reflected ray", "Horizontal"], "a": 1, "e": "Angles are measured from the normal.", "d": 1},
    {"t": "According to the laws of reflection, the angle of incidence is:", "o": ["Greater than the angle of reflection", "Equal to the angle of reflection", "Less than the angle of reflection", "Twice the angle of reflection"], "a": 1, "e": "Angle of incidence = angle of reflection.", "d": 1},
    {"t": "The speed of light in a vacuum is approximately:", "o": ["3 × 10⁸ m/s", "3 × 10⁶ m/s", "330 m/s", "3 × 10¹⁰ m/s"], "a": 0, "e": "c ≈ 3 × 10⁸ m/s.", "d": 1},
    {"t": "The bending of light as it passes from one medium to another is:", "o": ["Reflection", "Refraction", "Diffraction", "Dispersion"], "a": 1, "e": "Refraction is bending of light at a boundary.", "d": 1},
    {"t": "The refractive index n is the ratio of:", "o": ["sin i / sin r", "sin r / sin i", "cos i / cos r", "i / r"], "a": 0, "e": "Snell's law: n = sin i / sin r.", "d": 2},
    {"t": "A concave lens is also called a:", "o": ["Converging lens", "Diverging lens", "Plane lens", "Biconvex lens"], "a": 1, "e": "A concave lens diverges light.", "d": 1},
    {"t": "A convex lens is also called a:", "o": ["Diverging lens", "Converging lens", "Concave lens", "Plano lens"], "a": 1, "e": "A convex lens converges light.", "d": 1},
    {"t": "The splitting of white light into its colours is called:", "o": ["Refraction", "Dispersion", "Diffraction", "Polarisation"], "a": 1, "e": "Dispersion splits white light into a spectrum.", "d": 1},
    {"t": "The image formed by a plane mirror is:", "o": ["Real and inverted", "Virtual and upright", "Real and upright", "Virtual and inverted"], "a": 1, "e": "Plane mirror: virtual, upright, laterally inverted.", "d": 1},
    {"t": "A converging lens forms a real, inverted image when the object is:", "o": ["Between focus and lens", "Beyond the focal length", "At the lens", "Only at infinity"], "a": 1, "e": "Object beyond F gives a real inverted image.", "d": 2},
    {"t": "The power of a lens is measured in:", "o": ["Watts", "Dioptres", "Metres", "Lumens"], "a": 1, "e": "Lens power is in dioptres (D).", "d": 1},
    {"t": "A lens of focal length 50 cm has a power of:", "o": ["2 D", "0.5 D", "5 D", "20 D"], "a": 0, "e": "P = 1/f = 1/0.5 = 2 D.", "d": 2},

    # ── Electrostatics & capacitors ──
    {"t": "Like charges:", "o": ["Attract", "Repel", "Have no effect", "Neutralise"], "a": 1, "e": "Like charges repel; unlike attract.", "d": 1},
    {"t": "The unit of electric charge is the:", "o": ["Ampere", "Coulomb", "Volt", "Farad"], "a": 1, "e": "Charge is in coulombs.", "d": 1},
    {"t": "The unit of capacitance is the:", "o": ["Ohm", "Farad", "Henry", "Coulomb"], "a": 1, "e": "Capacitance is in farads (F).", "d": 1},
    {"t": "A capacitor stores:", "o": ["Current", "Charge and energy", "Resistance", "Power"], "a": 1, "e": "A capacitor stores charge/energy in an electric field.", "d": 1},
    {"t": "The unit of potential difference is the:", "o": ["Ampere", "Volt", "Ohm", "Watt"], "a": 1, "e": "Potential difference is in volts.", "d": 1},

    # ── Current electricity ──
    {"t": "Ohm's law states that V equals:", "o": ["IR", "I/R", "R/I", "I + R"], "a": 0, "e": "V = IR.", "d": 1},
    {"t": "The unit of resistance is the:", "o": ["Volt", "Ohm", "Ampere", "Watt"], "a": 1, "e": "Resistance is in ohms (Ω).", "d": 1},
    {"t": "A current of 2 A flows through a 5 Ω resistor. The voltage across it is:", "o": ["10 V", "2.5 V", "0.4 V", "7 V"], "a": 0, "e": "V = IR = 2 × 5 = 10 V.", "d": 2},
    {"t": "For resistors in series, the total resistance is:", "o": ["The sum of the resistances", "The reciprocal sum", "The average", "The difference"], "a": 0, "e": "Series: R = R₁ + R₂ + ...", "d": 1},
    {"t": "For resistors in parallel, the total resistance is:", "o": ["The sum", "Less than the smallest resistor", "Greater than the largest", "The average"], "a": 1, "e": "Parallel total resistance is less than the smallest.", "d": 2},
    {"t": "Two 4 Ω resistors in parallel have a combined resistance of:", "o": ["2 Ω", "8 Ω", "4 Ω", "1 Ω"], "a": 0, "e": "1/R = 1/4 + 1/4 = 1/2 → R = 2 Ω.", "d": 2},
    {"t": "Two 4 Ω resistors in series have a combined resistance of:", "o": ["8 Ω", "2 Ω", "4 Ω", "16 Ω"], "a": 0, "e": "4 + 4 = 8 Ω.", "d": 1},
    {"t": "Electrical power is calculated as:", "o": ["P = IV", "P = I/V", "P = V/I", "P = IR²"], "a": 0, "e": "Power P = IV.", "d": 1},
    {"t": "The instrument used to measure electric current is the:", "o": ["Voltmeter", "Ammeter", "Galvanometer", "Ohmmeter"], "a": 1, "e": "An ammeter measures current.", "d": 1},
    {"t": "A voltmeter is connected in:", "o": ["Series", "Parallel", "Either", "Neither"], "a": 1, "e": "Voltmeters are connected in parallel.", "d": 1},
    {"t": "An ammeter is connected in:", "o": ["Parallel", "Series", "Either", "Neither"], "a": 1, "e": "Ammeters are connected in series.", "d": 1},
    {"t": "The resistance of a wire increases when it is:", "o": ["Thicker", "Longer", "Cooler", "Shorter"], "a": 1, "e": "Longer wires have greater resistance.", "d": 1},

    # ── Magnetism & electromagnetic induction ──
    {"t": "Like magnetic poles:", "o": ["Attract", "Repel", "Neutralise", "Merge"], "a": 1, "e": "Like poles repel.", "d": 1},
    {"t": "The direction of a magnetic field is from:", "o": ["South to north", "North to south", "East to west", "Any direction"], "a": 1, "e": "Field lines run N → S outside a magnet.", "d": 1},
    {"t": "The unit of magnetic flux is the:", "o": ["Tesla", "Weber", "Henry", "Gauss"], "a": 1, "e": "Magnetic flux is in webers (Wb).", "d": 2},
    {"t": "The SI unit of magnetic flux density is the:", "o": ["Weber", "Tesla", "Henry", "Farad"], "a": 1, "e": "Flux density is in teslas (T).", "d": 2},
    {"t": "A current-carrying conductor in a magnetic field experiences:", "o": ["No force", "A force", "Only heat", "Only light"], "a": 1, "e": "Motor effect: a force acts on the conductor.", "d": 1},
    {"t": "The generation of an emf by a changing magnetic flux is:", "o": ["Electrolysis", "Electromagnetic induction", "Conduction", "Radiation"], "a": 1, "e": "EM induction produces an emf from changing flux.", "d": 1},
    {"t": "Faraday's law relates induced emf to the rate of change of:", "o": ["Current", "Magnetic flux", "Resistance", "Charge"], "a": 1, "e": "Induced emf ∝ rate of change of flux.", "d": 1},
    {"t": "A transformer works on the principle of:", "o": ["Electrolysis", "Electromagnetic induction", "Static electricity", "Conduction"], "a": 1, "e": "Transformers rely on mutual induction.", "d": 1},
    {"t": "A step-up transformer increases:", "o": ["Current", "Voltage", "Resistance", "Power"], "a": 1, "e": "Step-up increases voltage.", "d": 1},
    {"t": "The electric motor converts electrical energy to:", "o": ["Heat", "Mechanical energy", "Light", "Chemical energy"], "a": 1, "e": "Motors convert electrical → mechanical energy.", "d": 1},
    {"t": "A generator converts mechanical energy to:", "o": ["Electrical energy", "Heat", "Light", "Sound"], "a": 0, "e": "Generators convert mechanical → electrical energy.", "d": 1},

    # ── Modern physics ──
    {"t": "The smallest particle of an element is the:", "o": ["Molecule", "Atom", "Ion", "Electron"], "a": 1, "e": "An atom is the smallest unit of an element.", "d": 1},
    {"t": "The positively charged particle in an atom's nucleus is the:", "o": ["Electron", "Proton", "Neutron", "Positron"], "a": 1, "e": "Protons are positively charged.", "d": 1},
    {"t": "The particle in the nucleus with no charge is the:", "o": ["Proton", "Neutron", "Electron", "Ion"], "a": 1, "e": "Neutrons are neutral.", "d": 1},
    {"t": "The electron was discovered by:", "o": ["Rutherford", "J. J. Thomson", "Bohr", "Einstein"], "a": 1, "e": "J. J. Thomson discovered the electron.", "d": 1},
    {"t": "The nucleus of an atom was discovered by:", "o": ["Thomson", "Rutherford", "Dalton", "Planck"], "a": 1, "e": "Rutherford's gold-foil experiment revealed the nucleus.", "d": 1},
    {"t": "The number of protons in an atom is its:", "o": ["Mass number", "Atomic number", "Valency", "Charge"], "a": 1, "e": "Atomic number = number of protons.", "d": 1},
    {"t": "The mass number of an atom is the total of:", "o": ["Protons and electrons", "Protons and neutrons", "Neutrons and electrons", "Protons only"], "a": 1, "e": "Mass number = protons + neutrons.", "d": 1},
    {"t": "Isotopes of an element have the same number of protons but different:", "o": ["Electrons", "Neutrons", "Charge", "Atomic number"], "a": 1, "e": "Isotopes differ in neutron number.", "d": 1},
    {"t": "Radioactivity was discovered by:", "o": ["Becquerel", "Curie", "Rutherford", "Roentgen"], "a": 0, "e": "Henri Becquerel discovered radioactivity.", "d": 1},
    {"t": "Which radiation is the most penetrating?", "o": ["Alpha", "Beta", "Gamma", "All equal"], "a": 2, "e": "Gamma rays are the most penetrating.", "d": 1},
    {"t": "Alpha particles are essentially:", "o": ["Helium nuclei", "Electrons", "Photons", "Protons"], "a": 0, "e": "Alpha particles are helium nuclei (2p + 2n).", "d": 1},
    {"t": "Beta particles are:", "o": ["Helium nuclei", "Fast electrons", "Photons", "Protons"], "a": 1, "e": "Beta particles are fast-moving electrons.", "d": 1},
    {"t": "Gamma rays are:", "o": ["Charged particles", "Electromagnetic waves", "Helium nuclei", "Protons"], "a": 1, "e": "Gamma rays are high-energy EM waves.", "d": 1},
    {"t": "The photoelectric effect demonstrates the ___ nature of light.", "o": ["Wave", "Particle", "Magnetic", "Thermal"], "a": 1, "e": "The photoelectric effect shows light's particle (photon) nature.", "d": 2},
    {"t": "The energy of a photon is given by:", "o": ["E = hf", "E = h/f", "E = mc", "E = hc²"], "a": 0, "e": "Photon energy E = hf.", "d": 2},

    # ── More mixed ──
    {"t": "The S.I. unit of frequency is named after:", "o": ["Hertz", "Newton", "Joule", "Watt"], "a": 0, "e": "The hertz is named after Heinrich Hertz.", "d": 1},
    {"t": "A body of mass 10 kg has weight (g = 10 m/s²):", "o": ["100 N", "10 N", "1 N", "1000 N"], "a": 0, "e": "W = mg = 100 N.", "d": 1},
    {"t": "The centre of gravity of a body is the point where:", "o": ["Its weight acts", "It is densest", "It is widest", "It is tallest"], "a": 0, "e": "Weight is considered to act at the centre of gravity.", "d": 1},
    {"t": "A simple machine that is an inclined plane wrapped around a cylinder is the:", "o": ["Lever", "Screw", "Pulley", "Wedge"], "a": 1, "e": "A screw is an inclined plane wrapped around a cylinder.", "d": 1},
    {"t": "The mechanical advantage (MA) of a machine is:", "o": ["Load/Effort", "Effort/Load", "Load × Effort", "Effort − Load"], "a": 0, "e": "MA = load/effort.", "d": 1},
    {"t": "The velocity ratio (VR) of a machine is the ratio of:", "o": ["Effort distance to load distance", "Load distance to effort distance", "Load to effort", "Work to time"], "a": 0, "e": "VR = distance moved by effort / distance moved by load.", "d": 1},
    {"t": "Efficiency equals:", "o": ["MA/VR", "VR/MA", "MA × VR", "MA + VR"], "a": 0, "e": "Efficiency = MA/VR.", "d": 2},
    {"t": "The energy possessed by a body due to its motion is:", "o": ["Potential energy", "Kinetic energy", "Thermal energy", "Chemical energy"], "a": 1, "e": "Kinetic energy is energy of motion.", "d": 1},
    {"t": "The energy possessed by a body due to its position is:", "o": ["Kinetic energy", "Potential energy", "Sound energy", "Light energy"], "a": 1, "e": "Potential energy is due to position.", "d": 1},
    {"t": "The density of a substance is:", "o": ["Mass per unit volume", "Volume per unit mass", "Mass × volume", "Weight per unit area"], "a": 0, "e": "Density = mass/volume.", "d": 1},
    {"t": "An object floats when its density is:", "o": ["Greater than the fluid", "Less than the fluid", "Equal to the fluid only", "Irrelevant"], "a": 1, "e": "Objects float when less dense than the fluid.", "d": 1},
    {"t": "The upthrust on a submerged object equals the weight of:", "o": ["The object", "The fluid displaced", "The object and fluid", "Nothing"], "a": 1, "e": "Archimedes' principle: upthrust = weight of displaced fluid.", "d": 1},
    {"t": "The SI unit of electric power is the:", "o": ["Watt", "Joule", "Volt", "Ohm"], "a": 0, "e": "Power is in watts.", "d": 1},
    {"t": "Which of the following is an electromagnetic wave?", "o": ["Sound", "Water wave", "X-ray", "Seismic wave"], "a": 2, "e": "X-rays are EM waves.", "d": 1},
    {"t": "The phenomenon of light bending around obstacles is:", "o": ["Reflection", "Diffraction", "Refraction", "Dispersion"], "a": 1, "e": "Diffraction is the bending of waves around obstacles.", "d": 1},
    {"t": "The law of conservation of linear momentum applies when:", "o": ["External force is present", "No external force acts", "Friction is present", "Always"], "a": 1, "e": "Momentum is conserved only with no net external force.", "d": 2},
    {"t": "A projectile's vertical motion is affected by:", "o": ["Gravity", "Friction only", "Air only", "Nothing"], "a": 0, "e": "Gravity accelerates a projectile vertically.", "d": 1},
    {"t": "The SI unit of work is the:", "o": ["Joule", "Watt", "Newton", "Pascal"], "a": 0, "e": "Work is measured in joules.", "d": 1},

    # ── Extra: electricity, waves, optics, modern ──
    {"t": "The resistance of a conductor is measured using a(n):", "o": ["Ammeter", "Ohmmeter", "Voltmeter", "Galvanometer"], "a": 1, "e": "An ohmmeter measures resistance.", "d": 1},
    {"t": "The electric charge on an electron is:", "o": ["Positive", "Negative", "Neutral", "Zero"], "a": 1, "e": "Electrons carry negative charge.", "d": 1},
    {"t": "Current is defined as:", "o": ["Rate of flow of charge", "Rate of flow of energy", "Charge per unit area", "Voltage per resistance"], "a": 0, "e": "I = Q/t, the rate of charge flow.", "d": 1},
    {"t": "The unit of electromotive force (emf) is the:", "o": ["Ampere", "Volt", "Ohm", "Watt"], "a": 1, "e": "Emf is measured in volts.", "d": 1},
    {"t": "In a parallel circuit, the voltage across each branch is:", "o": ["The same", "Different", "Zero", "Halved"], "a": 0, "e": "Parallel branches share the same voltage.", "d": 1},
    {"t": "In a series circuit, the current through each component is:", "o": ["The same", "Different", "Zero", "Doubled"], "a": 0, "e": "Series circuits have the same current throughout.", "d": 1},
    {"t": "The frequency of a wave is measured in:", "o": ["Hertz", "Metres", "Seconds", "Joules"], "a": 0, "e": "Frequency is in hertz.", "d": 1},
    {"t": "The wavelength of a wave is measured in:", "o": ["Metres", "Hertz", "Seconds", "Amperes"], "a": 0, "e": "Wavelength is a distance, in metres.", "d": 1},
    {"t": "A wave has speed 100 m/s and frequency 50 Hz. Its wavelength is:", "o": ["2 m", "5000 m", "0.5 m", "150 m"], "a": 0, "e": "λ = v/f = 100/50 = 2 m.", "d": 2},
    {"t": "The image formed on the retina of the eye is:", "o": ["Real and inverted", "Virtual and upright", "Real and upright", "Virtual and inverted"], "a": 0, "e": "The retina receives a real, inverted image.", "d": 2},
    {"t": "The part of the eye that controls the amount of light entering is the:", "o": ["Retina", "Iris", "Cornea", "Lens"], "a": 1, "e": "The iris regulates light entry via the pupil.", "d": 1},
    {"t": "The defect of vision corrected by a concave lens is:", "o": ["Hypermetropia", "Myopia", "Astigmatism", "Presbyopia"], "a": 1, "e": "Myopia (short-sightedness) is corrected with a concave lens.", "d": 2},
    {"t": "The defect of vision corrected by a convex lens is:", "o": ["Myopia", "Hypermetropia", "Colour blindness", "Cataract"], "a": 1, "e": "Hypermetropia (long-sightedness) uses a convex lens.", "d": 2},
    {"t": "A magnifying glass is a:", "o": ["Concave lens", "Convex lens", "Plane mirror", "Prism"], "a": 1, "e": "A magnifying glass is a convex lens.", "d": 1},
    {"t": "The colour of an opaque object is determined by the light it:", "o": ["Absorbs", "Reflects", "Transmits", "Refracts"], "a": 1, "e": "An object appears the colour of the light it reflects.", "d": 2},
    {"t": "The primary colours of light are:", "o": ["Red, green, blue", "Red, yellow, blue", "Cyan, magenta, yellow", "Red, green, yellow"], "a": 0, "e": "Primary light colours are RGB.", "d": 1},
    {"t": "The phenomenon of light vibrating in one plane only is:", "o": ["Dispersion", "Polarisation", "Diffraction", "Refraction"], "a": 1, "e": "Polarisation restricts light to one plane.", "d": 2},
    {"t": "A total internal reflection occurs when light travels from a ___ medium to a ___ medium at an angle greater than the critical angle.", "o": ["Denser, rarer", "Rarer, denser", "Equal, equal", "Vacuum, air"], "a": 0, "e": "TIR occurs going from denser to rarer beyond the critical angle.", "d": 2},
    {"t": "The device used to convert a.c. to d.c. is the:", "o": ["Transformer", "Rectifier", "Transistor", "Resistor"], "a": 1, "e": "A rectifier converts a.c. to d.c.", "d": 2},
    {"t": "A semiconductor diode allows current to flow in:", "o": ["Both directions", "One direction only", "No direction", "Alternating only"], "a": 1, "e": "A diode conducts in one direction only.", "d": 1},
    {"t": "The process by which a nucleus splits into smaller nuclei is:", "o": ["Fusion", "Fission", "Decay", "Ionisation"], "a": 1, "e": "Fission splits a heavy nucleus.", "d": 1},
    {"t": "The process by which light nuclei combine to form a heavier nucleus is:", "o": ["Fission", "Fusion", "Decay", "Ionisation"], "a": 1, "e": "Fusion combines light nuclei.", "d": 1},
    {"t": "The half-life of a radioactive substance is the time for:", "o": ["All atoms to decay", "Half the atoms to decay", "The mass to double", "The activity to double"], "a": 1, "e": "Half-life = time for half the nuclei to decay.", "d": 1},
    {"t": "A radioactive substance has a half-life of 2 hours. After 6 hours, the fraction remaining is:", "o": ["1/8", "1/2", "1/4", "1/3"], "a": 0, "e": "6 h = 3 half-lives → (1/2)³ = 1/8.", "d": 2},
    {"t": "The device used to detect radiation is the:", "o": ["Geiger-Muller counter", "Barometer", "Hygrometer", "Thermometer"], "a": 0, "e": "A Geiger-Muller counter detects ionising radiation.", "d": 1},
    {"t": "X-rays were discovered by:", "o": ["Roentgen", "Becquerel", "Curie", "Hertz"], "a": 0, "e": "Wilhelm Roentgen discovered X-rays.", "d": 1},
    {"t": "X-rays are used in medicine mainly for:", "o": ["Imaging bones", "Cooling", "Heating", "Sterilising food"], "a": 0, "e": "X-rays image dense structures like bones.", "d": 1},
    {"t": "The S.I. unit of luminous intensity is the:", "o": ["Candela", "Lumen", "Lux", "Watt"], "a": 0, "e": "Luminous intensity is in candelas (cd).", "d": 2},
    {"t": "The S.I. unit of amount of substance is the:", "o": ["Mole", "Gram", "Kilogram", "Litre"], "a": 0, "e": "Amount of substance is in moles (mol).", "d": 1},
    {"t": "The energy stored in a stretched spring is:", "o": ["Kinetic energy", "Elastic potential energy", "Gravitational PE", "Chemical energy"], "a": 1, "e": "A stretched spring stores elastic potential energy.", "d": 1},
    {"t": "Hooke's law states that extension is proportional to:", "o": ["Force (within the elastic limit)", "Temperature", "Time", "Mass"], "a": 0, "e": "F ∝ e within the elastic limit.", "d": 1},
    {"t": "The unit of spring constant is:", "o": ["N/m", "N m", "N/m²", "J"], "a": 0, "e": "k = F/e → N/m.", "d": 2},
    {"t": "The time period of a simple pendulum depends on:", "o": ["Length and gravity", "Mass", "Amplitude", "Material"], "a": 0, "e": "T = 2π√(L/g).", "d": 2},
    {"t": "The frequency of a simple pendulum is the:", "o": ["Reciprocal of its period", "Same as its period", "Square of its period", "Double its period"], "a": 0, "e": "f = 1/T.", "d": 1},
    {"t": "The unit of momentum is:", "o": ["kg m/s", "N", "kg m/s²", "J"], "a": 0, "e": "p = mv → kg m/s.", "d": 1},
    {"t": "The impulse of a force equals the change in:", "o": ["Momentum", "Energy", "Speed", "Force"], "a": 0, "e": "Impulse = change in momentum.", "d": 1},
    {"t": "Impulse is calculated as:", "o": ["Force × time", "Force × distance", "Mass × acceleration", "Work × time"], "a": 0, "e": "Impulse = F × t.", "d": 1},
    {"t": "The escape velocity is the minimum velocity to:", "o": ["Overcome gravity completely", "Enter orbit", "Land on the moon", "Reach the atmosphere"], "a": 0, "e": "Escape velocity frees a body from gravitational pull.", "d": 2},
    {"t": "A satellite in a stable orbit experiences:", "o": ["Weightlessness", "Increased weight", "No gravity", "Constant force"], "a": 0, "e": "Orbiting bodies appear weightless (free fall).", "d": 2},
    {"t": "The force that keeps planets in orbit is:", "o": ["Gravitational force", "Magnetic force", "Electric force", "Nuclear force"], "a": 0, "e": "Gravity keeps planets in orbit.", "d": 1},
    {"t": "Newton's law of universal gravitation states force ∝:", "o": ["Product of masses / distance²", "Distance²", "Mass²", "Distance/mass"], "a": 0, "e": "F = Gm₁m₂/r².", "d": 1},
]

build("phy", "Physics", QUESTIONS[:200])
