from _common import build

QUESTIONS = [
    # ── Meaning & scope ──
    {"t": "Government is best defined as the:", "o": ["Ruling party", "Machinery through which the state exercises power", "President", "Civil service"], "a": 1, "e": "Government is the machinery of state power.", "d": 1},
    {"t": "The study of government is also called:", "o": ["Sociology", "Political science", "Economics", "History"], "a": 1, "e": "Government = political science.", "d": 1},
    {"t": "The three organs of government are:", "o": ["Legislature, executive, judiciary", "President, governor, minister", "Army, police, courts", "Federal, state, local"], "a": 0, "e": "The organs are legislature, executive, judiciary.", "d": 1},
    {"t": "The power to make laws belongs to the:", "o": ["Executive", "Legislature", "Judiciary", "Police"], "a": 1, "e": "The legislature makes laws.", "d": 1},
    {"t": "The power to implement laws belongs to the:", "o": ["Legislature", "Executive", "Judiciary", "Civil society"], "a": 1, "e": "The executive implements laws.", "d": 1},
    {"t": "The power to interpret laws belongs to the:", "o": ["Executive", "Legislature", "Judiciary", "Police"], "a": 2, "e": "The judiciary interprets laws.", "d": 1},
    {"t": "A state is defined by all EXCEPT:", "o": ["Population", "Territory", "Government", "A single political party"], "a": 3, "e": "A state needs population, territory, government and sovereignty.", "d": 1},
    {"t": "Sovereignty is the:", "o": ["Wealth of a state", "Supreme power of the state", "Size of the state", "Population"], "a": 1, "e": "Sovereignty is supreme authority.", "d": 1},
    {"t": "A nation is a group of people with:", "o": ["Only shared territory", "Shared culture, history and identity", "Only shared language", "Nothing in common"], "a": 1, "e": "A nation shares culture and identity.", "d": 1},
    {"t": "Power is best defined as the:", "o": ["Wealth of a person", "Ability to make others do what you want", "Size of an army", "Popularity"], "a": 1, "e": "Power is the ability to influence others.", "d": 1},
    {"t": "Authority is power that is:", "o": ["Illegal", "Legitimate/accepted", "Coercive only", "Temporary"], "a": 1, "e": "Authority is legitimate power.", "d": 1},
    {"t": "Legitimacy means the:", "o": ["Legality of a law", "Acceptance of the right to rule", "Size of government", "Wealth of rulers"], "a": 1, "e": "Legitimacy = acceptance of the right to rule.", "d": 1},

    # ── Constitution ──
    {"t": "A constitution is a:", "o": ["Set of fundamental laws/principles of a state", "Political party", "Court ruling", "Government ministry"], "a": 0, "e": "A constitution sets out state principles.", "d": 1},
    {"t": "A written constitution is one that is:", "o": ["Unwritten", "Contained in a single document", "Based on customs", "Illegal"], "a": 1, "e": "A written constitution is in one document.", "d": 1},
    {"t": "An unwritten constitution is based on:", "o": ["A single document", "Customs, conventions and statutes", "Only statutes", "Court cases only"], "a": 1, "e": "Unwritten constitutions derive from customs and conventions.", "d": 1},
    {"t": "Which country has an unwritten constitution?", "o": ["Nigeria", "Britain", "USA", "Ghana"], "a": 1, "e": "Britain has an unwritten constitution.", "d": 1},
    {"t": "A rigid constitution is one that is:", "o": ["Easy to amend", "Difficult to amend", "Unwritten", "Illegal"], "a": 1, "e": "Rigid constitutions are hard to amend.", "d": 1},
    {"t": "A flexible constitution is one that is:", "o": ["Hard to amend", "Easy to amend", "Written only", "Rigid"], "a": 1, "e": "Flexible constitutions are easily amended.", "d": 1},
    {"t": "The principle of separation of powers was popularised by:", "o": ["Rousseau", "Montesquieu", "Locke", "Hobbes"], "a": 1, "e": "Montesquieu popularised separation of powers.", "d": 1},
    {"t": "The principle of separation of powers aims to prevent:", "o": ["Elections", "Abuse of power", "Taxation", "Law-making"], "a": 1, "e": "It prevents concentration/abuse of power.", "d": 1},
    {"t": "Checks and balances refers to:", "o": ["Banking", "Each organ checking the others", "Military rule", "Elections"], "a": 1, "e": "Organs check and balance each other.", "d": 1},
    {"t": "The rule of law means:", "o": ["Rule by the military", "Equality before the law and supremacy of law", "Rule by the rich", "Rule by one person"], "a": 1, "e": "Rule of law = no one is above the law.", "d": 1},
    {"t": "The rule of law was popularised by:", "o": ["Montesquieu", "A.V. Dicey", "Locke", "Marx"], "a": 1, "e": "Dicey articulated the rule of law.", "d": 1},

    # ── Political ideologies ──
    {"t": "Socialism advocates:", "o": ["Private ownership", "Public ownership of the means of production", "Free markets", "Monarchy"], "a": 1, "e": "Socialism favours public ownership.", "d": 1},
    {"t": "Capitalism advocates:", "o": ["Public ownership", "Private ownership and free markets", "Government control", "No trade"], "a": 1, "e": "Capitalism favours private ownership.", "d": 1},
    {"t": "Communism was propounded by:", "o": ["Adam Smith", "Karl Marx", "Keynes", "Locke"], "a": 1, "e": "Marx propounded communism.", "d": 1},
    {"t": "Fascism is a political ideology that is:", "o": ["Democratic", "Authoritarian and nationalist", "Socialist", "Liberal"], "a": 1, "e": "Fascism is authoritarian nationalism.", "d": 1},
    {"t": "Liberalism emphasises:", "o": ["State control", "Individual freedom and rights", "Dictatorship", "Monarchy"], "a": 1, "e": "Liberalism values individual liberty.", "d": 1},
    {"t": "The ideology that rejects all forms of government is:", "o": ["Socialism", "Anarchism", "Fascism", "Communism"], "a": 1, "e": "Anarchism rejects government.", "d": 1},

    # ── Organs/arms of government ──
    {"t": "A bicameral legislature has:", "o": ["One house", "Two houses", "Three houses", "No houses"], "a": 1, "e": "Bicameral = two chambers.", "d": 1},
    {"t": "A unicameral legislature has:", "o": ["Two houses", "One house", "Three houses", "No houses"], "a": 1, "e": "Unicameral = one chamber.", "d": 1},
    {"t": "Nigeria's federal legislature is:", "o": ["Unicameral", "Bicameral", "Tricameral", "None"], "a": 1, "e": "Nigeria has a bicameral National Assembly.", "d": 1},
    {"t": "The two houses of Nigeria's National Assembly are:", "o": ["Senate and House of Representatives", "Senate and House of Lords", "Congress and Senate", "Council and Senate"], "a": 0, "e": "Senate + House of Representatives.", "d": 1},
    {"t": "The head of the executive in Nigeria is the:", "o": ["Chief Justice", "President", "Senate President", "Speaker"], "a": 1, "e": "The President heads the executive.", "d": 1},
    {"t": "The head of the judiciary in Nigeria is the:", "o": ["President", "Chief Justice of Nigeria", "Attorney-General", "Senate President"], "a": 1, "e": "The Chief Justice heads the judiciary.", "d": 1},
    {"t": "The chief law officer of the federation is the:", "o": ["Chief Justice", "Attorney-General", "IGP", "President"], "a": 1, "e": "The Attorney-General is chief law officer.", "d": 1},
    {"t": "The presiding officer of the Senate is the:", "o": ["Speaker", "Senate President", "Clerk", "Whip"], "a": 1, "e": "The Senate President presides over the Senate.", "d": 1},
    {"t": "The presiding officer of the House of Representatives is the:", "o": ["Senate President", "Speaker", "Clerk", "Majority Leader"], "a": 1, "e": "The Speaker presides over the House.", "d": 1},
    {"t": "A bill becomes law after it is signed by the:", "o": ["Chief Justice", "President (assent)", "Speaker", "IGP"], "a": 1, "e": "The President's assent makes a bill law.", "d": 1},

    # ── Federalism ──
    {"t": "Federalism is a system where power is shared between:", "o": ["The central and component units", "Only the centre", "Only states", "The army"], "a": 0, "e": "Federalism divides power between centre and units.", "d": 1},
    {"t": "Nigeria became a federation in:", "o": ["1960", "1954", "1946", "1963"], "a": 1, "e": "The Lyttleton Constitution (1954) made Nigeria a federation.", "d": 1},
    {"t": "The number of states in Nigeria is:", "o": ["30", "36", "40", "25"], "a": 1, "e": "Nigeria has 36 states.", "d": 1},
    {"t": "The current Federal Capital Territory of Nigeria is:", "o": ["Lagos", "Abuja", "Kano", "Ibadan"], "a": 1, "e": "Abuja is the FCT.", "d": 1},
    {"t": "The former capital of Nigeria was:", "o": ["Abuja", "Lagos", "Calabar", "Port Harcourt"], "a": 1, "e": "Lagos was the former capital.", "d": 1},
    {"t": "The federal system is most suitable for a country that is:", "o": ["Small and homogeneous", "Large and diverse", "Only rural", "Only urban"], "a": 1, "e": "Federalism suits large, diverse states.", "d": 1},
    {"t": "In a unitary system, power is concentrated in the:", "o": ["States", "Central government", "Local councils", "Regions"], "a": 1, "e": "Unitary systems centralise power.", "d": 1},
    {"t": "A confederation is a union where the component units:", "o": ["Lose sovereignty", "Retain their sovereignty", "Merge completely", "Disappear"], "a": 1, "e": "In a confederation, units keep sovereignty.", "d": 1},
    {"t": "The exclusive legislative list contains matters for the:", "o": ["States", "Federal government", "Local government", "Traditional rulers"], "a": 1, "e": "Exclusive list = federal matters.", "d": 1},
    {"t": "The concurrent legislative list contains matters for:", "o": ["The federal government only", "Both federal and state governments", "Local government only", "The judiciary"], "a": 1, "e": "Concurrent list = shared federal/state matters.", "d": 1},

    # ── Citizenship ──
    {"t": "Citizenship is the:", "o": ["Residence in a country", "Legal membership of a state with rights and duties", "Visiting a country", "Paying tax"], "a": 1, "e": "Citizenship is legal membership of a state.", "d": 1},
    {"t": "Citizenship by birth is called:", "o": ["Naturalisation", "Jus sanguinis/jus soli", "Registration", "Marriage"], "a": 1, "e": "Birth citizenship = jus sanguinis or jus soli.", "d": 1},
    {"t": "Citizenship acquired through legal application by a foreigner is:", "o": ["By birth", "Naturalisation", "By descent", "By registration"], "a": 1, "e": "Naturalisation grants citizenship by application.", "d": 1},
    {"t": "The right to vote in elections is called:", "o": ["Suffrage", "Citizenship", "Naturalisation", "Franchise only"], "a": 0, "e": "Suffrage (franchise) is the right to vote.", "d": 1},
    {"t": "Universal adult suffrage means the right to vote for:", "o": ["Only men", "All qualified adults", "Only the rich", "Only the educated"], "a": 1, "e": "Universal adult suffrage extends to all adults.", "d": 1},
    {"t": "A duty of a citizen is to:", "o": ["Vote only", "Obey the laws and pay taxes", "Travel freely", "Own property"], "a": 1, "e": "Citizens must obey laws and pay taxes.", "d": 1},
    {"t": "A right enjoyed by citizens is the right to:", "o": ["Break laws", "Freedom of speech and association", "Avoid taxes", "Disobey courts"], "a": 1, "e": "Citizens have civil rights like free speech.", "d": 1},

    # ── Political parties ──
    {"t": "A political party is an organisation that:", "o": ["Runs businesses", "Contests elections to gain power", "Enforces laws", "Collects taxes"], "a": 1, "e": "Parties contest elections for power.", "d": 1},
    {"t": "A one-party system exists when:", "o": ["Many parties exist", "Only one party is legally allowed", "No parties exist", "Two parties exist"], "a": 1, "e": "One-party systems permit one party.", "d": 1},
    {"t": "A two-party system has:", "o": ["One dominant party", "Two major parties", "Many parties", "No parties"], "a": 1, "e": "Two-party systems have two major parties.", "d": 1},
    {"t": "A multi-party system has:", "o": ["One party", "Two parties", "Many political parties", "No parties"], "a": 2, "e": "Multi-party systems have many parties.", "d": 1},
    {"t": "Nigeria operates a:", "o": ["One-party system", "Two-party system", "Multi-party system", "No-party system"], "a": 2, "e": "Nigeria has a multi-party system.", "d": 1},
    {"t": "The party in power that forms the government is the:", "o": ["Opposition party", "Ruling party", "Pressure group", "Faction"], "a": 1, "e": "The ruling party forms government.", "d": 1},
    {"t": "The main function of the opposition party is to:", "o": ["Support everything", "Criticise and check the government", "Collect taxes", "Make laws alone"], "a": 1, "e": "The opposition checks the government.", "d": 1},
    {"t": "The body that registers political parties in Nigeria is:", "o": ["CBN", "INEC", "NDIC", "NEC"], "a": 1, "e": "INEC registers political parties.", "d": 1},
    {"t": "INEC stands for:", "o": ["Independent National Electoral Commission", "Internal National Electoral Council", "Independent Nigerian Electoral Committee", "National Electoral Commission"], "a": 0, "e": "INEC = Independent National Electoral Commission.", "d": 1},

    # ── Pressure groups & public opinion ──
    {"t": "A pressure group is an organisation that:", "o": ["Contests elections", "Tries to influence government policy", "Makes laws", "Enforces laws"], "a": 1, "e": "Pressure groups influence policy without contesting elections.", "d": 1},
    {"t": "The main difference between a political party and a pressure group is that a party:", "o": ["Influences policy", "Contests elections for power", "Has members", "Has interests"], "a": 1, "e": "Parties seek power via elections.", "d": 1},
    {"t": "The Nigerian Labour Congress (NLC) is an example of a:", "o": ["Political party", "Pressure group", "Government body", "Court"], "a": 1, "e": "The NLC is a labour pressure group.", "d": 1},
    {"t": "Public opinion is the:", "o": ["Government's view", "Aggregate of citizens' views on issues", "Judges' view", "Party view"], "a": 1, "e": "Public opinion is the collective view of the people.", "d": 1},
    {"t": "Public opinion can be measured through:", "o": ["Elections and opinion polls", "War", "Taxation", "Rumours"], "a": 0, "e": "Polls and elections measure public opinion.", "d": 1},

    # ── Elections & electoral systems ──
    {"t": "An election is the process of:", "o": ["Making laws", "Choosing representatives by voting", "Collecting taxes", "Appointing judges"], "a": 1, "e": "Elections choose representatives by vote.", "d": 1},
    {"t": "A referendum is a:", "o": ["General election", "Direct vote by citizens on a specific issue", "Party primary", "Court case"], "a": 1, "e": "A referendum lets citizens vote on an issue.", "d": 1},
    {"t": "A by-election is held to fill:", "o": ["All seats", "A vacant seat between general elections", "The presidency", "Judicial posts"], "a": 1, "e": "By-elections fill vacancies.", "d": 1},
    {"t": "The first-past-the-post system awards the seat to the candidate with:", "o": ["The most votes", "Over 50%", "Two-thirds", "All votes"], "a": 0, "e": "FPTP = simple majority wins.", "d": 1},
    {"t": "The secret ballot means voting is:", "o": ["Public", "Confidential/anonymous", "By show of hands", "Open"], "a": 1, "e": "Secret ballot protects voter privacy.", "d": 1},
    {"t": "Gerrymandering is the:", "o": ["Fair drawing of constituencies", "Manipulation of constituency boundaries for advantage", "Counting votes", "Registering voters"], "a": 1, "e": "Gerrymandering manipulates boundaries.", "d": 2},
    {"t": "The voting age in Nigeria is:", "o": ["16", "18", "21", "20"], "a": 1, "e": "Voting age in Nigeria is 18.", "d": 1},

    # ── Political development in Nigeria ──
    {"t": "The first colonial constitution of Nigeria was the:", "o": ["Clifford Constitution (1922)", "Richard Constitution (1946)", "Macpherson (1951)", "Lyttleton (1954)"], "a": 0, "e": "Clifford Constitution (1922) was first.", "d": 1},
    {"t": "The Richard Constitution of 1946 divided Nigeria into:", "o": ["States", "Three regions", "Two regions", "Six zones"], "a": 1, "e": "The Richard Constitution created three regions.", "d": 1},
    {"t": "The Lyttleton Constitution of 1954 established:", "o": ["Unitary government", "A federal system", "Military rule", "Monarchy"], "a": 1, "e": "Lyttleton (1954) established federalism.", "d": 1},
    {"t": "Nigeria gained independence on:", "o": ["1 October 1960", "1 October 1963", "1 January 1960", "29 May 1999"], "a": 0, "e": "Independence was 1 October 1960.", "d": 1},
    {"t": "Nigeria became a republic in:", "o": ["1960", "1963", "1966", "1979"], "a": 1, "e": "Nigeria became a republic in 1963.", "d": 1},
    {"t": "Nigeria's first President was:", "o": ["Tafawa Balewa", "Nnamdi Azikiwe", "Obafemi Awolowo", "Ahmadu Bello"], "a": 1, "e": "Azikiwe was first President (ceremonial).", "d": 1},
    {"t": "Nigeria's first Prime Minister was:", "o": ["Nnamdi Azikiwe", "Abubakar Tafawa Balewa", "Ahmadu Bello", "Awolowo"], "a": 1, "e": "Balewa was first Prime Minister.", "d": 1},
    {"t": "Nigeria's first military coup was in:", "o": ["1963", "1966", "1967", "1970"], "a": 1, "e": "The first coup was January 1966.", "d": 1},
    {"t": "The Nigerian Civil War lasted from:", "o": ["1967–1970", "1966–1967", "1970–1973", "1963–1966"], "a": 0, "e": "The Civil War was 1967–1970.", "d": 1},
    {"t": "The leader of Biafra during the Civil War was:", "o": ["Gowon", "Ojukwu", "Ironsi", "Obasanjo"], "a": 1, "e": "Odumegwu Ojukwu led Biafra.", "d": 1},
    {"t": "The head of state who prosecuted the Civil War was:", "o": ["Ironsi", "Yakubu Gowon", "Buhari", "Babangida"], "a": 1, "e": "Gowon was head of state during the war.", "d": 1},
    {"t": "The 'no victor, no vanquished' declaration was made by:", "o": ["Gowon", "Ojukwu", "Obasanjo", "Shagari"], "a": 0, "e": "Gowon declared 'no victor, no vanquished'.", "d": 1},
    {"t": "The first military head of state of Nigeria was:", "o": ["Gowon", "Aguiyi-Ironsi", "Obasanjo", "Murtala"], "a": 1, "e": "Ironsi was the first military head of state.", "d": 1},
    {"t": "The head of state assassinated in 1976 was:", "o": ["Ironsi", "Murtala Mohammed", "Gowon", "Abacha"], "a": 1, "e": "Murtala Mohammed was assassinated in 1976.", "d": 1},
    {"t": "The head of state who returned Nigeria to civilian rule in 1979 was:", "o": ["Murtala", "Olusegun Obasanjo", "Gowon", "Buhari"], "a": 1, "e": "Obasanjo handed over to civilians in 1979.", "d": 1},
    {"t": "The President of the Second Republic was:", "o": ["Obasanjo", "Shehu Shagari", "Shonekan", "Babangida"], "a": 1, "e": "Shagari was Second Republic president.", "d": 1},
    {"t": "The head of state who annulled the 1993 election was:", "o": ["Buhari", "Ibrahim Babangida", "Abacha", "Gowon"], "a": 1, "e": "Babangida annulled the June 12, 1993 election.", "d": 1},
    {"t": "The winner of the annulled 1993 election was:", "o": ["Abiola", "Tofa", "Shagari", "Obasanjo"], "a": 0, "e": "M.K.O. Abiola won the June 12 election.", "d": 1},
    {"t": "The Interim National Government (1993) was headed by:", "o": ["Abacha", "Ernest Shonekan", "Babangida", "Abiola"], "a": 1, "e": "Shonekan headed the ING.", "d": 1},
    {"t": "The head of state who died in office in 1998 was:", "o": ["Babangida", "Sani Abacha", "Buhari", "Ironsi"], "a": 1, "e": "Abacha died in office in 1998.", "d": 1},
    {"t": "The head of state who handed over to democracy in 1999 was:", "o": ["Abacha", "Abdulsalami Abubakar", "Babangida", "Buhari"], "a": 1, "e": "Abdulsalami Abubakar handed over in 1999.", "d": 1},
    {"t": "Nigeria's current democracy (Fourth Republic) began in:", "o": ["1993", "1999", "1979", "2007"], "a": 1, "e": "The Fourth Republic began in 1999.", "d": 1},
    {"t": "The first President of the Fourth Republic was:", "o": ["Obasanjo", "Yar'Adua", "Jonathan", "Buhari"], "a": 0, "e": "Obasanjo was first Fourth Republic president.", "d": 1},
    {"t": "The 1999 Constitution established:", "o": ["Parliamentary system", "Presidential system", "Monarchy", "Military rule"], "a": 1, "e": "The 1999 Constitution is presidential.", "d": 1},

    # ── Military rule ──
    {"t": "A military government rules by:", "o": ["Elections", "Decrees", "Referenda", "Consensus"], "a": 1, "e": "Military regimes rule by decree.", "d": 1},
    {"t": "A decree is a law made by the:", "o": ["Legislature", "Military government", "Judiciary", "Local council"], "a": 1, "e": "Decrees are military-made laws.", "d": 1},
    {"t": "A coup d'état is the:", "o": ["Peaceful transfer of power", "Violent seizure of government", "Election", "Referendum"], "a": 1, "e": "A coup is a violent takeover.", "d": 1},
    {"t": "One disadvantage of military rule is:", "o": ["Order", "Abuse of human rights", "Discipline", "Speed"], "a": 1, "e": "Military rule often abuses rights.", "d": 1},

    # ── Foreign policy & international organisations ──
    {"t": "Foreign policy is a country's:", "o": ["Internal policies", "Policies toward other countries", "Economic plans", "Tax policy"], "a": 1, "e": "Foreign policy governs external relations.", "d": 1},
    {"t": "The main focus of Nigeria's foreign policy is:", "o": ["Asia first", "Africa as centrepiece", "Europe only", "Isolation"], "a": 1, "e": "Africa is the centrepiece of Nigeria's foreign policy.", "d": 1},
    {"t": "The UN was founded in:", "o": ["1945", "1919", "1948", "1960"], "a": 0, "e": "The UN was founded in 1945.", "d": 1},
    {"t": "The headquarters of the UN is in:", "o": ["Geneva", "New York", "Paris", "London"], "a": 1, "e": "The UN headquarters is in New York.", "d": 1},
    {"t": "The main organ of the UN responsible for peace and security is the:", "o": ["General Assembly", "Security Council", "Secretariat", "ECOSOC"], "a": 1, "e": "The Security Council maintains peace.", "d": 1},
    {"t": "The five permanent members of the UN Security Council are:", "o": ["USA, UK, France, Russia, China", "USA, UK, Germany, Japan, China", "USA, UK, France, India, China", "USA, Russia, China, Brazil, UK"], "a": 0, "e": "The P5: USA, UK, France, Russia, China.", "d": 1},
    {"t": "The AU was formerly called the:", "o": ["ECOWAS", "OAU", "League of Nations", "Commonwealth"], "a": 1, "e": "The AU succeeded the OAU.", "d": 1},
    {"t": "The headquarters of the African Union is in:", "o": ["Lagos", "Addis Ababa", "Nairobi", "Accra"], "a": 1, "e": "The AU is headquartered in Addis Ababa.", "d": 1},
    {"t": "The AU was founded in:", "o": ["2002", "1963", "1999", "1945"], "a": 0, "e": "The AU was launched in 2002.", "d": 1},
    {"t": "The OAU was founded in:", "o": ["1963", "2002", "1945", "1975"], "a": 0, "e": "The OAU was founded in 1963.", "d": 1},
    {"t": "The headquarters of ECOWAS is in:", "o": ["Accra", "Abuja", "Lome", "Dakar"], "a": 1, "e": "ECOWAS is headquartered in Abuja.", "d": 1},
    {"t": "The Commonwealth is an association of:", "o": ["African states", "Mostly former British colonies", "American states", "Asian states"], "a": 1, "e": "The Commonwealth comprises mostly former British colonies.", "d": 1},
    {"t": "The head of the Commonwealth is the:", "o": ["UN Secretary-General", "British monarch", "AU Chairperson", "US President"], "a": 1, "e": "The British monarch heads the Commonwealth.", "d": 1},
    {"t": "Nigeria's membership of the Commonwealth was suspended during:", "o": ["Civilian rule", "Military rule (especially under Abacha)", "Colonial rule", "Independence"], "a": 1, "e": "Nigeria was suspended under Abacha.", "d": 2},
    {"t": "The ECOWAS protocol concerns:", "o": ["Free movement of persons and goods", "Military alliance only", "Taxation", "Religion"], "a": 0, "e": "ECOWAS promotes free movement and trade.", "d": 1},
    {"t": "The main organ of the AU is the:", "o": ["Assembly", "Parliament", "Court", "Commission"], "a": 0, "e": "The Assembly of Heads of State is the main organ.", "d": 1},
    {"t": "The Secretary-General heads the:", "o": ["Security Council", "UN Secretariat", "General Assembly", "ECOSOC"], "a": 1, "e": "The Secretary-General heads the Secretariat.", "d": 1},
    {"t": "Non-alignment in foreign policy means:", "o": ["Joining blocs", "Not aligning with any major power bloc", "Isolation", "Neutrality in all matters"], "a": 1, "e": "Non-alignment avoids power blocs.", "d": 1},
    {"t": "The Non-Aligned Movement was formed during the:", "o": ["Cold War", "World War I", "Colonial era", "2000s"], "a": 0, "e": "NAM formed during the Cold War.", "d": 1},
    {"t": "The main aim of Nigeria's membership of international organisations is to:", "o": ["Dominate", "Promote cooperation and development", "Isolate", "Tax others"], "a": 1, "e": "Membership fosters cooperation.", "d": 1},
    {"t": "The colonial power that ruled Nigeria was:", "o": ["France", "Britain", "Portugal", "Germany"], "a": 1, "e": "Britain colonised Nigeria.", "d": 1},
    {"t": "Indirect rule in Nigeria was associated with:", "o": ["Goldie", "Lord Lugard", "Clifford", "Richards"], "a": 1, "e": "Lugard practised indirect rule.", "d": 1},
    {"t": "The amalgamation of Nigeria was in:", "o": ["1914", "1900", "1922", "1946"], "a": 0, "e": "Nigeria was amalgamated in 1914.", "d": 1},
    {"t": "The person who amalgamated Nigeria was:", "o": ["Clifford", "Lord Lugard", "Richards", "Macpherson"], "a": 1, "e": "Lugard amalgamated Nigeria in 1914.", "d": 1},
    {"t": "The body that made laws in colonial Nigeria was the:", "o": ["Parliament", "Legislative Council", "Senate", "Assembly"], "a": 1, "e": "The Legislative Council made colonial laws.", "d": 1},
    {"t": "The Clifford Constitution established:", "o": ["Federalism", "An elected Legislative Council", "Independence", "Republic"], "a": 1, "e": "Clifford (1922) introduced an elected council.", "d": 1},
    {"t": "The first political party in Nigeria was the:", "o": ["NCNC", "NNPP", "Action Group", "NPC"], "a": 1, "e": "The Nigerian National Democratic Party (NNDP, 1923) was first.", "d": 1},
    {"t": "The NCNC was founded by:", "o": ["Awolowo", "Herbert Macaulay and Nnamdi Azikiwe", "Ahmadu Bello", "Balewa"], "a": 1, "e": "Macaulay and Azikiwe founded the NCNC.", "d": 1},
    {"t": "The Action Group was founded by:", "o": ["Azikiwe", "Obafemi Awolowo", "Bello", "Balewa"], "a": 1, "e": "Awolowo founded the Action Group.", "d": 1},
    {"t": "The NPC was led by:", "o": ["Awolowo", "Ahmadu Bello", "Azikiwe", "Ojukwu"], "a": 1, "e": "Ahmadu Bello led the NPC.", "d": 1},
    {"t": "The head of state who created 12 states in 1967 was:", "o": ["Ironsi", "Yakubu Gowon", "Obasanjo", "Buhari"], "a": 1, "e": "Gowon created 12 states in 1967.", "d": 1},
    {"t": "The number of regions in Nigeria at independence was:", "o": ["4", "3", "2", "5"], "a": 1, "e": "Nigeria had three regions at independence.", "d": 1},
    {"t": "The Mid-Western Region was created in:", "o": ["1963", "1967", "1954", "1976"], "a": 0, "e": "The Mid-West was created in 1963.", "d": 2},
    {"t": "The current Nigerian Constitution came into effect in:", "o": ["1999", "1979", "1995", "1963"], "a": 0, "e": "The 1999 Constitution is current.", "d": 1},
    {"t": "The head of the local government in Nigeria is the:", "o": ["Governor", "Chairman", "President", "Chief"], "a": 1, "e": "A chairman heads local government.", "d": 1},
    {"t": "The number of local government areas in Nigeria is:", "o": ["774", "776", "770", "780"], "a": 0, "e": "Nigeria has 774 LGAs.", "d": 1},
    {"t": "The head of a state government in Nigeria is the:", "o": ["President", "Governor", "Chairman", "Minister"], "a": 1, "e": "A governor heads a state.", "d": 1},
    {"t": "The term of office of the Nigerian President is:", "o": ["4 years", "5 years", "6 years", "3 years"], "a": 0, "e": "The President serves a 4-year term.", "d": 1},
    {"t": "The minimum age to be President of Nigeria is:", "o": ["30", "40", "35", "45"], "a": 1, "e": "A presidential candidate must be at least 40.", "d": 2},
    {"t": "The legislature of a Nigerian state is the:", "o": ["National Assembly", "House of Assembly", "Senate", "Council"], "a": 1, "e": "States have a House of Assembly.", "d": 1},
    {"t": "The supreme court is the highest court in:", "o": ["Each state", "Nigeria", "Each LGA", "The Commonwealth"], "a": 1, "e": "The Supreme Court is Nigeria's highest court.", "d": 1},
    {"t": "The number of Justices of the Supreme Court of Nigeria is:", "o": ["21", "15", "10", "30"], "a": 0, "e": "The Supreme Court has up to 21 Justices.", "d": 2},
    {"t": "The body that advises the President on legal matters is the:", "o": ["Senate", "Attorney-General and Minister of Justice", "Speaker", "IGP"], "a": 1, "e": "The Attorney-General advises on law.", "d": 1},
    {"t": "The police is headed by the:", "o": ["Minister", "Inspector-General of Police", "Attorney-General", "Chief Justice"], "a": 1, "e": "The IGP heads the police.", "d": 1},
    {"t": "The armed forces are headed by the:", "o": ["IGP", "President (Commander-in-Chief)", "Chief Justice", "Senate President"], "a": 1, "e": "The President is Commander-in-Chief.", "d": 1},
    {"t": "The document that contains fundamental human rights in Nigeria is the:", "o": ["Constitution", "Budget", "Party manifesto", "Census"], "a": 0, "e": "The Constitution contains fundamental rights.", "d": 1},
    {"t": "The ombudsman that investigates complaints against government is the:", "o": ["Court", "Public Complaints Commission", "Police", "Senate"], "a": 1, "e": "The Public Complaints Commission is the ombudsman.", "d": 1},
    # ── More: systems & concepts ──
    {"t": "In a presidential system, the president is:", "o": ["Part of the legislature", "Both head of state and head of government", "Only head of government", "Appointed by parliament"], "a": 1, "e": "The president is both head of state and government.", "d": 1},
    {"t": "In a parliamentary system, the head of government is the:", "o": ["Monarch", "Prime Minister", "President", "Speaker"], "a": 1, "e": "The Prime Minister heads government.", "d": 1},
    {"t": "In a parliamentary system, the head of state may be the:", "o": ["Prime Minister", "Monarch or President (ceremonial)", "Speaker", "Chief Justice"], "a": 1, "e": "A monarch/president is ceremonial head of state.", "d": 1},
    {"t": "A monarchy is a system ruled by a:", "o": ["President", "King or Queen", "Prime Minister", "Dictator"], "a": 1, "e": "Monarchies are ruled by royalty.", "d": 1},
    {"t": "A republic is a state without a:", "o": ["Constitution", "Monarch", "Government", "Flag"], "a": 1, "e": "A republic has no monarch.", "d": 1},
    {"t": "A dictatorship is characterised by:", "o": ["Free elections", "Absolute, unchecked power", "Rule of law", "Multi-party politics"], "a": 1, "e": "Dictators hold unchecked power.", "d": 1},
    {"t": "An oligarchy is rule by:", "o": ["The people", "A few people", "One person", "Religious leaders"], "a": 1, "e": "Oligarchy = rule by a few.", "d": 1},
    {"t": "An aristocracy is rule by the:", "o": ["Poor", "Nobility/privileged class", "Military", "People"], "a": 1, "e": "Aristocracy = rule by the privileged.", "d": 1},
    {"t": "Democracy is government by:", "o": ["One person", "The people", "The military", "A few"], "a": 1, "e": "Democracy = rule by the people.", "d": 1},
    {"t": "Direct democracy is practised through:", "o": ["Representatives", "Referenda and town meetings", "Parliament", "Courts"], "a": 1, "e": "Direct democracy uses referenda.", "d": 1},
    {"t": "Representative democracy means the people rule through:", "o": ["Referenda", "Elected representatives", "The monarch", "The military"], "a": 1, "e": "Representatives act for the people.", "d": 1},
    {"t": "The separation of powers divides government into:", "o": ["One organ", "Legislative, executive, judicial", "Federal and state", "Army and police"], "a": 1, "e": "Three organs are separated.", "d": 1},
    {"t": "The principle that no one is above the law is:", "o": ["Federalism", "Rule of law", "Sovereignty", "Checks and balances"], "a": 1, "e": "Rule of law = equality before the law.", "d": 1},
    {"t": "Fundamental human rights include the right to:", "o": ["Break laws", "Life, liberty and fair trial", "Avoid taxes", "Harm others"], "a": 1, "e": "Rights include life, liberty, fair trial.", "d": 1},
    {"t": "The right to freedom of the press is part of:", "o": ["Fundamental rights", "Government duties", "Tax law", "Military law"], "a": 0, "e": "Press freedom is a fundamental right.", "d": 1},
    {"t": "The process of law-making by the legislature is called:", "o": ["Execution", "Legislation", "Adjudication", "Administration"], "a": 1, "e": "Legislation is law-making.", "d": 1},
    {"t": "A proposed law before passage is called a:", "o": ["Decree", "Bill", "Edict", "Act"], "a": 1, "e": "A bill is a proposed law.", "d": 1},
    {"t": "A law made by the federal legislature is called an:", "o": ["Edict", "Act", "Bye-law", "Decree"], "a": 1, "e": "Federal laws are Acts.", "d": 1},
    {"t": "A law made by a state legislature is called an:", "o": ["Act", "Edict or Law", "Decree", "Bye-law"], "a": 1, "e": "States make Edicts (now Laws).", "d": 1},
    {"t": "A law made by a local government is a:", "o": ["Act", "Bye-law", "Decree", "Edict"], "a": 1, "e": "LGAs make bye-laws.", "d": 1},
    {"t": "The civil service is the body of:", "o": ["Elected officials", "Permanent government officials", "Soldiers", "Judges"], "a": 1, "e": "The civil service is permanent bureaucracy.", "d": 1},
    {"t": "The head of the civil service in Nigeria is the:", "o": ["President", "Head of Civil Service", "Minister", "Governor"], "a": 1, "e": "The Head of Civil Service leads it.", "d": 1},
    {"t": "The civil service is expected to be:", "o": ["Partisan", "Neutral and permanent", "Elected", "Temporary"], "a": 1, "e": "The civil service is neutral and permanent.", "d": 1},
    {"t": "A minister is a:", "o": ["Civil servant", "Political appointee heading a ministry", "Judge", "Governor"], "a": 1, "e": "Ministers are political appointees.", "d": 1},
    {"t": "The process of a minister answering to parliament is:", "o": ["Judicial review", "Ministerial responsibility", "Federalism", "Bicameralism"], "a": 1, "e": "Ministers are accountable to parliament.", "d": 1},
    {"t": "The doctrine of collective responsibility applies to the:", "o": ["Judiciary", "Cabinet", "Civil service", "Police"], "a": 1, "e": "The cabinet is collectively responsible.", "d": 1},
    {"t": "The body that checks the legality of government actions is the:", "o": ["Cabinet", "Judiciary (judicial review)", "Civil service", "Police"], "a": 1, "e": "Courts review legality of actions.", "d": 1},
    {"t": "Judicial review is the power of courts to:", "o": ["Make laws", "Declare laws/actions unconstitutional", "Execute laws", "Appoint ministers"], "a": 1, "e": "Courts review constitutionality.", "d": 1},
    {"t": "The power to grant pardon in Nigeria belongs to the:", "o": ["Chief Justice", "President", "Senate", "IGP"], "a": 1, "e": "The President grants pardons.", "d": 1},
    {"t": "The National Assembly can remove the President through:", "o": ["A decree", "Impeachment", "A coup", "Referendum"], "a": 1, "e": "Impeachment removes the President.", "d": 1},
    {"t": "The two-third majority is often required to:", "o": ["Pass ordinary bills", "Impeach or amend the constitution", "Appoint officials", "Collect taxes"], "a": 1, "e": "Impeachment/amendments need two-thirds.", "d": 2},
    {"t": "The quorum is the:", "o": ["Maximum members", "Minimum members required for a valid meeting", "Speaker", "Clerk"], "a": 1, "e": "A quorum is the minimum for validity.", "d": 1},
    {"t": "The process of voting a candidate out of office is:", "o": ["Impeachment", "Recall", "Coup", "Pardon"], "a": 1, "e": "Recall removes a representative.", "d": 1},
    {"t": "A manifesto is a document stating:", "o": ["A party's policies", "Court rulings", "Tax laws", "Census results"], "a": 0, "e": "A manifesto states party policies.", "d": 1},
    {"t": "The electorate refers to the:", "o": ["Candidates", "Voters", "Officials", "Parties"], "a": 1, "e": "The electorate are the voters.", "d": 1},
    {"t": "The body that divides constituencies in Nigeria is:", "o": ["CBN", "INEC", "FIRS", "NDIC"], "a": 1, "e": "INEC delimits constituencies.", "d": 2},
    {"t": "The first military coup in Nigeria was led by:", "o": ["Gowon", "Chukwuma Kaduna Nzeogwu", "Ironsi", "Obasanjo"], "a": 1, "e": "Nzeogwu led the 1966 coup.", "d": 2},
    {"t": "The counter-coup of July 1966 brought which leader to power?", "o": ["Gowon", "Ironsi", "Nzeogwu", "Obasanjo"], "a": 0, "e": "Gowon emerged after the July 1966 counter-coup.", "d": 2},
    {"t": "The 'three Rs' of post-war reconciliation were:", "o": ["Reconciliation, Reconstruction, Rehabilitation", "Rights, Rules, Revenue", "Reform, Rehab, Renewal", "Rest, Recovery, Relief"], "a": 0, "e": "Gowon's 3Rs: Reconciliation, Reconstruction, Rehabilitation.", "d": 2},
    {"t": "The NYSC scheme was established in:", "o": ["1973", "1976", "1960", "1999"], "a": 0, "e": "NYSC was established in 1973.", "d": 2},
    {"t": "The head of state who created the NYSC was:", "o": ["Gowon", "Obasanjo", "Buhari", "Babangida"], "a": 0, "e": "Gowon established NYSC.", "d": 2},
    {"t": "The Constitution that introduced the presidential system in Nigeria was the:", "o": ["1999 Constitution", "1979 Constitution", "1963 Constitution", "1960 Constitution"], "a": 1, "e": "The 1979 Constitution introduced presidentialism.", "d": 1},
    {"t": "The Second Republic lasted from:", "o": ["1979–1983", "1960–1966", "1999–2007", "1975–1979"], "a": 0, "e": "The Second Republic was 1979–1983.", "d": 1},
    {"t": "The military coup that ended the Second Republic was in:", "o": ["1979", "1983", "1993", "1966"], "a": 1, "e": "The 1983 coup ended the Second Republic.", "d": 2},
    {"t": "The head of state ousted in the 1983 coup was:", "o": ["Obasanjo", "Shehu Shagari", "Gowon", "Babangida"], "a": 1, "e": "Shagari was ousted in 1983.", "d": 1},
    {"t": "The head of state who introduced Structural Adjustment Programme (SAP) was:", "o": ["Buhari", "Ibrahim Babangida", "Abacha", "Gowon"], "a": 1, "e": "Babangida introduced SAP in 1986.", "d": 1},
    {"t": "The head of state who created 36 states was:", "o": ["Gowon", "Sani Abacha", "Babangida", "Buhari"], "a": 1, "e": "Abacha created the current 36-state structure.", "d": 2},
    {"t": "The June 12 election was held in:", "o": ["1993", "1999", "1991", "1983"], "a": 0, "e": "The June 12 election was in 1993.", "d": 1},
]

build("gov", "Government", QUESTIONS[:200])
