from _common import build

QUESTIONS = [
    # ── Commerce & occupations ──
    {"t": "Commerce is best defined as the:", "o": ["Production of goods", "Distribution and exchange of goods and services", "Manufacturing only", "Banking only"], "a": 1, "e": "Commerce covers distribution and exchange.", "d": 1},
    {"t": "Commerce is divided into:", "o": ["Trade and aids to trade", "Production and consumption", "Import and export", "Buying and selling"], "a": 0, "e": "Commerce = trade + aids to trade.", "d": 1},
    {"t": "Trade is the:", "o": ["Production of goods", "Buying and selling of goods and services", "Banking", "Insurance"], "a": 1, "e": "Trade = buying and selling.", "d": 1},
    {"t": "Home trade is trade:", "o": ["Between countries", "Within a country", "Only in cities", "Only online"], "a": 1, "e": "Home trade is within one country.", "d": 1},
    {"t": "Foreign trade is trade:", "o": ["Within a country", "Between countries", "Only in villages", "Between regions"], "a": 1, "e": "Foreign trade crosses borders.", "d": 1},
    {"t": "An occupation is a person's:", "o": ["Hobby", "Means of earning a living", "Religion", "Family"], "a": 1, "e": "An occupation is one's job/vocation.", "d": 1},
    {"t": "Occupations are broadly divided into:", "o": ["Industrial, commercial and service", "Manual and skilled", "Urban and rural", "Paid and unpaid"], "a": 0, "e": "Occupations: industrial, commercial, service.", "d": 1},
    {"t": "A person who works in a bank is in the ___ occupation.", "o": ["Industrial", "Commercial", "Service", "Extractive"], "a": 2, "e": "Banking is a service occupation.", "d": 1},
    {"t": "A farmer is in the ___ occupation.", "o": ["Commercial", "Service", "Industrial (extractive)", "Manufacturing"], "a": 2, "e": "Farming is extractive industry.", "d": 1},
    {"t": "A tailor is in the ___ occupation.", "o": ["Extractive", "Manufacturing/industrial", "Commercial", "Direct service"], "a": 1, "e": "Tailoring is manufacturing.", "d": 1},

    # ── Production ──
    {"t": "Production is the creation of:", "o": ["Money", "Utility", "Problems", "Waste"], "a": 1, "e": "Production creates utility.", "d": 1},
    {"t": "The three stages of production are:", "o": ["Primary, secondary, tertiary", "Start, middle, end", "Buying, selling, profit", "Input, process, cost"], "a": 0, "e": "Production stages: primary, secondary, tertiary.", "d": 1},
    {"t": "Primary production involves:", "o": ["Manufacturing", "Extracting raw materials", "Services", "Retailing"], "a": 1, "e": "Primary production extracts raw materials.", "d": 1},
    {"t": "Secondary production involves:", "o": ["Extraction", "Manufacturing/processing", "Services", "Farming only"], "a": 1, "e": "Secondary production manufactures goods.", "d": 1},
    {"t": "Tertiary production involves:", "o": ["Manufacturing", "Providing services", "Mining", "Farming"], "a": 1, "e": "Tertiary = services.", "d": 1},
    {"t": "The extractive industry is concerned with:", "o": ["Retailing", "Obtaining raw materials from nature", "Banking", "Transport"], "a": 1, "e": "Extractive industry gets natural resources.", "d": 1},
    {"t": "Which of the following is an extractive industry?", "o": ["Banking", "Fishing", "Tailoring", "Transport"], "a": 1, "e": "Fishing extracts from nature.", "d": 1},
    {"t": "The manufacturing industry is concerned with:", "o": ["Extraction", "Converting raw materials to finished goods", "Services", "Trade"], "a": 1, "e": "Manufacturing converts raw materials.", "d": 1},
    {"t": "Division of labour is the:", "o": ["Splitting work into tasks", "Working alone", "Reducing workers", "Hiring more staff"], "a": 0, "e": "Division of labour splits tasks.", "d": 1},
    {"t": "Specialisation increases:", "o": ["Costs", "Productivity", "Errors", "Time"], "a": 1, "e": "Specialisation raises productivity.", "d": 1},
    {"t": "A disadvantage of division of labour is:", "o": ["Higher output", "Monotony", "Lower costs", "More skill"], "a": 1, "e": "Repetitive work causes boredom.", "d": 1},

    # ── Trade ──
    {"t": "The two main types of trade are:", "o": ["Home and foreign trade", "Import and export", "Retail and wholesale", "Cash and credit"], "a": 0, "e": "Trade = home + foreign.", "d": 1},
    {"t": "Retail trade is selling to the:", "o": ["Wholesaler", "Final consumer", "Manufacturer", "Exporter"], "a": 1, "e": "Retail sells to final consumers.", "d": 1},
    {"t": "Wholesale trade is selling to:", "o": ["Consumers", "Retailers (for resale)", "Manufacturers only", "Government only"], "a": 1, "e": "Wholesale sells to retailers.", "d": 1},
    {"t": "The middleman who buys from the producer and sells to the retailer is the:", "o": ["Consumer", "Wholesaler", "Retailer", "Agent"], "a": 1, "e": "The wholesaler links producer and retailer.", "d": 1},
    {"t": "The middleman who sells directly to consumers is the:", "o": ["Wholesaler", "Retailer", "Producer", "Agent"], "a": 1, "e": "The retailer sells to consumers.", "d": 1},
    {"t": "The removal of middlemen from distribution is called:", "o": ["Channel", "Eliminating middlemen (direct selling)", "Wholesaling", "Retailing"], "a": 1, "e": "Removing middlemen = direct distribution.", "d": 1},
    {"t": "Goods sold to other countries are:", "o": ["Imports", "Exports", "Capital", "Aids"], "a": 1, "e": "Exports are sold abroad.", "d": 1},
    {"t": "Goods bought from other countries are:", "o": ["Exports", "Imports", "Capital", "Aids"], "a": 1, "e": "Imports are bought from abroad.", "d": 1},
    {"t": "A document that lists the goods shipped is the:", "o": ["Invoice", "Bill of lading", "Cheque", "Receipt"], "a": 1, "e": "A bill of lading lists shipped goods.", "d": 1},
    {"t": "The document that states the price and terms of sale is the:", "o": ["Bill of lading", "Invoice", "Pro forma", "Voucher"], "a": 1, "e": "An invoice states price/terms.", "d": 1},
    {"t": "The document used to request payment for goods is the:", "o": ["Invoice", "Order", "Receipt", "Bill of lading"], "a": 0, "e": "An invoice requests payment.", "d": 1},
    {"t": "Cash-and-carry trade is where the buyer:", "o": ["Buys on credit", "Pays cash and takes goods away", "Orders online", "Barters"], "a": 1, "e": "Cash-and-carry: pay and collect.", "d": 1},
    {"t": "Credit trade is where the buyer:", "o": ["Pays immediately", "Pays later", "Barters", "Pays more"], "a": 1, "e": "Credit trade defers payment.", "d": 1},
    {"t": "Barter is the exchange of:", "o": ["Goods for money", "Goods for goods", "Money for money", "Services for cash"], "a": 1, "e": "Barter = goods for goods.", "d": 1},
    {"t": "The main disadvantage of barter is:", "o": ["Too much money", "Double coincidence of wants", "Low taxes", "High prices"], "a": 1, "e": "Barter needs a double coincidence of wants.", "d": 1},
    {"t": "Entrepot trade is the:", "o": ["Import of goods for re-export", "Retail trade", "Wholesale trade", "Home trade"], "a": 0, "e": "Entrepot = import for re-export.", "d": 1},
    {"t": "Visible trade refers to trade in:", "o": ["Services", "Tangible goods", "Invisibles", "Tourism"], "a": 1, "e": "Visible trade = goods.", "d": 1},
    {"t": "Invisible trade refers to trade in:", "o": ["Goods", "Services", "Raw materials", "Machinery"], "a": 1, "e": "Invisible trade = services.", "d": 1},

    # ── Purchase & sale ──
    {"t": "A contract of sale is an agreement where:", "o": ["Goods are donated", "Ownership of goods transfers for a price", "Services are free", "Nothing happens"], "a": 1, "e": "A sale transfers ownership for a price.", "d": 1},
    {"t": "The document sent by a buyer to order goods is the:", "o": ["Invoice", "Purchase order", "Receipt", "Bill"], "a": 1, "e": "A purchase order orders goods.", "d": 1},
    {"t": "The document sent by a seller quoting prices is the:", "o": ["Order", "Quotation", "Receipt", "Invoice"], "a": 1, "e": "A quotation states prices.", "d": 1},
    {"t": "A document confirming receipt of goods is the:", "o": ["Invoice", "Delivery note", "Order", "Quotation"], "a": 1, "e": "A delivery note confirms delivery.", "d": 1},
    {"t": "A trade discount is given to:", "o": ["Consumers", "Traders/bulk buyers", "Employees", "Government"], "a": 1, "e": "Trade discounts go to traders.", "d": 1},
    {"t": "A cash discount is given for:", "o": ["Bulk buying", "Prompt payment", "Old customers", "Advertising"], "a": 1, "e": "Cash discounts reward prompt payment.", "d": 1},

    # ── Aids to trade ──
    {"t": "The aids to trade include all EXCEPT:", "o": ["Transport", "Banking", "Insurance", "Production"], "a": 3, "e": "Production is not an aid to trade.", "d": 1},
    {"t": "Banking aids trade by:", "o": ["Transporting goods", "Providing finance and payments", "Insuring goods", "Advertising"], "a": 1, "e": "Banks finance and process payments.", "d": 1},
    {"t": "Insurance aids trade by:", "o": ["Transporting goods", "Spreading risk", "Making goods", "Advertising"], "a": 1, "e": "Insurance spreads risk.", "d": 1},
    {"t": "Transport aids trade by:", "o": ["Making goods", "Moving goods to where needed", "Insuring goods", "Banking"], "a": 1, "e": "Transport moves goods.", "d": 1},
    {"t": "Advertising aids trade by:", "o": ["Producing goods", "Informing consumers about products", "Insuring", "Banking"], "a": 1, "e": "Advertising informs consumers.", "d": 1},
    {"t": "Warehousing aids trade by:", "o": ["Producing goods", "Storing goods", "Insuring", "Advertising"], "a": 1, "e": "Warehousing stores goods.", "d": 1},
    {"t": "Communication aids trade by:", "o": ["Making goods", "Linking buyers and sellers", "Insuring", "Transporting"], "a": 1, "e": "Communication links parties.", "d": 1},
    {"t": "The modes of transport include:", "o": ["Land, air, water", "Road and rail only", "Air and sea only", "Pipeline only"], "a": 0, "e": "Transport modes: land, air, water, pipeline.", "d": 1},
    {"t": "The fastest mode of transport is:", "o": ["Road", "Air", "Sea", "Rail"], "a": 1, "e": "Air transport is fastest.", "d": 1},
    {"t": "The cheapest mode of transport for bulky goods over long sea distances is:", "o": ["Air", "Water (sea)", "Road", "Rail"], "a": 1, "e": "Sea transport is cheapest for bulk.", "d": 1},

    # ── Business units ──
    {"t": "A business owned by one person is a:", "o": ["Partnership", "Sole proprietorship", "Company", "Cooperative"], "a": 1, "e": "A sole proprietorship has one owner.", "d": 1},
    {"t": "A business owned by two to twenty people is a:", "o": ["Sole trader", "Partnership", "Company", "Cooperative"], "a": 1, "e": "A partnership has 2–20 partners.", "d": 1},
    {"t": "A limited liability company has owners called:", "o": ["Partners", "Shareholders", "Sole traders", "Members only"], "a": 1, "e": "Company owners are shareholders.", "d": 1},
    {"t": "A private limited company's name ends with:", "o": ["PLC", "Ltd", "Inc", "Corp"], "a": 1, "e": "Private companies use 'Ltd'.", "d": 1},
    {"t": "A public limited company's name ends with:", "o": ["Ltd", "PLC", "Co", "Inc"], "a": 1, "e": "Public companies use 'PLC'.", "d": 1},
    {"t": "A public limited company can sell shares to the:", "o": ["Public", "Only founders", "Only employees", "No one"], "a": 0, "e": "PLCs sell shares to the public.", "d": 1},
    {"t": "The liability of a sole proprietor is:", "o": ["Limited", "Unlimited", "Zero", "Shared"], "a": 1, "e": "Sole traders have unlimited liability.", "d": 1},
    {"t": "The liability of shareholders in a company is:", "o": ["Unlimited", "Limited to their investment", "Zero", "Shared equally"], "a": 1, "e": "Shareholders' liability is limited.", "d": 1},
    {"t": "A cooperative society is owned and run by:", "o": ["One person", "Its members", "The government", "Shareholders"], "a": 1, "e": "Cooperatives are member-owned.", "d": 1},
    {"t": "A business formed to provide a service to members is a:", "o": ["Sole trader", "Cooperative", "Partnership", "PLC"], "a": 1, "e": "Cooperatives serve members.", "d": 1},
    {"t": "The document that sets out a company's rules is the:", "o": ["Invoice", "Memorandum and Articles of Association", "Receipt", "Bill"], "a": 1, "e": "The Memorandum/Articles set company rules.", "d": 1},
    {"t": "A partnership is governed by a:", "o": ["Deed of partnership", "Invoice", "Receipt", "Cheque"], "a": 0, "e": "A partnership deed governs partners.", "d": 1},
    {"t": "A state-owned enterprise is owned by the:", "o": ["Public", "Government", "Private individuals", "Foreigners"], "a": 1, "e": "State enterprises are government-owned.", "d": 1},
    {"t": "The process of selling a state enterprise to private owners is:", "o": ["Nationalisation", "Privatisation", "Indigenisation", "Commercialisation"], "a": 1, "e": "Privatisation sells to private owners.", "d": 1},
    {"t": "The process of transferring private enterprises to the state is:", "o": ["Privatisation", "Nationalisation", "Liberalisation", "Deregulation"], "a": 1, "e": "Nationalisation transfers to the state.", "d": 1},
    {"t": "A multinational company operates in:", "o": ["One country", "Many countries", "One city", "One state"], "a": 1, "e": "Multinationals operate in many countries.", "d": 1},
    {"t": "A holding company is one that:", "o": ["Produces goods", "Owns shares in other companies", "Only banks", "Only insures"], "a": 1, "e": "A holding company owns other companies' shares.", "d": 1},
    {"t": "A cartel is a group of firms that:", "o": ["Compete", "Agree to control prices/output", "Produce different goods", "Only trade"], "a": 1, "e": "Cartels control prices/output.", "d": 2},
    {"t": "A merger is the:", "o": ["Split of a firm", "Combination of two or more firms", "Bankruptcy", "Sale of assets"], "a": 1, "e": "A merger combines firms.", "d": 1},
    {"t": "The body that registers companies in Nigeria is the:", "o": ["CBN", "Corporate Affairs Commission (CAC)", "NDIC", "FIRS"], "a": 1, "e": "The CAC registers companies.", "d": 1},

    # ── Financing business ──
    {"t": "The capital contributed by the owner to start a business is:", "o": ["Loan", "Owners' capital/equity", "Overdraft", "Grant"], "a": 1, "e": "Owners' capital is initial funding.", "d": 1},
    {"t": "Borrowed capital is also called:", "o": ["Equity", "Loan capital", "Profit", "Revenue"], "a": 1, "e": "Borrowed capital is debt.", "d": 1},
    {"t": "A loan that is repayable over a long period is a:", "o": ["Short-term loan", "Long-term loan", "Overdraft", "Grant"], "a": 1, "e": "Long-term loans span years.", "d": 1},
    {"t": "An overdraft is a facility that allows an account holder to:", "o": ["Earn interest", "Withdraw more than the balance", "Buy shares", "Save money"], "a": 1, "e": "Overdrafts allow over-withdrawal.", "d": 1},
    {"t": "The interest paid on a loan is the:", "o": ["Principal", "Cost of borrowing", "Profit", "Deposit"], "a": 1, "e": "Interest is the cost of borrowing.", "d": 1},
    {"t": "The principal of a loan is the:", "o": ["Interest", "Original amount borrowed", "Profit", "Fee"], "a": 1, "e": "Principal = original sum borrowed.", "d": 1},
    {"t": "Venture capital is funding provided to:", "o": ["Established firms", "New/risky businesses with growth potential", "Government", "Banks"], "a": 1, "e": "Venture capital funds startups.", "d": 1},

    # ── Trade associations ──
    {"t": "A trade association is an organisation of:", "o": ["Consumers", "Firms in the same industry", "Workers", "Government"], "a": 1, "e": "Trade associations unite firms in an industry.", "d": 1},
    {"t": "A chamber of commerce is an association of:", "o": ["Workers", "Businesses in a locality", "Farmers", "Students"], "a": 1, "e": "Chambers of commerce represent local businesses.", "d": 1},
    {"t": "The manufacturers' association of Nigeria is the:", "o": ["NLC", "MAN", "NACCIMA", "CBN"], "a": 1, "e": "MAN = Manufacturers Association of Nigeria.", "d": 1},
    {"t": "NACCIMA represents:", "o": ["Workers", "Chambers of commerce and industry", "Farmers", "Banks"], "a": 1, "e": "NACCIMA = national chamber body.", "d": 1},

    # ── Money ──
    {"t": "The functions of money include all EXCEPT:", "o": ["Medium of exchange", "Store of value", "Unit of account", "Production of goods"], "a": 3, "e": "Money does not produce goods.", "d": 1},
    {"t": "Legal tender is money that:", "o": ["Must be accepted for payment", "Can be refused", "Is foreign", "Is illegal"], "a": 0, "e": "Legal tender must be accepted.", "d": 1},
    {"t": "The coins and notes issued by the central bank are:", "o": ["Deposits", "Currency", "Cheques", "Shares"], "a": 1, "e": "Currency = coins and notes.", "d": 1},
    {"t": "The currency of Nigeria is the:", "o": ["Dollar", "Naira", "Cedi", "Pound"], "a": 1, "e": "Nigeria's currency is the naira.", "d": 1},
    {"t": "The body that issues currency in Nigeria is the:", "o": ["Commercial banks", "Central Bank of Nigeria", "Ministry of Finance", "FIRS"], "a": 1, "e": "The CBN issues currency.", "d": 1},
    {"t": "Bank deposits that can be withdrawn on demand are:", "o": ["Fixed deposits", "Demand deposits", "Shares", "Bonds"], "a": 1, "e": "Demand deposits are withdrawable anytime.", "d": 1},
    {"t": "A fixed deposit account:", "o": ["Allows instant withdrawal", "Locks money for a fixed period", "Is a current account", "Has no interest"], "a": 1, "e": "Fixed deposits lock funds for a term.", "d": 1},
    {"t": "Near money refers to assets:", "o": ["That are cash", "Easily convertible to cash", "That cannot be converted", "That are illegal"], "a": 1, "e": "Near money converts easily to cash.", "d": 2},

    # ── Stock exchange ──
    {"t": "A stock exchange is a market for:", "o": ["Goods", "Shares and securities", "Labour", "Land"], "a": 1, "e": "Stock exchanges trade shares.", "d": 1},
    {"t": "The stock exchange in Nigeria is the:", "o": ["Abuja Stock Exchange", "Nigerian Exchange (NGX)", "Lagos Trade Exchange", "CBN"], "a": 1, "e": "Nigeria's exchange is NGX (formerly NSE).", "d": 1},
    {"t": "A share represents:", "o": ["A loan", "Ownership in a company", "A debt", "A bond"], "a": 1, "e": "Shares represent ownership.", "d": 1},
    {"t": "A person who buys and sells shares for others is a:", "o": ["Banker", "Stockbroker", "Auditor", "Insurer"], "a": 1, "e": "Stockbrokers trade shares.", "d": 1},
    {"t": "The market where new shares are first sold is the:", "o": ["Secondary market", "Primary market", "Black market", "Forex market"], "a": 1, "e": "New issues are in the primary market.", "d": 1},
    {"t": "The market where existing shares are traded is the:", "o": ["Primary market", "Secondary market", "Black market", "Commodity market"], "a": 1, "e": "Existing shares trade on the secondary market.", "d": 1},
    {"t": "The first sale of a company's shares to the public is an:", "o": ["IPO (Initial Public Offering)", "Dividend", "Bond", "Merger"], "a": 0, "e": "An IPO is the first public share sale.", "d": 1},
    {"t": "A dividend is the:", "o": ["Share price", "Profit distributed to shareholders", "Loan", "Tax"], "a": 1, "e": "Dividends distribute profit to shareholders.", "d": 1},
    {"t": "A bond is a:", "o": ["Share", "Debt instrument (loan to a firm/government)", "Dividend", "Stock"], "a": 1, "e": "Bonds are debt instruments.", "d": 1},
    {"t": "A bull market is one where prices are:", "o": ["Falling", "Rising", "Stable", "Zero"], "a": 1, "e": "Bull markets see rising prices.", "d": 1},
    {"t": "A bear market is one where prices are:", "o": ["Rising", "Falling", "Stable", "Zero"], "a": 1, "e": "Bear markets see falling prices.", "d": 1},

    # ── Business management ──
    {"t": "The functions of management include:", "o": ["Planning, organising, directing, controlling", "Buying, selling, banking", "Producing, storing, shipping", "Taxing, spending, saving"], "a": 0, "e": "Management functions: plan, organise, direct, control.", "d": 1},
    {"t": "The first function of management is:", "o": ["Controlling", "Planning", "Staffing", "Directing"], "a": 1, "e": "Planning comes first.", "d": 1},
    {"t": "Planning involves:", "o": ["Checking results", "Setting objectives and strategies", "Hiring staff", "Motivating staff"], "a": 1, "e": "Planning sets objectives.", "d": 1},
    {"t": "Organising involves:", "o": ["Setting goals", "Allocating resources and tasks", "Measuring results", "Rewarding staff"], "a": 1, "e": "Organising allocates resources/tasks.", "d": 1},
    {"t": "Controlling involves:", "o": ["Setting goals", "Monitoring and correcting performance", "Hiring", "Planning"], "a": 1, "e": "Controlling monitors/corrects.", "d": 1},
    {"t": "Directing (leading) involves:", "o": ["Setting goals", "Motivating and guiding staff", "Checking results", "Planning"], "a": 1, "e": "Directing motivates staff.", "d": 1},
    {"t": "Authority is the:", "o": ["Responsibility", "Right to give orders and make decisions", "Task assigned", "Salary"], "a": 1, "e": "Authority = right to decide/command.", "d": 1},
    {"t": "Responsibility is the:", "o": ["Right to command", "Obligation to perform assigned duties", "Salary", "Authority"], "a": 1, "e": "Responsibility = duty to perform.", "d": 1},
    {"t": "Delegation of authority means:", "o": ["Centralising power", "Assigning authority to subordinates", "Removing duties", "Firing staff"], "a": 1, "e": "Delegation passes authority down.", "d": 1},
    {"t": "The chain of command is the:", "o": ["Salary scale", "Line of authority from top to bottom", "List of customers", "Product list"], "a": 1, "e": "Chain of command = authority line.", "d": 1},

    # ── Marketing ──
    {"t": "Marketing is the process of:", "o": ["Only selling", "Identifying and satisfying customer needs profitably", "Only advertising", "Only producing"], "a": 1, "e": "Marketing satisfies customer needs.", "d": 1},
    {"t": "The marketing mix consists of the:", "o": ["4 Ps (Product, Price, Place, Promotion)", "3 Cs", "4 Ms", "5 Ws"], "a": 0, "e": "The 4 Ps form the marketing mix.", "d": 1},
    {"t": "The 'product' in the marketing mix refers to:", "o": ["The price", "The good/service offered", "The place", "The promotion"], "a": 1, "e": "Product = what is offered.", "d": 1},
    {"t": "The 'price' in the marketing mix is the:", "o": ["Cost", "Amount charged for the product", "Profit", "Discount"], "a": 1, "e": "Price = what customers pay.", "d": 1},
    {"t": "The 'place' in the marketing mix refers to:", "o": ["Price", "Distribution channels", "Promotion", "Product"], "a": 1, "e": "Place = distribution.", "d": 1},
    {"t": "The 'promotion' in the marketing mix refers to:", "o": ["Distribution", "Communication with customers", "Price", "Product"], "a": 1, "e": "Promotion communicates with customers.", "d": 1},
    {"t": "A market segment is:", "o": ["A shop", "A subgroup of customers with similar needs", "A product", "A price"], "a": 1, "e": "Segments group similar customers.", "d": 1},
    {"t": "Market segmentation divides the market by:", "o": ["Demographics, geography, behaviour", "Only age", "Only income", "Nothing"], "a": 0, "e": "Segmentation uses demographics etc.", "d": 1},
    {"t": "Advertising is a form of:", "o": ["Distribution", "Promotion", "Production", "Pricing"], "a": 1, "e": "Advertising is promotion.", "d": 1},
    {"t": "Personal selling involves:", "o": ["Mass media ads", "Direct face-to-face selling", "Billboards", "Posters"], "a": 1, "e": "Personal selling is direct.", "d": 1},
    {"t": "Sales promotion includes:", "o": ["Only TV ads", "Discounts, samples and coupons", "Only billboards", "Only radio"], "a": 1, "e": "Sales promotion uses incentives.", "d": 1},
    {"t": "The ultimate goal of marketing is to:", "o": ["Reduce sales", "Satisfy customers and earn profit", "Increase costs", "Store goods"], "a": 1, "e": "Marketing aims for customer satisfaction + profit.", "d": 1},
    {"t": "Consumer goods are goods bought by:", "o": ["Firms", "Final consumers for personal use", "Government only", "Wholesalers only"], "a": 1, "e": "Consumer goods are for personal use.", "d": 1},
    {"t": "Industrial goods are bought by:", "o": ["Consumers", "Firms for production", "Students", "Households"], "a": 1, "e": "Industrial goods serve production.", "d": 1},

    # ── Legal aspects ──
    {"t": "A contract is a:", "o": ["Verbal promise", "Legally binding agreement", "Casual chat", "Receipt"], "a": 1, "e": "A contract is legally binding.", "d": 1},
    {"t": "The essential elements of a valid contract include:", "o": ["Offer, acceptance, consideration", "Price only", "Time only", "Signature only"], "a": 0, "e": "Offer, acceptance, consideration are essential.", "d": 1},
    {"t": "Consideration in a contract is:", "o": ["Kindness", "Something of value exchanged", "A promise only", "A signature"], "a": 1, "e": "Consideration = value exchanged.", "d": 1},
    {"t": "An offer is:", "o": ["Acceptance", "A proposal to enter a contract", "A receipt", "A signature"], "a": 1, "e": "An offer proposes a contract.", "d": 1},
    {"t": "Acceptance is the:", "o": ["Proposal", "Agreement to the terms of an offer", "Receipt", "Delivery"], "a": 1, "e": "Acceptance agrees to the offer.", "d": 1},
    {"t": "The law governing the sale of goods in Nigeria is the:", "o": ["Constitution", "Sale of Goods Act", "Company Act", "Tax Act"], "a": 1, "e": "The Sale of Goods Act governs sales.", "d": 1},
    {"t": "A patent protects:", "o": ["Inventions", "Trade names", "Music", "Books"], "a": 0, "e": "Patents protect inventions.", "d": 1},
    {"t": "A trademark protects:", "o": ["Inventions", "Brand names and logos", "Music", "Books"], "a": 1, "e": "Trademarks protect brands.", "d": 1},
    {"t": "Copyright protects:", "o": ["Inventions", "Literary and artistic works", "Trade names", "Inventions only"], "a": 1, "e": "Copyright protects creative works.", "d": 1},

    # ── ICT in business ──
    {"t": "E-commerce is the:", "o": ["Buying and selling via the internet", "Barter trade", "Retail trade", "Wholesale trade"], "a": 0, "e": "E-commerce is online trading.", "d": 1},
    {"t": "The use of computers to process business data is:", "o": ["Manual processing", "Electronic data processing", "Barter", "Posting"], "a": 1, "e": "EDP processes data electronically.", "d": 1},
    {"t": "An advantage of e-commerce is:", "o": ["No reach", "Global reach and convenience", "Higher costs", "Slower service"], "a": 1, "e": "E-commerce offers global reach.", "d": 1},
    {"t": "The transfer of funds electronically between banks is:", "o": ["Cash payment", "Electronic funds transfer (EFT)", "Barter", "Cheque only"], "a": 1, "e": "EFT moves funds electronically.", "d": 1},
    {"t": "An ATM is used to:", "o": ["Make calls", "Withdraw cash and do transactions", "Post letters", "Store goods"], "a": 1, "e": "ATMs enable banking transactions.", "d": 1},
    {"t": "A POS terminal is used for:", "o": ["Printing", "Card payments at the point of sale", "Transport", "Storage"], "a": 1, "e": "POS terminals process card payments.", "d": 1},
    {"t": "The internet has made trade:", "o": ["Slower", "Faster and more accessible", "Impossible", "More expensive only"], "a": 1, "e": "The internet speeds up trade.", "d": 1},

    # ── More mixed ──
    {"t": "The reward for labour is:", "o": ["Rent", "Wages", "Interest", "Profit"], "a": 1, "e": "Wages reward labour.", "d": 1},
    {"t": "The reward for capital is:", "o": ["Wages", "Interest", "Rent", "Profit"], "a": 1, "e": "Interest rewards capital.", "d": 1},
    {"t": "The reward for enterprise is:", "o": ["Rent", "Profit", "Wages", "Interest"], "a": 1, "e": "Profit rewards the entrepreneur.", "d": 1},
    {"t": "The reward for land is:", "o": ["Wages", "Rent", "Profit", "Interest"], "a": 1, "e": "Rent rewards land.", "d": 1},
    {"t": "A consumer is a person who:", "o": ["Produces goods", "Uses goods and services", "Sells goods", "Transports goods"], "a": 1, "e": "Consumers use goods/services.", "d": 1},
    {"t": "A producer is a person who:", "o": ["Consumes", "Makes goods or provides services", "Buys only", "Sells only"], "a": 1, "e": "Producers make goods/services.", "d": 1},
    {"t": "The person who buys goods in bulk for resale is the:", "o": ["Consumer", "Wholesaler", "Retailer", "Agent"], "a": 1, "e": "Wholesalers buy in bulk.", "d": 1},
    {"t": "The person who acts on behalf of a principal is the:", "o": ["Wholesaler", "Agent", "Retailer", "Consumer"], "a": 1, "e": "Agents act for principals.", "d": 1},
    {"t": "A warehouse is a place for:", "o": ["Selling goods", "Storing goods", "Making goods", "Advertising"], "a": 1, "e": "Warehouses store goods.", "d": 1},
    {"t": "The document used to advertise goods for sale is the:", "o": ["Invoice", "Catalogue", "Receipt", "Cheque"], "a": 1, "e": "Catalogues advertise goods.", "d": 1},
    {"t": "The middleman who does not take ownership of goods is the:", "o": ["Wholesaler", "Agent", "Retailer", "Consumer"], "a": 1, "e": "Agents don't own the goods.", "d": 1},
    {"t": "A superstore is a:", "o": ["Small shop", "Large retail store selling a wide range of goods", "Warehouse", "Market stall"], "a": 1, "e": "Superstores sell many goods.", "d": 1},
    {"t": "A supermarket is a:", "o": ["Wholesaler", "Large self-service retail store", "Warehouse", "Bank"], "a": 1, "e": "Supermarkets are self-service stores.", "d": 1},
    {"t": "A hawker is a:", "o": ["Wholesaler", "Mobile retailer selling on the street", "Manufacturer", "Banker"], "a": 1, "e": "Hawkers sell on the street.", "d": 1},
    {"t": "A franchise is a business arrangement where:", "o": ["One person owns everything", "A franchisee pays to use a franchisor's brand", "The state owns", "No one owns"], "a": 1, "e": "Franchisees license a brand.", "d": 2},
    {"t": "The cost of transporting goods is known as:", "o": ["Insurance", "Freight", "Profit", "Interest"], "a": 1, "e": "Freight is transport cost.", "d": 1},
    {"t": "CIF in foreign trade means:", "o": ["Cost, Insurance, Freight", "Cash in Full", "Cost Including Fee", "Credit Invoice Form"], "a": 0, "e": "CIF = cost, insurance, freight.", "d": 2},
    {"t": "FOB means:", "o": ["Free on Board", "Freight on Buyer", "First Order Basis", "Full Order Billing"], "a": 0, "e": "FOB = free on board.", "d": 2},
    {"t": "A letter of credit is issued by a:", "o": ["Seller", "Bank", "Buyer", "Broker"], "a": 1, "e": "Banks issue letters of credit.", "d": 1},
    {"t": "The document showing the details of goods shipped by sea is the:", "o": ["Invoice", "Bill of lading", "Order", "Quotation"], "a": 1, "e": "Bill of lading details sea cargo.", "d": 1},
    {"t": "The document used to insure goods is the:", "o": ["Invoice", "Insurance policy", "Order", "Receipt"], "a": 1, "e": "An insurance policy insures goods.", "d": 1},
    {"t": "The main aim of a business is to:", "o": ["Lose money", "Make profit", "Avoid tax", "Employ no one"], "a": 1, "e": "Businesses aim for profit.", "d": 1},
    {"t": "The excess of revenue over cost is:", "o": ["Loss", "Profit", "Debt", "Capital"], "a": 1, "e": "Profit = revenue − cost.", "d": 1},
    {"t": "The excess of cost over revenue is:", "o": ["Profit", "Loss", "Capital", "Interest"], "a": 1, "e": "Loss = cost − revenue.", "d": 1},
    {"t": "The goods a business holds for sale are its:", "o": ["Capital", "Stock (inventory)", "Debt", "Revenue"], "a": 1, "e": "Stock = goods held for sale.", "d": 1},
    {"t": "The money owed to a business by customers is:", "o": ["Creditors", "Debtors", "Capital", "Stock"], "a": 1, "e": "Debtors owe the business.", "d": 1},
    {"t": "The money a business owes its suppliers is:", "o": ["Debtors", "Creditors", "Capital", "Stock"], "a": 1, "e": "Creditors are owed by the business.", "d": 1},
    # ── More mixed ──
    {"t": "The assets of a business are its:", "o": ["Debts", "Resources/property owned", "Losses", "Expenses"], "a": 1, "e": "Assets are what a business owns.", "d": 1},
    {"t": "The liabilities of a business are its:", "o": ["Assets", "Debts/obligations", "Profits", "Revenue"], "a": 1, "e": "Liabilities are what it owes.", "d": 1},
    {"t": "Capital employed in a business is:", "o": ["Only cash", "Total resources invested in the business", "Only loans", "Only profit"], "a": 1, "e": "Capital employed = invested resources.", "d": 1},
    {"t": "Working capital is:", "o": ["Fixed assets", "Current assets minus current liabilities", "Long-term loans", "Share capital"], "a": 1, "e": "Working capital = current assets − current liabilities.", "d": 1},
    {"t": "Fixed assets are assets:", "o": ["Held for resale", "Held for long-term use (land, machinery)", "Cash", "Stock"], "a": 1, "e": "Fixed assets are long-term.", "d": 1},
    {"t": "Current assets are assets:", "o": ["Held long-term", "Convertible to cash within a year", "Land", "Buildings"], "a": 1, "e": "Current assets are short-term.", "d": 1},
    {"t": "The ratio of net profit to capital is the:", "o": ["Turnover", "Return on capital", "Liquidity ratio", "Debt ratio"], "a": 1, "e": "Return on capital = profit/capital.", "d": 2},
    {"t": "Turnover (sales) refers to the:", "o": ["Total value of sales", "Total profit", "Total cost", "Stock"], "a": 0, "e": "Turnover = total sales value.", "d": 1},
    {"t": "The margin (mark-up) is the:", "o": ["Cost", "Profit added to cost", "Tax", "Discount"], "a": 1, "e": "Mark-up is profit added to cost.", "d": 1},
    {"t": "The trade of buying and selling within Nigeria is:", "o": ["Foreign trade", "Home/domestic trade", "Entrepot", "Export trade"], "a": 1, "e": "Home trade is within a country.", "d": 1},
    {"t": "The sale of goods by a Nigerian firm to Ghana is:", "o": ["Home trade", "Export trade", "Entrepot", "Retail trade"], "a": 1, "e": "Selling abroad is export trade.", "d": 1},
    {"t": "The purchase of goods from China by a Nigerian firm is:", "o": ["Export trade", "Import trade", "Home trade", "Retail trade"], "a": 1, "e": "Buying from abroad is import trade.", "d": 1},
    {"t": "The price at which a retailer buys from a wholesaler is the:", "o": ["Retail price", "Wholesale price", "List price", "Market price"], "a": 1, "e": "Wholesale price is charged to retailers.", "d": 1},
    {"t": "The price at which a retailer sells to consumers is the:", "o": ["Wholesale price", "Retail price", "Cost price", "Factory price"], "a": 1, "e": "Retail price is charged to consumers.", "d": 1},
    {"t": "The difference between cost price and selling price is the:", "o": ["Loss only", "Profit (or loss)", "Tax", "Discount"], "a": 1, "e": "Profit/loss = selling price − cost price.", "d": 1},
    {"t": "An invoice that also serves as a receipt is a:", "o": ["Pro forma invoice", "Receipted invoice", "Order", "Quotation"], "a": 1, "e": "A receipted invoice confirms payment.", "d": 1},
    {"t": "A pro forma invoice is sent:", "o": ["After payment", "Before delivery to indicate cost", "After delivery", "Never"], "a": 1, "e": "Pro forma precedes delivery.", "d": 1},
    {"t": "The document a buyer sends to correct an overcharge is a:", "o": ["Invoice", "Debit note", "Receipt", "Order"], "a": 1, "e": "A debit note corrects undercharges.", "d": 2},
    {"t": "The document sent to correct an overcharge to a customer is a:", "o": ["Debit note", "Credit note", "Invoice", "Receipt"], "a": 1, "e": "A credit note corrects overcharges.", "d": 1},
    {"t": "The study of how businesses are managed is:", "o": ["Accounting", "Business administration", "Economics", "Law"], "a": 1, "e": "Business administration studies management.", "d": 1},
    {"t": "The person who manages a company on behalf of shareholders is the:", "o": ["Auditor", "Managing Director/CEO", "Shareholder", "Customer"], "a": 1, "e": "The CEO manages the company.", "d": 1},
    {"t": "The owners of a company are the:", "o": ["Employees", "Shareholders", "Customers", "Suppliers"], "a": 1, "e": "Shareholders own the company.", "d": 1},
    {"t": "The board of directors is elected by the:", "o": ["Employees", "Shareholders", "Customers", "Government"], "a": 1, "e": "Shareholders elect the board.", "d": 1},
    {"t": "The annual general meeting (AGM) is attended by:", "o": ["Employees only", "Shareholders", "Customers", "Suppliers"], "a": 1, "e": "Shareholders attend the AGM.", "d": 1},
    {"t": "The document that shows a company's annual financial performance is the:", "o": ["Invoice", "Annual report/accounts", "Receipt", "Order"], "a": 1, "e": "Annual reports show performance.", "d": 1},
    {"t": "A business that is insolvent:", "o": ["Is profitable", "Cannot pay its debts", "Has no assets", "Is new"], "a": 1, "e": "Insolvency = can't pay debts.", "d": 1},
    {"t": "Bankruptcy applies to:", "o": ["Companies", "Individuals", "Governments", "Banks"], "a": 1, "e": "Bankruptcy applies to individuals.", "d": 1},
    {"t": "Liquidation of a company means:", "o": ["Starting up", "Winding up/closure", "Expansion", "Merger"], "a": 1, "e": "Liquidation winds up a company.", "d": 1},
    {"t": "The main objective of consumer protection is to:", "o": ["Protect businesses", "Safeguard consumers' interests", "Increase prices", "Reduce quality"], "a": 1, "e": "Consumer protection safeguards buyers.", "d": 1},
    {"t": "The body that protects consumers in Nigeria is the:", "o": ["CBN", "Federal Competition and Consumer Protection Commission (FCCPC)", "NDIC", "FIRS"], "a": 1, "e": "The FCCPC protects consumers.", "d": 2},
    {"t": "The acronym CAC stands for:", "o": ["Central Accounting Council", "Corporate Affairs Commission", "Commerce and Audit Council", "Company Affairs Committee"], "a": 1, "e": "CAC = Corporate Affairs Commission.", "d": 1},
    {"t": "The main source of funds for a new sole trader is:", "o": ["Share capital", "Owner's personal savings", "Government grant only", "Bonds"], "a": 1, "e": "Sole traders fund from savings.", "d": 1},
    {"t": "The main source of funds for a company is:", "o": ["Personal savings", "Share capital and loans", "Gifts", "Barter"], "a": 1, "e": "Companies raise share capital.", "d": 1},
    {"t": "The government agency that promotes Nigerian exports is the:", "o": ["CBN", "Nigerian Export Promotion Council (NEPC)", "NDIC", "FIRS"], "a": 1, "e": "NEPC promotes exports.", "d": 2},
    {"t": "The process of checking and recording business transactions is:", "o": ["Marketing", "Bookkeeping", "Advertising", "Production"], "a": 1, "e": "Bookkeeping records transactions.", "d": 1},
    {"t": "The main purpose of keeping business records is to:", "o": ["Waste time", "Know the financial position", "Avoid tax only", "Decorate"], "a": 1, "e": "Records reveal financial position.", "d": 1},
]

build("com", "Commerce", QUESTIONS[:200])
