from _common import build

QUESTIONS = [
    # ── Cell structure ──
    {"t": "The basic unit of life is the:", "o": ["Tissue", "Cell", "Organ", "Organism"], "a": 1, "e": "The cell is the basic structural unit of life.", "d": 1},
    {"t": "The organelle known as the powerhouse of the cell is the:", "o": ["Ribosome", "Mitochondrion", "Nucleus", "Golgi body"], "a": 1, "e": "Mitochondria produce ATP (energy).", "d": 1},
    {"t": "The control centre of the cell is the:", "o": ["Cytoplasm", "Nucleus", "Ribosome", "Vacuole"], "a": 1, "e": "The nucleus controls cell activities.", "d": 1},
    {"t": "The site of protein synthesis is the:", "o": ["Mitochondrion", "Ribosome", "Lysosome", "Chloroplast"], "a": 1, "e": "Ribosomes synthesise proteins.", "d": 1},
    {"t": "The organelle that contains chlorophyll and carries out photosynthesis is the:", "o": ["Mitochondrion", "Chloroplast", "Ribosome", "Nucleus"], "a": 1, "e": "Chloroplasts perform photosynthesis.", "d": 1},
    {"t": "Which organelle is found in plant cells but not animal cells?", "o": ["Mitochondrion", "Chloroplast", "Nucleus", "Ribosome"], "a": 1, "e": "Chloroplasts are unique to plant cells.", "d": 1},
    {"t": "The cell wall of plants is mainly made of:", "o": ["Protein", "Cellulose", "Lipid", "Chitin"], "a": 1, "e": "Plant cell walls are cellulose.", "d": 1},
    {"t": "The genetic material of a cell is stored in the:", "o": ["Cytoplasm", "Nucleus", "Vacuole", "Cell membrane"], "a": 1, "e": "DNA is in the nucleus.", "d": 1},
    {"t": "The semi-permeable membrane surrounding the cytoplasm is the:", "o": ["Cell wall", "Cell (plasma) membrane", "Nuclear membrane", "Vacuole"], "a": 1, "e": "The plasma membrane surrounds the cytoplasm.", "d": 1},
    {"t": "The jelly-like substance that fills the cell is the:", "o": ["Nucleoplasm", "Cytoplasm", "Protoplasm only", "Matrix"], "a": 1, "e": "Cytoplasm is the jelly-like cell fluid.", "d": 1},
    {"t": "Which of the following is a prokaryotic organism?", "o": ["Amoeba", "Bacterium", "Euglena", "Paramecium"], "a": 1, "e": "Bacteria lack a true nucleus (prokaryotes).", "d": 1},
    {"t": "Organisms with a true nucleus are called:", "o": ["Prokaryotes", "Eukaryotes", "Viruses", "Prions"], "a": 1, "e": "Eukaryotes have a membrane-bound nucleus.", "d": 1},
    {"t": "The movement of water molecules from high to low concentration through a membrane is:", "o": ["Diffusion", "Osmosis", "Active transport", "Phagocytosis"], "a": 1, "e": "Osmosis is water movement across a membrane.", "d": 1},
    {"t": "The movement of molecules from high to low concentration is:", "o": ["Osmosis", "Diffusion", "Active transport", "Transpiration"], "a": 1, "e": "Diffusion moves molecules down a concentration gradient.", "d": 1},
    {"t": "The movement of substances against a concentration gradient using energy is:", "o": ["Diffusion", "Active transport", "Osmosis", "Plasmolysis"], "a": 1, "e": "Active transport needs energy (ATP).", "d": 1},

    # ── Classification ──
    {"t": "The five kingdoms of classification include all EXCEPT:", "o": ["Monera", "Protista", "Animalia", "Bacteria are in Monera"], "a": 3, "e": "The five kingdoms are Monera, Protista, Fungi, Plantae, Animalia.", "d": 2},
    {"t": "The binomial system of naming organisms uses:", "o": ["Two Latin names", "One name", "Three names", "Common names"], "a": 0, "e": "Binomial nomenclature uses genus + species.", "d": 1},
    {"t": "The scientific name of humans is:", "o": ["Homo erectus", "Homo sapiens", "Homo habilis", "Australopithecus"], "a": 1, "e": "Humans are Homo sapiens.", "d": 1},
    {"t": "The kingdom of organisms that feed by decomposing organic matter is:", "o": ["Plantae", "Fungi", "Animalia", "Monera"], "a": 1, "e": "Fungi are decomposers.", "d": 1},
    {"t": "Viruses are considered non-living because they:", "o": ["Reproduce independently", "Cannot reproduce outside a host", "Have DNA only", "Are too small"], "a": 1, "e": "Viruses need a host cell to reproduce.", "d": 1},
    {"t": "A group of organisms that can interbreed to produce fertile offspring is a:", "o": ["Genus", "Species", "Family", "Order"], "a": 1, "e": "A species can interbreed with fertile offspring.", "d": 1},
    {"t": "The correct order of taxonomic hierarchy (largest to smallest) is:", "o": ["Kingdom, Phylum, Class, Order, Family, Genus, Species", "Species, Genus, Family, Order, Class, Phylum, Kingdom", "Kingdom, Class, Phylum, Order, Family, Genus, Species", "Phylum, Kingdom, Class, Order, Family, Genus, Species"], "a": 0, "e": "Kingdom → Phylum → Class → Order → Family → Genus → Species.", "d": 2},
    {"t": "Mushrooms belong to the kingdom:", "o": ["Plantae", "Fungi", "Protista", "Monera"], "a": 1, "e": "Mushrooms are fungi.", "d": 1},
    {"t": "Which of the following is an example of a protist?", "o": ["Yeast", "Amoeba", "Bacterium", "Mould"], "a": 1, "e": "Amoeba is a protist.", "d": 1},
    {"t": "The study of the classification of organisms is called:", "o": ["Ecology", "Taxonomy", "Genetics", "Anatomy"], "a": 1, "e": "Taxonomy is the science of classification.", "d": 1},

    # ── Nutrition (plants) ──
    {"t": "The process by which green plants make their food is:", "o": ["Respiration", "Photosynthesis", "Transpiration", "Fermentation"], "a": 1, "e": "Plants make glucose by photosynthesis.", "d": 1},
    {"t": "Photosynthesis takes place mainly in the:", "o": ["Root", "Leaf", "Stem only", "Flower"], "a": 1, "e": "Photosynthesis occurs mostly in leaves.", "d": 1},
    {"t": "The raw materials for photosynthesis are:", "o": ["Oxygen and glucose", "Carbon dioxide and water", "Nitrogen and water", "Oxygen and water"], "a": 1, "e": "CO₂ + H₂O → glucose + O₂.", "d": 1},
    {"t": "The gas released as a by-product of photosynthesis is:", "o": ["Carbon dioxide", "Oxygen", "Nitrogen", "Hydrogen"], "a": 1, "e": "Oxygen is released.", "d": 1},
    {"t": "The green pigment that absorbs light for photosynthesis is:", "o": ["Haemoglobin", "Chlorophyll", "Melanin", "Carotene"], "a": 1, "e": "Chlorophyll absorbs light.", "d": 1},
    {"t": "The pores on leaves through which gases are exchanged are called:", "o": ["Lenticels", "Stomata", "Guard cells", "Xylem"], "a": 1, "e": "Stomata allow gas exchange.", "d": 1},
    {"t": "The light-independent stage of photosynthesis is the:", "o": ["Calvin cycle", "Glycolysis", "Krebs cycle", "Electron transport"], "a": 0, "e": "The Calvin cycle fixes CO₂ in the dark stage.", "d": 2},
    {"t": "The stored form of carbohydrate in plants is:", "o": ["Glycogen", "Starch", "Glucose", "Fructose"], "a": 1, "e": "Plants store starch.", "d": 1},
    {"t": "The loss of water vapour from plant leaves is:", "o": ["Guttation", "Transpiration", "Evaporation", "Condensation"], "a": 1, "e": "Transpiration is water loss from leaves.", "d": 1},
    {"t": "The tissue that transports water in plants is the:", "o": ["Phloem", "Xylem", "Cambium", "Epidermis"], "a": 1, "e": "Xylem transports water and minerals.", "d": 1},
    {"t": "The tissue that transports food (sugars) in plants is the:", "o": ["Xylem", "Phloem", "Cambium", "Cortex"], "a": 1, "e": "Phloem transports sugars.", "d": 1},
    {"t": "Autotrophic nutrition means an organism:", "o": ["Feeds on others", "Makes its own food", "Feeds on dead matter", "Is parasitic"], "a": 1, "e": "Autotrophs make their own food.", "d": 1},
    {"t": "Heterotrophic nutrition means an organism:", "o": ["Makes its own food", "Depends on others for food", "Uses light", "Fixes nitrogen"], "a": 1, "e": "Heterotrophs depend on other organisms.", "d": 1},
    {"t": "The type of nutrition where an organism feeds on dead organic matter is:", "o": ["Parasitic", "Saprophytic", "Holozoic", "Symbiotic"], "a": 1, "e": "Saprophytes feed on dead matter.", "d": 1},
    {"t": "An organism that lives on another and harms it is a:", "o": ["Saprophyte", "Parasite", "Symbiont", "Autotroph"], "a": 1, "e": "Parasites harm their hosts.", "d": 1},

    # ── Nutrition (animals) ──
    {"t": "The digestion of food in humans begins in the:", "o": ["Stomach", "Mouth", "Small intestine", "Oesophagus"], "a": 1, "e": "Digestion starts in the mouth (saliva).", "d": 1},
    {"t": "The enzyme in saliva that digests starch is:", "o": ["Pepsin", "Amylase", "Lipase", "Trypsin"], "a": 1, "e": "Salivary amylase breaks down starch.", "d": 1},
    {"t": "The stomach produces which acid?", "o": ["Sulphuric acid", "Hydrochloric acid", "Nitric acid", "Acetic acid"], "a": 1, "e": "The stomach secretes HCl.", "d": 1},
    {"t": "The enzyme pepsin digests:", "o": ["Starch", "Proteins", "Fats", "Sugars"], "a": 1, "e": "Pepsin digests proteins.", "d": 1},
    {"t": "Bile is produced by the:", "o": ["Pancreas", "Liver", "Stomach", "Gall bladder"], "a": 1, "e": "Bile is produced by the liver.", "d": 1},
    {"t": "Bile is stored in the:", "o": ["Liver", "Gall bladder", "Pancreas", "Stomach"], "a": 1, "e": "Bile is stored in the gall bladder.", "d": 1},
    {"t": "Bile aids in the digestion of:", "o": ["Proteins", "Fats", "Carbohydrates", "Vitamins"], "a": 1, "e": "Bile emulsifies fats.", "d": 1},
    {"t": "The main site of absorption of digested food is the:", "o": ["Stomach", "Small intestine", "Large intestine", "Oesophagus"], "a": 1, "e": "Most absorption occurs in the small intestine.", "d": 1},
    {"t": "The finger-like projections that increase absorption in the small intestine are:", "o": ["Villi", "Cilia", "Alveoli", "Nephrons"], "a": 0, "e": "Villi increase surface area for absorption.", "d": 1},
    {"t": "The end products of carbohydrate digestion are:", "o": ["Amino acids", "Simple sugars (glucose)", "Fatty acids", "Glycerol"], "a": 1, "e": "Carbohydrates → simple sugars.", "d": 1},
    {"t": "The end products of protein digestion are:", "o": ["Glucose", "Amino acids", "Fatty acids", "Glycerol"], "a": 1, "e": "Proteins → amino acids.", "d": 1},
    {"t": "The end products of fat digestion are:", "o": ["Glucose", "Fatty acids and glycerol", "Amino acids", "Sugars"], "a": 1, "e": "Fats → fatty acids + glycerol.", "d": 1},
    {"t": "Which of the following is a vitamin deficiency disease?", "o": ["Malaria", "Scurvy", "Typhoid", "Cholera"], "a": 1, "e": "Scurvy is due to vitamin C deficiency.", "d": 1},
    {"t": "A diet lacking in iodine leads to:", "o": ["Anaemia", "Goitre", "Rickets", "Beriberi"], "a": 1, "e": "Iodine deficiency causes goitre.", "d": 1},
    {"t": "Vitamin D deficiency in children causes:", "o": ["Scurvy", "Rickets", "Night blindness", "Pellagra"], "a": 1, "e": "Rickets results from vitamin D deficiency.", "d": 1},

    # ── Transport ──
    {"t": "The fluid that transports oxygen in the blood is:", "o": ["Plasma", "Haemoglobin in red blood cells", "White blood cells", "Platelets"], "a": 1, "e": "Haemoglobin in RBCs carries oxygen.", "d": 1},
    {"t": "The pigment that gives red blood cells their colour and carries oxygen is:", "o": ["Chlorophyll", "Haemoglobin", "Melanin", "Carotene"], "a": 1, "e": "Haemoglobin carries oxygen.", "d": 1},
    {"t": "The blood cells responsible for fighting infection are:", "o": ["Red blood cells", "White blood cells", "Platelets", "Plasma"], "a": 1, "e": "White blood cells fight infection.", "d": 1},
    {"t": "The blood cells responsible for clotting are:", "o": ["Red blood cells", "White blood cells", "Platelets", "Plasma"], "a": 2, "e": "Platelets help blood clotting.", "d": 1},
    {"t": "The liquid part of blood is:", "o": ["Serum", "Plasma", "Lymph", "Water only"], "a": 1, "e": "Plasma is the liquid component of blood.", "d": 1},
    {"t": "The heart is divided into how many chambers?", "o": ["2", "4", "3", "1"], "a": 1, "e": "The human heart has four chambers.", "d": 1},
    {"t": "The blood vessel that carries blood away from the heart is the:", "o": ["Vein", "Artery", "Capillary", "Venule"], "a": 1, "e": "Arteries carry blood from the heart.", "d": 1},
    {"t": "The blood vessel that carries blood toward the heart is the:", "o": ["Artery", "Vein", "Capillary", "Arteriole"], "a": 1, "e": "Veins carry blood to the heart.", "d": 1},
    {"t": "The artery that carries deoxygenated blood is the:", "o": ["Aorta", "Pulmonary artery", "Carotid", "Coronary"], "a": 1, "e": "The pulmonary artery carries deoxygenated blood to the lungs.", "d": 2},
    {"t": "The vein that carries oxygenated blood is the:", "o": ["Vena cava", "Pulmonary vein", "Jugular", "Hepatic vein"], "a": 1, "e": "The pulmonary vein returns oxygenated blood.", "d": 2},

    # ── Respiration ──
    {"t": "The site of gas exchange in the lungs is the:", "o": ["Bronchi", "Alveoli", "Trachea", "Bronchioles"], "a": 1, "e": "Gas exchange occurs in the alveoli.", "d": 1},
    {"t": "The process of breaking down glucose to release energy is:", "o": ["Photosynthesis", "Respiration", "Transpiration", "Digestion"], "a": 1, "e": "Respiration releases energy from glucose.", "d": 1},
    {"t": "The type of respiration that requires oxygen is:", "o": ["Anaerobic", "Aerobic", "Fermentation", "Glycolysis"], "a": 1, "e": "Aerobic respiration uses oxygen.", "d": 1},
    {"t": "Respiration that does not require oxygen is:", "o": ["Aerobic", "Anaerobic", "Oxidative", "Cellular"], "a": 1, "e": "Anaerobic respiration needs no oxygen.", "d": 1},
    {"t": "The end product of anaerobic respiration in animals is:", "o": ["Ethanol", "Lactic acid", "Water", "Glucose"], "a": 1, "e": "Animal anaerobic respiration forms lactic acid.", "d": 1},
    {"t": "The end product of anaerobic respiration in yeast is:", "o": ["Lactic acid", "Ethanol and CO₂", "Water", "Oxygen"], "a": 1, "e": "Yeast fermentation produces ethanol and CO₂.", "d": 1},
    {"t": "The organelle where aerobic respiration occurs is the:", "o": ["Ribosome", "Mitochondrion", "Nucleus", "Chloroplast"], "a": 1, "e": "Aerobic respiration occurs in mitochondria.", "d": 1},
    {"t": "The first stage of respiration (glucose splitting) is:", "o": ["Krebs cycle", "Glycolysis", "Electron transport", "Calvin cycle"], "a": 1, "e": "Glycolysis splits glucose into pyruvate.", "d": 2},
    {"t": "The gas breathed in during respiration is:", "o": ["Carbon dioxide", "Oxygen", "Nitrogen", "Hydrogen"], "a": 1, "e": "Oxygen is inhaled for respiration.", "d": 1},
    {"t": "The gas breathed out during respiration is:", "o": ["Oxygen", "Carbon dioxide", "Nitrogen", "Helium"], "a": 1, "e": "CO₂ is exhaled.", "d": 1},

    # ── Excretion ──
    {"t": "The functional unit of the kidney is the:", "o": ["Neuron", "Nephron", "Alveolus", "Villus"], "a": 1, "e": "The nephron is the kidney's functional unit.", "d": 1},
    {"t": "The organs that excrete urine are the:", "o": ["Lungs", "Kidneys", "Skin", "Liver"], "a": 1, "e": "Kidneys excrete urine.", "d": 1},
    {"t": "The main nitrogenous waste excreted by humans is:", "o": ["Uric acid", "Urea", "Ammonia", "Creatinine only"], "a": 1, "e": "Humans excrete urea.", "d": 1},
    {"t": "The process of removing metabolic waste from the body is:", "o": ["Egestion", "Excretion", "Secretion", "Digestion"], "a": 1, "e": "Excretion removes metabolic wastes.", "d": 1},
    {"t": "The lungs excrete which waste product?", "o": ["Urea", "Carbon dioxide", "Uric acid", "Salts"], "a": 1, "e": "The lungs excrete CO₂.", "d": 1},
    {"t": "The skin excretes waste through:", "o": ["Urine", "Sweat", "Faeces", "Saliva"], "a": 1, "e": "The skin excretes via sweat glands.", "d": 1},
    {"t": "The organ that filters blood to form urine is the:", "o": ["Liver", "Kidney", "Spleen", "Pancreas"], "a": 1, "e": "The kidneys filter blood.", "d": 1},
    {"t": "The tube that carries urine from the kidney to the bladder is the:", "o": ["Urethra", "Ureter", "Nephron", "Renal vein"], "a": 1, "e": "The ureter carries urine to the bladder.", "d": 1},
    {"t": "The tube that carries urine out of the body is the:", "o": ["Ureter", "Urethra", "Bladder", "Renal artery"], "a": 1, "e": "The urethra carries urine out.", "d": 1},

    # ── Support & movement ──
    {"t": "The skeleton of humans provides:", "o": ["Only movement", "Support, protection and movement", "Only protection", "Only storage"], "a": 1, "e": "The skeleton supports, protects and enables movement.", "d": 1},
    {"t": "The bones are connected to each other at:", "o": ["Muscles", "Joints", "Tendons", "Ligaments"], "a": 1, "e": "Bones meet at joints.", "d": 1},
    {"t": "The tissue that connects muscle to bone is:", "o": ["Ligament", "Tendon", "Cartilage", "Skin"], "a": 1, "e": "Tendons connect muscle to bone.", "d": 1},
    {"t": "The tissue that connects bone to bone is:", "o": ["Tendon", "Ligament", "Cartilage", "Muscle"], "a": 1, "e": "Ligaments connect bones.", "d": 1},
    {"t": "The bones that protect the heart and lungs form the:", "o": ["Skull", "Rib cage", "Pelvis", "Spine"], "a": 1, "e": "The rib cage protects the heart and lungs.", "d": 1},
    {"t": "The skull protects the:", "o": ["Heart", "Brain", "Lungs", "Stomach"], "a": 1, "e": "The skull protects the brain.", "d": 1},
    {"t": "Muscles work by:", "o": ["Pushing", "Contraction and relaxation", "Stretching only", "Vibrating"], "a": 1, "e": "Muscles contract and relax to move.", "d": 1},
    {"t": "The longest bone in the human body is the:", "o": ["Humerus", "Femur", "Tibia", "Radius"], "a": 1, "e": "The femur (thigh bone) is the longest.", "d": 1},
    {"t": "Plants support themselves mainly through:", "o": ["Bones", "Turgor pressure and woody tissue", "Muscles", "Cartilage"], "a": 1, "e": "Plants use turgidity and lignified tissue.", "d": 2},

    # ── Reproduction ──
    {"t": "The male gamete in humans is the:", "o": ["Egg", "Sperm", "Ovum", "Zygote"], "a": 1, "e": "Sperm is the male gamete.", "d": 1},
    {"t": "The female gamete in humans is the:", "o": ["Sperm", "Ovum (egg)", "Zygote", "Gamete"], "a": 1, "e": "The ovum is the female gamete.", "d": 1},
    {"t": "The fusion of male and female gametes is called:", "o": ["Pollination", "Fertilisation", "Germination", "Implantation"], "a": 1, "e": "Fertilisation fuses gametes to form a zygote.", "d": 1},
    {"t": "The fertilised egg is called a:", "o": ["Gamete", "Zygote", "Embryo", "Foetus"], "a": 1, "e": "The zygote is the fertilised egg.", "d": 1},
    {"t": "The male reproductive organ that produces sperm is the:", "o": ["Penis", "Testis", "Ovary", "Prostate"], "a": 1, "e": "Testes produce sperm.", "d": 1},
    {"t": "The female reproductive organ that produces eggs is the:", "o": ["Uterus", "Ovary", "Vagina", "Fallopian tube"], "a": 1, "e": "Ovaries produce ova.", "d": 1},
    {"t": "In plants, the transfer of pollen to the stigma is:", "o": ["Fertilisation", "Pollination", "Germination", "Dispersal"], "a": 1, "e": "Pollination transfers pollen to the stigma.", "d": 1},
    {"t": "The male reproductive part of a flower is the:", "o": ["Pistil", "Stamen", "Stigma", "Ovary"], "a": 1, "e": "The stamen is the male part.", "d": 1},
    {"t": "The female reproductive part of a flower is the:", "o": ["Stamen", "Pistil (carpel)", "Anther", "Filament"], "a": 1, "e": "The pistil is the female part.", "d": 1},
    {"t": "Asexual reproduction produces offspring that are:", "o": ["Genetically different", "Genetically identical to the parent", "Always seeds", "Always male"], "a": 1, "e": "Asexual reproduction gives clones.", "d": 1},
    {"t": "Binary fission is a form of asexual reproduction in:", "o": ["Humans", "Bacteria", "Flowers", "Birds"], "a": 1, "e": "Bacteria reproduce by binary fission.", "d": 1},
    {"t": "Budding is a form of asexual reproduction found in:", "o": ["Amoeba", "Yeast", "Humans", "Ferns"], "a": 1, "e": "Yeast reproduces by budding.", "d": 1},
    {"t": "The structure that develops into a new plant in a seed is the:", "o": ["Cotyledon", "Embryo", "Testa", "Endosperm"], "a": 1, "e": "The embryo develops into the new plant.", "d": 1},
    {"t": "The protective outer coat of a seed is the:", "o": ["Embryo", "Testa", "Cotyledon", "Plumule"], "a": 1, "e": "The testa is the seed coat.", "d": 1},
    {"t": "The process by which a seed begins to grow is:", "o": ["Pollination", "Germination", "Fertilisation", "Dispersal"], "a": 1, "e": "Germination is the start of seed growth.", "d": 1},

    # ── Growth & coordination ──
    {"t": "Growth in living organisms involves an increase in:", "o": ["Only cell size", "Cell number and size", "Only weight", "Only height"], "a": 1, "e": "Growth = increase in cell number/size.", "d": 1},
    {"t": "The growth of a plant toward light is called:", "o": ["Geotropism", "Phototropism", "Hydrotropism", "Chemotropism"], "a": 1, "e": "Phototropism is growth toward light.", "d": 1},
    {"t": "The growth of a plant root toward gravity is:", "o": ["Phototropism", "Geotropism", "Thigmotropism", "Hydrotropism"], "a": 1, "e": "Geotropism is growth in response to gravity.", "d": 1},
    {"t": "The growth of a plant toward water is:", "o": ["Phototropism", "Hydrotropism", "Geotropism", "Nastic movement"], "a": 1, "e": "Hydrotropism is growth toward water.", "d": 1},
    {"t": "The plant hormone that promotes growth is:", "o": ["Insulin", "Auxin", "Adrenaline", "Thyroxine"], "a": 1, "e": "Auxins promote plant growth.", "d": 1},
    {"t": "The nervous system is made up of the brain, spinal cord and:", "o": ["Bones", "Nerves", "Muscles", "Glands"], "a": 1, "e": "Nerves connect the CNS to the body.", "d": 1},
    {"t": "The basic functional unit of the nervous system is the:", "o": ["Nephron", "Neuron", "Alveolus", "Villus"], "a": 1, "e": "The neuron is the nerve cell.", "d": 1},
    {"t": "The brain and spinal cord make up the:", "o": ["Peripheral nervous system", "Central nervous system", "Autonomic system", "Somatic system"], "a": 1, "e": "The CNS = brain + spinal cord.", "d": 1},
    {"t": "The hormone that regulates blood sugar level is:", "o": ["Thyroxine", "Insulin", "Adrenaline", "Oestrogen"], "a": 1, "e": "Insulin regulates blood glucose.", "d": 1},
    {"t": "The gland that secretes insulin is the:", "o": ["Thyroid", "Pancreas", "Adrenal", "Pituitary"], "a": 1, "e": "The pancreas secretes insulin.", "d": 1},

    # ── Ecology ──
    {"t": "The study of the relationship between organisms and their environment is:", "o": ["Genetics", "Ecology", "Anatomy", "Taxonomy"], "a": 1, "e": "Ecology studies organism-environment relationships.", "d": 1},
    {"t": "A group of organisms of the same species in an area is a:", "o": ["Community", "Population", "Ecosystem", "Biome"], "a": 1, "e": "A population is one species in an area.", "d": 1},
    {"t": "All the populations in an area form a:", "o": ["Population", "Community", "Biosphere", "Habitat"], "a": 1, "e": "A community is all populations together.", "d": 1},
    {"t": "The place where an organism lives is its:", "o": ["Niche", "Habitat", "Community", "Ecosystem"], "a": 1, "e": "A habitat is where an organism lives.", "d": 1},
    {"t": "The role of an organism in its ecosystem is its:", "o": ["Habitat", "Niche", "Population", "Biome"], "a": 1, "e": "A niche is the organism's role.", "d": 1},
    {"t": "A community of organisms interacting with their physical environment is an:", "o": ["Population", "Ecosystem", "Species", "Genus"], "a": 1, "e": "An ecosystem includes living + non-living parts.", "d": 1},
    {"t": "Organisms that produce their own food are called:", "o": ["Consumers", "Producers", "Decomposers", "Herbivores"], "a": 1, "e": "Producers (plants) make food.", "d": 1},
    {"t": "Organisms that feed on producers are called:", "o": ["Decomposers", "Primary consumers", "Secondary consumers", "Producers"], "a": 1, "e": "Primary consumers (herbivores) eat producers.", "d": 1},
    {"t": "Organisms that break down dead matter are:", "o": ["Producers", "Decomposers", "Herbivores", "Carnivores"], "a": 1, "e": "Decomposers recycle nutrients.", "d": 1},
    {"t": "The sequence of organisms through which energy flows is a:", "o": ["Food web", "Food chain", "Trophic level", "Biomass"], "a": 1, "e": "A food chain shows energy flow.", "d": 1},
    {"t": "The interconnected food chains in an ecosystem form a:", "o": ["Food chain", "Food web", "Pyramid", "Cycle"], "a": 1, "e": "A food web links many chains.", "d": 1},
    {"t": "The ultimate source of energy for most ecosystems is the:", "o": ["Moon", "Sun", "Wind", "Water"], "a": 1, "e": "The sun powers photosynthesis.", "d": 1},
    {"t": "A relationship where both organisms benefit is:", "o": ["Parasitism", "Mutualism", "Commensalism", "Competition"], "a": 1, "e": "Mutualism benefits both organisms.", "d": 1},
    {"t": "A relationship where one benefits and the other is unaffected is:", "o": ["Mutualism", "Commensalism", "Parasitism", "Predation"], "a": 1, "e": "Commensalism benefits one, neutral to the other.", "d": 1},
    {"t": "A relationship where one benefits and the other is harmed is:", "o": ["Commensalism", "Parasitism", "Mutualism", "Saprophytism"], "a": 1, "e": "Parasitism harms the host.", "d": 1},

    # ── Genetics & heredity ──
    {"t": "The study of heredity and variation is:", "o": ["Ecology", "Genetics", "Taxonomy", "Embryology"], "a": 1, "e": "Genetics studies heredity.", "d": 1},
    {"t": "The basic unit of heredity is the:", "o": ["Chromosome", "Gene", "Nucleus", "Cell"], "a": 1, "e": "The gene is the unit of heredity.", "d": 1},
    {"t": "Genes are located on:", "o": ["Ribosomes", "Chromosomes", "Mitochondria", "Vacuoles"], "a": 1, "e": "Genes are on chromosomes.", "d": 1},
    {"t": "The father of genetics is:", "o": ["Darwin", "Gregor Mendel", "Watson", "Lamarck"], "a": 1, "e": "Mendel founded genetics.", "d": 1},
    {"t": "The number of chromosomes in a normal human body cell is:", "o": ["23", "46", "44", "48"], "a": 1, "e": "Humans have 46 chromosomes (23 pairs).", "d": 1},
    {"t": "The number of chromosomes in a human gamete is:", "o": ["46", "23", "44", "48"], "a": 1, "e": "Gametes have 23 chromosomes (haploid).", "d": 1},
    {"t": "The sex chromosomes in a human female are:", "o": ["XY", "XX", "YY", "XZ"], "a": 1, "e": "Females are XX.", "d": 1},
    {"t": "The sex chromosomes in a human male are:", "o": ["XX", "XY", "YY", "XZ"], "a": 1, "e": "Males are XY.", "d": 1},
    {"t": "An allele that masks another is said to be:", "o": ["Recessive", "Dominant", "Lethal", "Mutant"], "a": 1, "e": "A dominant allele masks the recessive.", "d": 1},
    {"t": "An allele that is masked is:", "o": ["Dominant", "Recessive", "Lethal", "Mutant"], "a": 1, "e": "A recessive allele is masked by a dominant one.", "d": 1},
    {"t": "The physical appearance of an organism is its:", "o": ["Genotype", "Phenotype", "Karyotype", "Genome"], "a": 1, "e": "Phenotype is observable traits.", "d": 1},
    {"t": "The genetic makeup of an organism is its:", "o": ["Phenotype", "Genotype", "Karyotype", "Genome"], "a": 1, "e": "Genotype is the genetic constitution.", "d": 1},
    {"t": "Having two identical alleles for a trait is:", "o": ["Heterozygous", "Homozygous", "Diploid", "Haploid"], "a": 1, "e": "Homozygous = same alleles.", "d": 1},
    {"t": "Having two different alleles for a trait is:", "o": ["Homozygous", "Heterozygous", "Diploid", "Haploid"], "a": 1, "e": "Heterozygous = different alleles.", "d": 1},
    {"t": "The process by which DNA makes a copy of itself is:", "o": ["Transcription", "Replication", "Translation", "Mutation"], "a": 1, "e": "DNA replication copies DNA.", "d": 1},
    {"t": "A sudden change in the genetic material is a:", "o": ["Variation", "Mutation", "Replication", "Transcription"], "a": 1, "e": "A mutation is a change in DNA.", "d": 1},
    {"t": "The structure of DNA was described by:", "o": ["Mendel", "Watson and Crick", "Darwin", "Lamarck"], "a": 1, "e": "Watson and Crick described DNA's double helix.", "d": 1},
    {"t": "DNA stands for:", "o": ["Deoxyribonucleic acid", "Ribonucleic acid", "Dinucleotide acid", "Dinitrogen acid"], "a": 0, "e": "DNA = deoxyribonucleic acid.", "d": 1},

    # ── Evolution & microorganisms ──
    {"t": "The theory of evolution by natural selection was proposed by:", "o": ["Mendel", "Charles Darwin", "Watson", "Lamarck"], "a": 1, "e": "Darwin proposed natural selection.", "d": 1},
    {"t": "Natural selection is based on:", "o": ["Artificial breeding", "Survival of the fittest", "Random chance only", "Mutation only"], "a": 1, "e": "The fittest survive and reproduce.", "d": 1},
    {"t": "The theory of use and disuse of organs was proposed by:", "o": ["Darwin", "Lamarck", "Mendel", "Wallace"], "a": 1, "e": "Lamarck proposed use/disuse inheritance.", "d": 1},
    {"t": "Which of the following is a microorganism?", "o": ["Earthworm", "Bacterium", "Frog", "Fern"], "a": 1, "e": "Bacteria are microorganisms.", "d": 1},
    {"t": "Diseases caused by microorganisms include:", "o": ["Malaria", "Rickets", "Scurvy", "Goitre"], "a": 0, "e": "Malaria is caused by Plasmodium.", "d": 1},
    {"t": "Malaria is caused by:", "o": ["Bacteria", "Plasmodium (protozoan)", "Virus", "Fungus"], "a": 1, "e": "Plasmodium causes malaria.", "d": 1},
    {"t": "Malaria is transmitted by:", "o": ["Tsetse fly", "Female Anopheles mosquito", "Housefly", "Tick"], "a": 1, "e": "Female Anopheles mosquito transmits malaria.", "d": 1},
    {"t": "The vector of sleeping sickness is the:", "o": ["Mosquito", "Tsetse fly", "Housefly", "Flea"], "a": 1, "e": "The tsetse fly transmits trypanosomiasis.", "d": 1},
    {"t": "The pathogen that causes cholera is a:", "o": ["Virus", "Bacterium (Vibrio)", "Protozoan", "Fungus"], "a": 1, "e": "Vibrio cholerae causes cholera.", "d": 1},
    {"t": "Immunity acquired after vaccination is:", "o": ["Natural passive", "Artificial active", "Natural active", "Innate"], "a": 1, "e": "Vaccination gives artificial active immunity.", "d": 2},
    {"t": "The process of heating food to kill microorganisms is:", "o": ["Fermentation", "Pasteurisation", "Distillation", "Filtration"], "a": 1, "e": "Pasteurisation kills microbes by heating.", "d": 1},
    {"t": "The scientist who developed the first vaccine was:", "o": ["Darwin", "Edward Jenner", "Mendel", "Pasteur only"], "a": 1, "e": "Edward Jenner developed the smallpox vaccine.", "d": 1},
    {"t": "The conversion of glucose to ethanol by yeast is:", "o": ["Photosynthesis", "Fermentation", "Respiration", "Digestion"], "a": 1, "e": "Yeast ferments sugar to ethanol.", "d": 1},
    {"t": "The process by which bacteria convert ammonia to nitrates is:", "o": ["Denitrification", "Nitrification", "Nitrogen fixation", "Ammonification"], "a": 1, "e": "Nitrification converts ammonia to nitrates.", "d": 1},
    {"t": "The conversion of atmospheric nitrogen to nitrates is:", "o": ["Nitrification", "Nitrogen fixation", "Denitrification", "Ammonification"], "a": 1, "e": "Nitrogen fixation converts N₂ to usable forms.", "d": 1},
    {"t": "The bacteria that fix nitrogen in legume root nodules are:", "o": ["Lactobacillus", "Rhizobium", "Vibrio", "Bacillus"], "a": 1, "e": "Rhizobium fixes nitrogen in legumes.", "d": 1},
    {"t": "The main source of energy for the human body is:", "o": ["Proteins", "Carbohydrates", "Vitamins", "Minerals"], "a": 1, "e": "Carbohydrates are the primary energy source.", "d": 1},
    {"t": "The nutrient that builds and repairs body tissues is:", "o": ["Carbohydrate", "Protein", "Fat", "Vitamin"], "a": 1, "e": "Proteins build and repair tissues.", "d": 1},
    {"t": "The nutrient that stores energy and insulates the body is:", "o": ["Protein", "Fat", "Carbohydrate", "Vitamin"], "a": 1, "e": "Fats store energy and insulate.", "d": 1},
    {"t": "Which of the following is a trace element needed by the body?", "o": ["Carbon", "Iron", "Hydrogen", "Oxygen"], "a": 1, "e": "Iron is a trace element (in haemoglobin).", "d": 2},
    # ── More: systems & ecology ──
    {"t": "The blood group known as the universal donor is:", "o": ["A", "B", "AB", "O"], "a": 3, "e": "Group O can donate to all groups.", "d": 2},
    {"t": "The blood group known as the universal recipient is:", "o": ["O", "AB", "A", "B"], "a": 1, "e": "Group AB can receive from all.", "d": 2},
    {"t": "The Rhesus factor is a protein on the surface of:", "o": ["White blood cells", "Red blood cells", "Platelets", "Plasma"], "a": 1, "e": "Rh factor is on red blood cells.", "d": 2},
    {"t": "The normal human heart rate at rest is about:", "o": ["72 beats/min", "120 beats/min", "20 beats/min", "150 beats/min"], "a": 0, "e": "Resting heart rate ≈ 72 bpm.", "d": 1},
    {"t": "The chamber of the heart that pumps blood to the body is the:", "o": ["Right atrium", "Left ventricle", "Right ventricle", "Left atrium"], "a": 1, "e": "The left ventricle pumps to the body.", "d": 2},
    {"t": "The valve between the left atrium and left ventricle is the:", "o": ["Tricuspid", "Bicuspid (mitral)", "Pulmonary", "Aortic"], "a": 1, "e": "The bicuspid/mitral valve separates them.", "d": 2},
    {"t": "The gas that turns limewater milky is:", "o": ["Oxygen", "Carbon dioxide", "Nitrogen", "Hydrogen"], "a": 1, "e": "CO₂ turns limewater milky.", "d": 1},
    {"t": "The process of breathing in is called:", "o": ["Expiration", "Inspiration", "Respiration", "Excretion"], "a": 1, "e": "Inspiration is inhaling.", "d": 1},
    {"t": "The process of breathing out is called:", "o": ["Inspiration", "Expiration", "Respiration", "Ventilation"], "a": 1, "e": "Expiration is exhaling.", "d": 1},
    {"t": "The muscle that separates the chest from the abdomen and aids breathing is the:", "o": ["Intercostal muscle", "Diaphragm", "Abdominal muscle", "Trachea"], "a": 1, "e": "The diaphragm aids breathing.", "d": 1},
    {"t": "The windpipe is scientifically called the:", "o": ["Oesophagus", "Trachea", "Bronchus", "Larynx"], "a": 1, "e": "The trachea is the windpipe.", "d": 1},
    {"t": "The voice box is the:", "o": ["Pharynx", "Larynx", "Trachea", "Bronchus"], "a": 1, "e": "The larynx is the voice box.", "d": 1},
    {"t": "The largest organ of the human body is the:", "o": ["Liver", "Skin", "Lung", "Brain"], "a": 1, "e": "The skin is the largest organ.", "d": 1},
    {"t": "The largest gland in the human body is the:", "o": ["Pancreas", "Liver", "Thyroid", "Salivary gland"], "a": 1, "e": "The liver is the largest gland.", "d": 1},
    {"t": "The smallest bone in the human body is in the:", "o": ["Hand", "Ear", "Foot", "Skull"], "a": 1, "e": "The stapes in the ear is smallest.", "d": 2},
    {"t": "The number of bones in an adult human is about:", "o": ["206", "300", "150", "250"], "a": 0, "e": "Adults have about 206 bones.", "d": 1},
    {"t": "The tissue that conducts impulses is the:", "o": ["Muscle tissue", "Nervous tissue", "Epithelial tissue", "Connective tissue"], "a": 1, "e": "Nervous tissue conducts impulses.", "d": 1},
    {"t": "Which of the following is an example of connective tissue?", "o": ["Skin", "Blood", "Muscle", "Nerve"], "a": 1, "e": "Blood is a connective tissue.", "d": 2},
    {"t": "The process by which green plants lose water through stomata is:", "o": ["Transpiration", "Respiration", "Guttation", "Osmosis"], "a": 0, "e": "Transpiration loses water via stomata.", "d": 1},
    {"t": "The carbohydrate stored in animal muscle and liver is:", "o": ["Starch", "Glycogen", "Glucose", "Cellulose"], "a": 1, "e": "Animals store glycogen.", "d": 1},
    {"t": "The vitamin needed for blood clotting is:", "o": ["Vitamin A", "Vitamin K", "Vitamin C", "Vitamin B"], "a": 1, "e": "Vitamin K aids clotting.", "d": 2},
    {"t": "Night blindness is caused by deficiency of:", "o": ["Vitamin A", "Vitamin B", "Vitamin C", "Vitamin D"], "a": 0, "e": "Vitamin A deficiency causes night blindness.", "d": 2},
    {"t": "The disease caused by vitamin B₁ deficiency is:", "o": ["Scurvy", "Beriberi", "Rickets", "Pellagra"], "a": 1, "e": "Beriberi is from vitamin B₁ deficiency.", "d": 2},
    {"t": "The process by which excess amino acids are broken down in the liver is:", "o": ["Digestion", "Deamination", "Glycolysis", "Oxidation"], "a": 1, "e": "Deamination removes amino groups in the liver.", "d": 2},
    {"t": "The organ that detoxifies harmful substances in the body is the:", "o": ["Kidney", "Liver", "Spleen", "Lung"], "a": 1, "e": "The liver detoxifies substances.", "d": 1},
    {"t": "The scientist who disproved spontaneous generation was:", "o": ["Darwin", "Louis Pasteur", "Mendel", "Jenner"], "a": 1, "e": "Pasteur disproved spontaneous generation.", "d": 2},
    {"t": "The theory that living things arise only from living things is:", "o": ["Spontaneous generation", "Biogenesis", "Evolution", "Natural selection"], "a": 1, "e": "Biogenesis = life from life.", "d": 1},
    {"t": "The branch of biology that studies insects is:", "o": ["Ornithology", "Entomology", "Ichthyology", "Botany"], "a": 1, "e": "Entomology studies insects.", "d": 1},
    {"t": "The branch of biology that studies birds is:", "o": ["Entomology", "Ornithology", "Herpetology", "Zoology"], "a": 1, "e": "Ornithology studies birds.", "d": 1},
    {"t": "The branch of biology that studies plants is:", "o": ["Zoology", "Botany", "Mycology", "Ecology"], "a": 1, "e": "Botany studies plants.", "d": 1},
    {"t": "The branch of biology that studies fungi is:", "o": ["Botany", "Mycology", "Virology", "Bacteriology"], "a": 1, "e": "Mycology studies fungi.", "d": 1},
    {"t": "The study of tissues is called:", "o": ["Cytology", "Histology", "Anatomy", "Physiology"], "a": 1, "e": "Histology studies tissues.", "d": 1},
    {"t": "The study of cells is called:", "o": ["Histology", "Cytology", "Ecology", "Genetics"], "a": 1, "e": "Cytology studies cells.", "d": 1},
    {"t": "A group of similar cells performing the same function is a:", "o": ["Organ", "Tissue", "System", "Organism"], "a": 1, "e": "Tissues are groups of similar cells.", "d": 1},
    {"t": "A group of tissues performing a specific function is an:", "o": ["Cell", "Organ", "System", "Organism"], "a": 1, "e": "Organs are made of tissues.", "d": 1},
    {"t": "The level of organisation above organs is:", "o": ["Tissue", "Organ system", "Cell", "Organelle"], "a": 1, "e": "Organ systems are above organs.", "d": 1},
]

build("bio", "Biology", QUESTIONS[:200])
