from _common import build

QUESTIONS = [
    # ── Nature & significance ──
    {"t": "Bookkeeping is the process of:", "o": ["Recording financial transactions", "Auditing", "Taxing", "Marketing"], "a": 0, "e": "Bookkeeping records transactions.", "d": 1},
    {"t": "Accounting is best defined as:", "o": ["Recording only", "Recording, classifying and summarising financial transactions", "Auditing", "Filing returns"], "a": 1, "e": "Accounting records, classifies, summarises.", "d": 1},
    {"t": "The father of double-entry bookkeeping is:", "o": ["Adam Smith", "Luca Pacioli", "Keynes", "Ricardo"], "a": 1, "e": "Luca Pacioli documented double entry.", "d": 1},
    {"t": "The main purpose of accounting is to:", "o": ["Pay tax only", "Provide financial information for decision-making", "Hide losses", "Decorate"], "a": 1, "e": "Accounting informs decisions.", "d": 1},
    {"t": "The users of accounting information include:", "o": ["Owners, creditors, government", "Only owners", "Only government", "Only auditors"], "a": 0, "e": "Many parties use accounting info.", "d": 1},
    {"t": "The source documents of accounting include all EXCEPT:", "o": ["Invoices", "Receipts", "Cheques", "Newspapers"], "a": 3, "e": "Newspapers are not source documents.", "d": 1},
    {"t": "A business transaction is:", "o": ["Any event", "An event that affects the financial position", "A rumour", "A meeting"], "a": 1, "e": "Transactions affect financial position.", "d": 1},
    {"t": "The book of original entry is the:", "o": ["Ledger", "Journal/day book", "Trial balance", "Balance sheet"], "a": 1, "e": "Journals are books of prime entry.", "d": 1},
    {"t": "The principal book of account is the:", "o": ["Journal", "Ledger", "Invoice", "Cash book"], "a": 1, "e": "The ledger is the principal book.", "d": 1},
    {"t": "A ledger is a book containing:", "o": ["Journals", "Accounts", "Invoices", "Receipts"], "a": 1, "e": "The ledger holds accounts.", "d": 1},

    # ── Double entry ──
    {"t": "The double-entry system records each transaction in:", "o": ["One account", "Two accounts (debit and credit)", "Three accounts", "No account"], "a": 1, "e": "Every transaction has a debit and credit.", "d": 1},
    {"t": "In double entry, a debit entry is made on the:", "o": ["Right side", "Left side", "Top", "Bottom"], "a": 1, "e": "Debits go on the left.", "d": 1},
    {"t": "A credit entry is made on the:", "o": ["Left side", "Right side", "Top", "Bottom"], "a": 1, "e": "Credits go on the right.", "d": 1},
    {"t": "Assets increase with a:", "o": ["Credit", "Debit", "Both", "Neither"], "a": 1, "e": "Assets increase on the debit side.", "d": 1},
    {"t": "Liabilities increase with a:", "o": ["Debit", "Credit", "Both", "Neither"], "a": 1, "e": "Liabilities increase on the credit side.", "d": 1},
    {"t": "Capital increases with a:", "o": ["Debit", "Credit", "Both", "Neither"], "a": 1, "e": "Capital increases on the credit side.", "d": 1},
    {"t": "Expenses increase with a:", "o": ["Credit", "Debit", "Both", "Neither"], "a": 1, "e": "Expenses increase on the debit side.", "d": 1},
    {"t": "Income increases with a:", "o": ["Debit", "Credit", "Both", "Neither"], "a": 1, "e": "Income increases on the credit side.", "d": 1},
    {"t": "The accounting equation is:", "o": ["Assets = Liabilities + Capital", "Assets = Liabilities − Capital", "Capital = Assets + Liabilities", "Assets = Liabilities × Capital"], "a": 0, "e": "Assets = Liabilities + Capital.", "d": 1},
    {"t": "Purchases of goods for resale are recorded in the:", "o": ["Sales account", "Purchases account", "Capital account", "Cash account"], "a": 1, "e": "Goods bought go to the purchases account.", "d": 1},
    {"t": "Sales of goods are recorded in the:", "o": ["Purchases account", "Sales account", "Capital account", "Bank account"], "a": 1, "e": "Goods sold go to the sales account.", "d": 1},
    {"t": "When goods are bought on credit, the supplier's account is:", "o": ["Debited", "Credited", "Ignored", "Closed"], "a": 1, "e": "Creditors are credited.", "d": 1},
    {"t": "When cash is received, the cash account is:", "o": ["Credited", "Debited", "Ignored", "Closed"], "a": 1, "e": "Cash received = debit cash.", "d": 1},
    {"t": "The account debited when a business pays rent is:", "o": ["Cash", "Rent account", "Capital", "Bank"], "a": 1, "e": "Rent (expense) is debited.", "d": 1},

    # ── Ethics in accounting ──
    {"t": "The fundamental ethical principle in accounting includes:", "o": ["Dishonesty", "Integrity and objectivity", "Secrecy from regulators", "Bias"], "a": 1, "e": "Accountants must be honest and objective.", "d": 1},
    {"t": "Confidentiality in accounting means the accountant should:", "o": ["Share client secrets", "Keep client information private", "Sell information", "Gossip"], "a": 1, "e": "Accountants keep information confidential.", "d": 1},
    {"t": "Independence of an auditor means the auditor must be:", "o": ["Related to the client", "Free from bias/conflict of interest", "Employed by the client", "A shareholder"], "a": 1, "e": "Auditors must be independent.", "d": 1},

    # ── Cash book ──
    {"t": "The cash book is a book of:", "o": ["Secondary entry only", "Prime entry that combines cash and bank", "Final accounts", "Memoranda"], "a": 1, "e": "The cash book records cash and bank.", "d": 1},
    {"t": "A two-column cash book has columns for:", "o": ["Cash and discount", "Cash and bank", "Bank and discount", "Cash only"], "a": 1, "e": "Two-column = cash and bank.", "d": 1},
    {"t": "A three-column cash book has columns for:", "o": ["Cash, bank and discount", "Cash and bank", "Discount only", "Cash only"], "a": 0, "e": "Three-column = cash, bank, discount.", "d": 1},
    {"t": "The petty cash book records:", "o": ["Large payments", "Small cash payments", "Credit sales", "Investments"], "a": 1, "e": "Petty cash records small payments.", "d": 1},
    {"t": "The system where petty cash is topped up to a fixed amount is the:", "o": ["Fixed system", "Imprest system", "Credit system", "Bank system"], "a": 1, "e": "The imprest system restores the float.", "d": 1},
    {"t": "A contra entry in the cash book occurs when:", "o": ["Cash is paid out", "Cash is transferred between cash and bank", "Goods are sold", "A loan is taken"], "a": 1, "e": "Contra entries link cash and bank.", "d": 2},
    {"t": "Discount received is recorded on the ___ side of the cash book.", "o": ["Debit", "Credit", "Both", "Neither"], "a": 1, "e": "Discount received is credited.", "d": 2},
    {"t": "Discount allowed is recorded on the ___ side of the cash book.", "o": ["Credit", "Debit", "Both", "Neither"], "a": 1, "e": "Discount allowed is debited.", "d": 2},

    # ── Bank reconciliation ──
    {"t": "A bank reconciliation statement reconciles the:", "o": ["Cash book and bank statement balances", "Two bank accounts", "Debtors and creditors", "Sales and purchases"], "a": 0, "e": "It reconciles cash book with bank statement.", "d": 1},
    {"t": "The document sent by the bank showing account activity is the:", "o": ["Invoice", "Bank statement", "Cheque book", "Receipt"], "a": 1, "e": "Banks issue statements.", "d": 1},
    {"t": "An unpresented cheque is one:", "o": ["Paid by the bank", "Issued but not yet presented for payment", "Deposited", "Lost"], "a": 1, "e": "Unpresented cheques are not yet paid.", "d": 1},
    {"t": "An uncredited cheque is one:", "o": ["Paid out", "Deposited but not yet credited by the bank", "Cancelled", "Bounced"], "a": 1, "e": "Uncredited cheques are not yet in the account.", "d": 1},
    {"t": "Bank charges appear in the:", "o": ["Cash book only", "Bank statement (not yet in cash book)", "Ledger only", "Journal"], "a": 1, "e": "Bank charges appear on the statement first.", "d": 1},
    {"t": "A standing order is:", "o": ["A cheque", "A regular payment authorised to the bank", "A deposit", "A loan"], "a": 1, "e": "Standing orders are regular bank payments.", "d": 1},
    {"t": "A credit transfer into the account appears first in the:", "o": ["Cash book", "Bank statement", "Ledger", "Journal"], "a": 1, "e": "Credit transfers show on the statement.", "d": 1},
    {"t": "Dishonoured (bounced) cheques must be:", "o": ["Ignored", "Adjusted in the cash book", "Destroyed", "Framed"], "a": 1, "e": "Dishonoured cheques are reversed.", "d": 1},

    # ── Final accounts ──
    {"t": "The final accounts of a sole trader consist of:", "o": ["Trading, profit and loss account and balance sheet", "Cash book only", "Journal only", "Ledger only"], "a": 0, "e": "Final accounts: trading + P&L + balance sheet.", "d": 1},
    {"t": "The trading account is used to calculate:", "o": ["Net profit", "Gross profit", "Capital", "Assets"], "a": 1, "e": "The trading account shows gross profit.", "d": 1},
    {"t": "Gross profit equals:", "o": ["Sales − cost of goods sold", "Sales + expenses", "Revenue − all expenses", "Assets − liabilities"], "a": 0, "e": "Gross profit = sales − COGS.", "d": 1},
    {"t": "Cost of goods sold equals:", "o": ["Opening stock + purchases − closing stock", "Sales − profit", "Purchases only", "Closing stock − purchases"], "a": 0, "e": "COGS = opening stock + purchases − closing stock.", "d": 1},
    {"t": "Net profit equals:", "o": ["Gross profit − expenses", "Gross profit + expenses", "Sales − purchases", "Assets − liabilities"], "a": 0, "e": "Net profit = gross profit − expenses.", "d": 1},
    {"t": "The profit and loss account shows:", "o": ["Gross profit", "Net profit or loss", "Assets", "Capital"], "a": 1, "e": "The P&L shows net profit/loss.", "d": 1},
    {"t": "The balance sheet is a statement of:", "o": ["Profit", "Assets, liabilities and capital", "Sales", "Expenses"], "a": 1, "e": "The balance sheet shows financial position.", "d": 1},
    {"t": "The balance sheet equation is:", "o": ["Assets = Liabilities + Capital", "Assets = Liabilities − Capital", "Profit = Revenue − Cost", "Assets = Revenue"], "a": 0, "e": "Assets = Liabilities + Capital.", "d": 1},
    {"t": "Which of the following is a current asset?", "o": ["Land", "Stock", "Buildings", "Machinery"], "a": 1, "e": "Stock is a current asset.", "d": 1},
    {"t": "Which of the following is a fixed asset?", "o": ["Cash", "Machinery", "Stock", "Debtors"], "a": 1, "e": "Machinery is a fixed asset.", "d": 1},
    {"t": "Which of the following is a current liability?", "o": ["Loan (long-term)", "Creditors", "Capital", "Buildings"], "a": 1, "e": "Creditors are current liabilities.", "d": 1},
    {"t": "Depreciation is the:", "o": ["Increase in asset value", "Allocation of an asset's cost over its useful life", "Profit", "Revenue"], "a": 1, "e": "Depreciation spreads asset cost.", "d": 1},
    {"t": "The straight-line method of depreciation charges:", "o": ["A varying amount", "An equal amount each year", "Nothing", "A growing amount"], "a": 1, "e": "Straight line = equal annual charge.", "d": 1},
    {"t": "The reducing balance method charges depreciation on the:", "o": ["Cost", "Net book value", "Market value", "Scrap value"], "a": 1, "e": "Reducing balance uses net book value.", "d": 1},
    {"t": "Accrued expenses are expenses:", "o": ["Paid in advance", "Incurred but not yet paid", "Cancelled", "Refunded"], "a": 1, "e": "Accruals are unpaid expenses.", "d": 1},
    {"t": "Prepaid expenses are expenses:", "o": ["Not yet incurred", "Paid in advance", "Cancelled", "Refunded"], "a": 1, "e": "Prepayments are paid in advance.", "d": 1},
    {"t": "Accrued income is income:", "o": ["Received", "Earned but not yet received", "Refunded", "Lost"], "a": 1, "e": "Accrued income is earned but uncollected.", "d": 1},
    {"t": "Income received in advance is:", "o": ["Earned", "Received but not yet earned", "Refunded", "Lost"], "a": 1, "e": "It is received before being earned.", "d": 1},
    {"t": "Bad debts are debts that are:", "o": ["Collected", "Unlikely to be collected", "New", "Paid early"], "a": 1, "e": "Bad debts are uncollectible.", "d": 1},
    {"t": "A provision for doubtful debts is:", "o": ["An asset", "An allowance for possible bad debts", "Revenue", "Cash"], "a": 1, "e": "It provides for possible losses.", "d": 1},
    {"t": "Carriage inwards is added to:", "o": ["Sales", "Purchases", "Expenses", "Capital"], "a": 1, "e": "Carriage inwards is a purchase cost.", "d": 1},
    {"t": "Carriage outwards is treated as a(n):", "o": ["Asset", "Expense", "Income", "Liability"], "a": 1, "e": "Carriage outwards is an expense.", "d": 1},
    {"t": "Returns inwards are:", "o": ["Goods returned by customers", "Goods returned to suppliers", "Cash sales", "Purchases"], "a": 0, "e": "Returns inwards = from customers.", "d": 1},
    {"t": "Returns outwards are:", "o": ["From customers", "Goods returned to suppliers", "Cash sales", "Sales"], "a": 1, "e": "Returns outwards = to suppliers.", "d": 1},
    {"t": "The working capital of a business is:", "o": ["Fixed assets", "Current assets − current liabilities", "Total assets", "Capital"], "a": 1, "e": "Working capital = CA − CL.", "d": 1},

    # ── Stock valuation ──
    {"t": "Stock is usually valued at the lower of:", "o": ["Cost or net realisable value", "Cost or market + 20%", "Cost only", "Market only"], "a": 0, "e": "Stock = lower of cost and NRV.", "d": 1},
    {"t": "The FIFO method of stock valuation means:", "o": ["First-in, first-out", "Last-in, first-out", "Average cost", "Highest cost"], "a": 0, "e": "FIFO = first-in, first-out.", "d": 1},
    {"t": "The LIFO method means:", "o": ["First-in, first-out", "Last-in, first-out", "Average cost", "Lowest cost"], "a": 1, "e": "LIFO = last-in, first-out.", "d": 1},
    {"t": "The average cost method values stock at:", "o": ["Highest cost", "Average cost of units", "Lowest cost", "Market price"], "a": 1, "e": "Average cost uses the mean unit cost.", "d": 1},
    {"t": "Closing stock appears in the:", "o": ["Trading account and balance sheet", "Cash book", "Journal", "Ledger only"], "a": 0, "e": "Closing stock is in trading account + balance sheet.", "d": 1},
    {"t": "Opening stock is:", "o": ["Stock at the end", "Stock at the beginning of a period", "Purchases", "Sales"], "a": 1, "e": "Opening stock starts the period.", "d": 1},

    # ── Control accounts ──
    {"t": "A sales ledger control account summarises the:", "o": ["Creditors ledger", "Debtors ledger", "Cash book", "Capital"], "a": 1, "e": "Sales ledger control = debtors.", "d": 1},
    {"t": "A purchases ledger control account summarises the:", "o": ["Debtors ledger", "Creditors ledger", "Cash book", "Capital"], "a": 1, "e": "Purchases ledger control = creditors.", "d": 1},
    {"t": "Control accounts are kept in the:", "o": ["Sales ledger", "General ledger", "Cash book", "Journal"], "a": 1, "e": "Control accounts are in the general ledger.", "d": 1},
    {"t": "The purpose of control accounts is to:", "o": ["Replace ledgers", "Check the accuracy of the ledgers", "Hide errors", "Avoid audits"], "a": 1, "e": "Control accounts verify ledgers.", "d": 1},

    # ── Incomplete records ──
    {"t": "Single entry (incomplete records) is a system where:", "o": ["All entries are complete", "Not all transactions are recorded in double entry", "No records exist", "Only cash is recorded"], "a": 1, "e": "Single entry is incomplete.", "d": 1},
    {"t": "When records are incomplete, profit is calculated using:", "o": ["The balance sheet only", "The statement of affairs/equity comparison", "The cash book", "Nothing"], "a": 1, "e": "Profit = closing capital − opening capital (+ drawings − capital introduced).", "d": 1},
    {"t": "A statement of affairs is similar to a:", "o": ["Balance sheet", "Cash book", "Journal", "Trial balance"], "a": 0, "e": "A statement of affairs shows position.", "d": 1},
    {"t": "Drawings are:", "o": ["Capital introduced", "Money/goods taken out by the owner", "Sales", "Loans"], "a": 1, "e": "Drawings are owner withdrawals.", "d": 1},

    # ── Manufacturing accounts ──
    {"t": "A manufacturing account calculates the:", "o": ["Net profit", "Cost of production", "Sales", "Capital"], "a": 1, "e": "Manufacturing account finds cost of production.", "d": 1},
    {"t": "Direct costs are costs:", "o": ["Not traceable to products", "Directly traceable to production", "Of administration", "Of selling"], "a": 1, "e": "Direct costs trace to production.", "d": 1},
    {"t": "Direct materials are part of:", "o": ["Overheads", "Prime cost", "Indirect cost", "Selling cost"], "a": 1, "e": "Direct materials are prime cost.", "d": 1},
    {"t": "Prime cost equals:", "o": ["Direct materials + direct labour + direct expenses", "All costs", "Indirect costs", "Selling costs"], "a": 0, "e": "Prime cost = direct costs.", "d": 1},
    {"t": "Factory overheads are:", "o": ["Direct costs", "Indirect production costs", "Selling costs", "Direct materials"], "a": 1, "e": "Factory overheads are indirect.", "d": 1},
    {"t": "Work-in-progress is:", "o": ["Finished goods", "Partially completed goods", "Raw materials", "Scrap"], "a": 1, "e": "WIP is partially completed.", "d": 1},

    # ── Not-for-profit accounts ──
    {"t": "A not-for-profit organisation prepares:", "o": ["Trading account", "Income and expenditure account", "Profit and loss account", "Manufacturing account"], "a": 1, "e": "NPOs prepare income & expenditure accounts.", "d": 1},
    {"t": "The capital of a not-for-profit organisation is called:", "o": ["Share capital", "Accumulated fund", "Drawings", "Profit"], "a": 1, "e": "NPOs have an accumulated fund.", "d": 1},
    {"t": "A receipts and payments account records:", "o": ["Accruals", "Cash received and paid", "Credit sales", "Depreciation"], "a": 1, "e": "Receipts & payments is cash-based.", "d": 1},
    {"t": "The surplus of an NPO is the excess of:", "o": ["Expenses over income", "Income over expenditure", "Assets over liabilities", "Cash over bank"], "a": 1, "e": "Surplus = income − expenditure.", "d": 1},
    {"t": "Subscription in arrears is:", "o": ["Paid in advance", "Owed by members", "Refunded", "Waived"], "a": 1, "e": "Arrears are unpaid subscriptions.", "d": 1},
    {"t": "Subscriptions in advance are:", "o": ["Owed", "Paid for future periods", "Refunded", "Waived"], "a": 1, "e": "Advance subscriptions are prepaid.", "d": 1},

    # ── Partnership & company ──
    {"t": "A partnership is governed by a:", "o": ["Memorandum", "Partnership deed/agreement", "Invoice", "Receipt"], "a": 1, "e": "A partnership deed governs partners.", "d": 1},
    {"t": "Partners' profits are shared in the:", "o": ["Profit and loss appropriation account", "Trading account", "Cash book", "Balance sheet"], "a": 0, "e": "The appropriation account shares profit.", "d": 1},
    {"t": "In a partnership, interest on capital is:", "o": ["An expense", "An appropriation of profit", "A liability only", "Revenue"], "a": 1, "e": "Interest on capital is an appropriation.", "d": 1},
    {"t": "A company's owners are its:", "o": ["Partners", "Shareholders", "Employees", "Customers"], "a": 1, "e": "Shareholders own a company.", "d": 1},
    {"t": "The capital of a company is called:", "o": ["Accumulated fund", "Share capital", "Drawings", "Reserve only"], "a": 1, "e": "Companies have share capital.", "d": 1},
    {"t": "The profit distributed to shareholders is a:", "o": ["Loan", "Dividend", "Fee", "Tax"], "a": 1, "e": "Dividends go to shareholders.", "d": 1},
    {"t": "Retained earnings are:", "o": ["Distributed profit", "Profit kept in the business", "Losses", "Taxes"], "a": 1, "e": "Retained earnings are reinvested.", "d": 1},
    {"t": "The authorised share capital is the:", "o": ["Issued amount", "Maximum capital a company may raise", "Paid-up amount", "Dividend"], "a": 1, "e": "Authorised capital is the maximum.", "d": 1},
    {"t": "Issued share capital is the capital:", "o": ["Authorised", "Actually issued to shareholders", "Paid as dividend", "Borrowed"], "a": 1, "e": "Issued capital is allotted.", "d": 1},
    {"t": "Called-up capital is the:", "o": ["Maximum", "Amount shareholders are required to pay", "Dividend", "Reserve"], "a": 1, "e": "Called-up capital is demanded from shareholders.", "d": 1},

    # ── Public sector & IT ──
    {"t": "Government accounting is based on:", "o": ["Accrual only", "Cash basis (usually)", "Credit basis", "Barter"], "a": 1, "e": "Government often uses cash basis.", "d": 1},
    {"t": "The body that sets accounting standards in Nigeria is the:", "o": ["CBN", "Financial Reporting Council of Nigeria (FRCN)", "NDIC", "FIRS"], "a": 1, "e": "The FRCN sets standards.", "d": 1},
    {"t": "The use of computers in accounting is:", "o": ["Manual accounting", "Computerised accounting", "Barter", "Auditing only"], "a": 1, "e": "Computers automate accounting.", "d": 1},
    {"t": "An advantage of computerised accounting is:", "o": ["Slower processing", "Speed and accuracy", "More errors", "Higher manual work"], "a": 1, "e": "Computers are fast and accurate.", "d": 1},
    {"t": "The software used to manage accounts electronically is:", "o": ["Spreadsheet/accounting software", "Word processor", "Browser", "Game"], "a": 0, "e": "Accounting software manages accounts.", "d": 1},

    # ── More mixed ──
    {"t": "A trial balance is prepared to:", "o": ["Check the arithmetic accuracy of ledgers", "Show profit", "Show assets", "Pay tax"], "a": 0, "e": "A trial balance checks accuracy.", "d": 1},
    {"t": "A trial balance is a list of:", "o": ["All ledger balances", "Only expenses", "Only assets", "Only income"], "a": 0, "e": "It lists all ledger balances.", "d": 1},
    {"t": "The trial balance agrees when total debits equal:", "o": ["Total credits", "Total assets", "Total sales", "Total capital"], "a": 0, "e": "Debits must equal credits.", "d": 1},
    {"t": "The journal is used to record:", "o": ["Cash transactions", "Non-routine and adjusting entries", "Sales only", "Purchases only"], "a": 1, "e": "The journal records adjustments.", "d": 1},
    {"t": "The process of transferring entries from journal to ledger is:", "o": ["Journalising", "Posting", "Balancing", "Auditing"], "a": 1, "e": "Posting transfers to the ledger.", "d": 1},
    {"t": "The examination of accounts by an independent person is:", "o": ["Bookkeeping", "Auditing", "Posting", "Journalising"], "a": 1, "e": "Auditing examines accounts.", "d": 1},
    {"t": "The person who audits accounts is the:", "o": ["Accountant", "Auditor", "Bookkeeper", "Manager"], "a": 1, "e": "Auditors examine accounts.", "d": 1},
    {"t": "The balance sheet is also called the:", "o": ["Profit statement", "Statement of financial position", "Cash flow", "Trading account"], "a": 1, "e": "Balance sheet = statement of financial position.", "d": 1},
    {"t": "The statement showing cash inflows and outflows is the:", "o": ["Cash flow statement", "Balance sheet", "Trading account", "Trial balance"], "a": 0, "e": "Cash flow shows cash movement.", "d": 1},
    {"t": "Capital expenditure is spending on:", "o": ["Daily expenses", "Acquiring fixed assets", "Salaries", "Rent"], "a": 1, "e": "Capital expenditure buys fixed assets.", "d": 1},
    {"t": "Revenue expenditure is spending on:", "o": ["Fixed assets", "Day-to-day running costs", "Land", "Buildings"], "a": 1, "e": "Revenue expenditure is routine.", "d": 1},
    {"t": "An asset is:", "o": ["A debt", "A resource owned that has value", "A loss", "An expense"], "a": 1, "e": "Assets are owned resources.", "d": 1},
    {"t": "A liability is:", "o": ["An asset", "An amount owed to others", "Capital", "Revenue"], "a": 1, "e": "Liabilities are debts owed.", "d": 1},
    {"t": "Owner's equity is:", "o": ["A liability only", "The owner's stake in the business", "A debt", "An expense"], "a": 1, "e": "Equity = owner's interest.", "d": 1},
    {"t": "The double-entry for a cash sale is: debit cash, credit:", "o": ["Purchases", "Sales", "Capital", "Debtors"], "a": 1, "e": "Cash sales credit the sales account.", "d": 1},
    {"t": "The double-entry for buying a machine for cash is: debit machinery, credit:", "o": ["Cash", "Bank", "Sales", "Capital"], "a": 0, "e": "Cash is credited when paying cash.", "d": 1},
    {"t": "The double-entry for paying a creditor by cheque is: debit creditor, credit:", "o": ["Cash", "Bank", "Purchases", "Sales"], "a": 1, "e": "Bank is credited for payments.", "d": 1},
    {"t": "The double-entry for receiving money from a debtor is: debit cash, credit:", "o": ["Sales", "Debtor", "Purchases", "Capital"], "a": 1, "e": "The debtor's account is credited.", "d": 1},
    {"t": "A nominal account records:", "o": ["Persons", "Assets", "Income and expenses", "Liabilities"], "a": 2, "e": "Nominal accounts record income/expenses.", "d": 1},
    {"t": "A real account records:", "o": ["Income", "Assets", "Expenses", "Persons"], "a": 1, "e": "Real accounts record assets.", "d": 1},
    {"t": "A personal account records:", "o": ["Assets", "Transactions with individuals/firms", "Income", "Expenses"], "a": 1, "e": "Personal accounts record persons/firms.", "d": 1},
    {"t": "The ledger that contains customers' accounts is the:", "o": ["Purchases ledger", "Sales ledger", "General ledger", "Cash book"], "a": 1, "e": "The sales ledger holds customers.", "d": 1},
    {"t": "The ledger that contains suppliers' accounts is the:", "o": ["Sales ledger", "Purchases ledger", "General ledger", "Cash book"], "a": 1, "e": "The purchases ledger holds suppliers.", "d": 1},
    {"t": "The general ledger contains:", "o": ["Only customers", "All other accounts (assets, capital, etc.)", "Only suppliers", "Only cash"], "a": 1, "e": "The general ledger holds the rest.", "d": 1},
    {"t": "The cash flow statement is prepared under:", "o": ["Accrual basis", "Cash basis", "Credit basis", "Barter"], "a": 1, "e": "Cash flow uses cash basis.", "d": 1},
    {"t": "A bank overdraft is:", "o": ["An asset", "A current liability", "Capital", "Revenue"], "a": 1, "e": "An overdraft is a liability.", "d": 1},
    {"t": "The provision for depreciation is:", "o": ["An expense", "A contra-asset account", "Revenue", "A liability"], "a": 1, "e": "It reduces the asset's value.", "d": 1},
    {"t": "Goodwill is a(n):", "o": ["Tangible asset", "Intangible asset", "Liability", "Expense"], "a": 1, "e": "Goodwill is intangible.", "d": 1},
    {"t": "The process of recording only credit sales in the:", "o": ["Cash book", "Sales day book", "Petty cash", "Ledger only"], "a": 1, "e": "Credit sales go in the sales day book.", "d": 1},
    {"t": "The purchases day book records:", "o": ["Cash purchases", "Credit purchases", "Cash sales", "Credit sales"], "a": 1, "e": "Credit purchases go in the purchases day book.", "d": 1},
    {"t": "The returns inwards day book records:", "o": ["Goods returned by customers", "Goods returned to suppliers", "Cash", "Expenses"], "a": 0, "e": "Returns inwards = from customers.", "d": 1},
    {"t": "The returns outwards day book records:", "o": ["From customers", "Goods returned to suppliers", "Cash", "Sales"], "a": 1, "e": "Returns outwards = to suppliers.", "d": 1},
    {"t": "The petty cash book is maintained under the:", "o": ["Imprest system", "Credit system", "Accrual system", "Cash system only"], "a": 0, "e": "Petty cash uses the imprest system.", "d": 1},
    {"t": "A suspense account is used to:", "o": ["Hold errors pending correction", "Record sales", "Record cash", "Pay tax"], "a": 0, "e": "A suspense account holds discrepancies.", "d": 1},
    {"t": "An error of commission is:", "o": ["Posting to the wrong account of the same class", "Posting to a wrong side", "Omitting an entry", "A calculation error"], "a": 0, "e": "Commission = wrong account, same class.", "d": 2},
    {"t": "An error of omission is:", "o": ["Posting to wrong account", "Leaving out an entry entirely", "Posting wrong side", "Wrong figure"], "a": 1, "e": "Omission = entry left out.", "d": 2},
    {"t": "An error of principle is posting to:", "o": ["A wrong account type (e.g. expense as asset)", "Wrong side", "Wrong amount", "Nothing"], "a": 0, "e": "Principle errors misclassify accounts.", "d": 2},
    {"t": "An error of original entry is:", "o": ["A wrong figure in both accounts", "An omission", "A wrong side", "A commission"], "a": 0, "e": "Original entry = wrong figure recorded twice.", "d": 2},
    {"t": "A compensating error is when:", "o": ["Two errors cancel each other", "One error", "No error", "An omission"], "a": 0, "e": "Compensating errors cancel out.", "d": 2},
    # ── More mixed ──
    {"t": "The gross profit margin is gross profit expressed as a percentage of:", "o": ["Cost of sales", "Sales", "Capital", "Expenses"], "a": 1, "e": "GPM = GP/sales × 100.", "d": 2},
    {"t": "The net profit margin is net profit as a percentage of:", "o": ["Expenses", "Sales", "Capital", "Assets"], "a": 1, "e": "NPM = NP/sales × 100.", "d": 2},
    {"t": "The current ratio is:", "o": ["Current assets / current liabilities", "Fixed assets / capital", "Sales / stock", "Profit / capital"], "a": 0, "e": "Current ratio = CA/CL.", "d": 2},
    {"t": "The quick (acid test) ratio excludes:", "o": ["Cash", "Stock", "Debtors", "Bank"], "a": 1, "e": "Quick ratio excludes stock.", "d": 2},
    {"t": "The ratio that measures liquidity is the:", "o": ["Profit ratio", "Current ratio", "Asset ratio", "Turnover ratio"], "a": 1, "e": "Current ratio measures liquidity.", "d": 2},
    {"t": "The rate of stock turnover is:", "o": ["Cost of goods sold / average stock", "Stock / sales", "Sales / capital", "Profit / stock"], "a": 0, "e": "Stock turnover = COGS/average stock.", "d": 2},
    {"t": "The debtor's collection period measures:", "o": ["How long debtors take to pay", "Stock holding", "Profit", "Liquidity"], "a": 0, "e": "It measures collection time.", "d": 2},
    {"t": "The creditor's payment period measures:", "o": ["Collection time", "How long the business takes to pay suppliers", "Profit", "Liquidity"], "a": 1, "e": "It measures payment to suppliers.", "d": 2},
    {"t": "Depreciation is provided in the accounts to:", "o": ["Match asset cost with revenue earned", "Increase profit", "Avoid tax only", "Sell assets"], "a": 0, "e": "Depreciation matches cost to revenue.", "d": 1},
    {"t": "The book value of an asset is its cost minus:", "o": ["Profit", "Accumulated depreciation", "Sales", "Revenue"], "a": 1, "e": "Book value = cost − accumulated depreciation.", "d": 1},
    {"t": "If an asset costing ₦100,000 depreciates at 10% straight line, the annual depreciation is:", "o": ["₦10,000", "₦1,000", "₦100,000", "₦9,000"], "a": 0, "e": "10% × 100,000 = 10,000.", "d": 2},
    {"t": "The reducing balance method gives:", "o": ["Equal charges", "Decreasing annual charges", "Increasing charges", "No charge"], "a": 1, "e": "Reducing balance charges decrease over time.", "d": 1},
    {"t": "An asset bought for ₦50,000 with a residual value of ₦5,000 and 5-year life has straight-line depreciation of:", "o": ["₦9,000", "₦10,000", "₦5,000", "₦45,000"], "a": 0, "e": "(50,000 − 5,000)/5 = 9,000.", "d": 2},
    {"t": "The entry to record depreciation is: debit depreciation expense, credit:", "o": ["Asset account", "Provision for depreciation", "Cash", "Capital"], "a": 1, "e": "Provision for depreciation is credited.", "d": 2},
    {"t": "The cash book balance and bank statement balance differ due to:", "o": ["Timing differences and errors", "Only errors", "Only timing", "Nothing"], "a": 0, "e": "Timing differences and errors cause differences.", "d": 1},
    {"t": "When the cash book shows a credit balance, it means:", "o": ["Cash in hand", "A bank overdraft", "A profit", "No cash"], "a": 1, "e": "Credit cash book = overdraft.", "d": 1},
    {"t": "The balance carried down (bal c/d) is placed:", "o": ["On the larger side to balance the account", "On the smaller side", "In the journal", "Nowhere"], "a": 1, "e": "bal c/d balances the account on the smaller side.", "d": 2},
    {"t": "The balance brought down (bal b/d) is the:", "o": ["Closing balance", "Opening balance of the next period", "Profit", "Sales"], "a": 1, "e": "bal b/d opens the next period.", "d": 1},
    {"t": "The trial balance is prepared from the:", "o": ["Journal", "Ledger balances", "Cash book", "Invoices"], "a": 1, "e": "Ledger balances form the trial balance.", "d": 1},
    {"t": "If the trial balance does not agree, the difference is placed in a:", "o": ["Suspense account", "Sales account", "Capital account", "Cash account"], "a": 0, "e": "A suspense account holds the difference.", "d": 1},
    {"t": "The main books of account are the:", "o": ["Journal and ledger", "Invoice and receipt", "Cash book only", "Day books only"], "a": 0, "e": "Journal and ledger are the main books.", "d": 1},
    {"t": "The petty cashier is reimbursed under the imprest system to:", "o": ["Increase the float", "Restore the float to its original amount", "Pay dividends", "Buy assets"], "a": 1, "e": "Reimbursement restores the float.", "d": 1},
    {"t": "The imprest amount is the:", "o": ["Spent amount", "Fixed petty cash float", "Profit", "Loan"], "a": 1, "e": "The imprest is the fixed float.", "d": 1},
    {"t": "The account used to correct errors and balances is the:", "o": ["Sales account", "Suspense account", "Capital account", "Bank account"], "a": 1, "e": "Suspense holds errors.", "d": 1},
    {"t": "The value of a business's reputation is its:", "o": ["Stock", "Goodwill", "Cash", "Debtors"], "a": 1, "e": "Goodwill is reputational value.", "d": 1},
    {"t": "A company's financial statements are prepared by the:", "o": ["Auditors", "Accountants (management)", "Shareholders", "Customers"], "a": 1, "e": "Management/accountants prepare statements.", "d": 1},
    {"t": "The auditor's report expresses:", "o": ["A sales forecast", "An opinion on the financial statements", "Tax liability", "Dividend"], "a": 1, "e": "The auditor gives an opinion.", "d": 1},
    {"t": "The accounting period is usually:", "o": ["One year", "One month", "One week", "Ten years"], "a": 0, "e": "The accounting period is a year.", "d": 1},
    {"t": "The going concern concept assumes the business will:", "o": ["Close soon", "Continue operating indefinitely", "Be sold", "Liquidate"], "a": 1, "e": "Going concern assumes continuity.", "d": 1},
    {"t": "The accruals concept states that transactions are recorded:", "o": ["When cash moves", "When they occur, regardless of cash", "Only at year end", "Never"], "a": 1, "e": "Accruals record when incurred.", "d": 1},
    {"t": "The consistency concept means using:", "o": ["Different methods each year", "The same accounting methods over time", "No methods", "Random methods"], "a": 1, "e": "Consistency = same methods over time.", "d": 1},
    {"t": "The prudence (conservatism) concept means:", "o": ["Overstating profit", "Not overstating assets/income, providing for losses", "Ignoring losses", "Hiding debts"], "a": 1, "e": "Prudence avoids overstatement.", "d": 1},
    {"t": "The matching concept matches:", "o": ["Assets with liabilities", "Revenue with the expenses incurred to earn it", "Cash with bank", "Debtors with creditors"], "a": 1, "e": "Matching links revenue and expenses.", "d": 1},
    {"t": "The realisation concept recognises revenue when:", "o": ["Cash is received", "The sale is earned (goods delivered)", "Ordered", "Invoiced only"], "a": 1, "e": "Revenue is recognised when earned.", "d": 1},
    {"t": "The money measurement concept records only:", "o": ["Qualitative items", "Transactions measurable in money", "Opinions", "Feelings"], "a": 1, "e": "Only money-measurable items are recorded.", "d": 1},
    {"t": "The entity concept separates:", "o": ["Business and owner's affairs", "Assets and liabilities", "Income and expenses", "Cash and bank"], "a": 0, "e": "The entity is separate from the owner.", "d": 1},
    {"t": "The dual aspect concept is the basis of:", "o": ["Single entry", "Double entry", "Cash accounting", "Budgeting"], "a": 1, "e": "Dual aspect underpins double entry.", "d": 1},
    {"t": "The historical cost concept records assets at:", "o": ["Market value", "Original cost", "Replacement cost", "Scrap value"], "a": 1, "e": "Assets are at original cost.", "d": 1},
    {"t": "A budget is a:", "o": ["Record of the past", "Plan expressed in financial terms for the future", "Receipt", "Invoice"], "a": 1, "e": "A budget is a financial plan.", "d": 1},
    {"t": "Variance analysis compares:", "o": ["Two companies", "Actual results with budgeted figures", "Cash and bank", "Assets and liabilities"], "a": 1, "e": "Variance = actual vs budget.", "d": 1},
    {"t": "A favourable variance is when actual cost is:", "o": ["Higher than budget", "Lower than budget", "Equal", "Zero"], "a": 1, "e": "Lower actual cost is favourable.", "d": 2},
    {"t": "An adverse variance is when actual cost is:", "o": ["Lower than budget", "Higher than budget", "Equal", "Zero"], "a": 1, "e": "Higher actual cost is adverse.", "d": 2},
    {"t": "Cost accounting deals with:", "o": ["Determining the cost of products", "Only tax", "Only cash", "Only sales"], "a": 0, "e": "Cost accounting determines product costs.", "d": 1},
    {"t": "Management accounting provides information for:", "o": ["External users only", "Internal decision-making", "Tax authorities only", "Shareholders only"], "a": 1, "e": "Management accounting serves managers.", "d": 1},
    {"t": "Financial accounting provides information for:", "o": ["Managers only", "External users (investors, creditors)", "Employees only", "No one"], "a": 1, "e": "Financial accounting serves external users.", "d": 1},
    {"t": "The payroll records show:", "o": ["Sales", "Employees' wages and deductions", "Stock", "Assets"], "a": 1, "e": "Payroll records wages.", "d": 1},
    {"t": "Gross pay is:", "o": ["Net pay", "Total earnings before deductions", "Tax only", "Pension only"], "a": 1, "e": "Gross pay = before deductions.", "d": 1},
    {"t": "Net pay is:", "o": ["Gross pay", "Gross pay minus deductions", "Tax only", "Bonus"], "a": 1, "e": "Net pay = gross − deductions.", "d": 1},
    {"t": "Deductions from wages include:", "o": ["Bonuses", "Tax and pension contributions", "Overtime", "Allowances"], "a": 1, "e": "Tax/pension are deducted.", "d": 1},
    {"t": "The bank statement is a copy of the customer's account kept by the:", "o": ["Customer", "Bank", "Auditor", "Registrar"], "a": 1, "e": "The bank keeps the statement.", "d": 1},
    {"t": "The cash book is kept by the:", "o": ["Bank", "Business (customer)", "Auditor", "Registrar"], "a": 1, "e": "The business keeps the cash book.", "d": 1},
    {"t": "A cheque is a:", "o": ["Currency", "Written order to a bank to pay money", "Loan", "Receipt"], "a": 1, "e": "A cheque orders a payment.", "d": 1},
    {"t": "The person who writes a cheque is the:", "o": ["Payee", "Drawer", "Drawee", "Endorser"], "a": 1, "e": "The drawer writes the cheque.", "d": 1},
    {"t": "The bank on which a cheque is drawn is the:", "o": ["Drawer", "Drawee", "Payee", "Endorser"], "a": 1, "e": "The drawee is the bank.", "d": 1},
    {"t": "The person to whom a cheque is payable is the:", "o": ["Drawer", "Payee", "Drawee", "Endorser"], "a": 1, "e": "The payee receives payment.", "d": 1},
    {"t": "A crossed cheque is one that:", "o": ["Can be cashed over the counter", "Must be paid into a bank account", "Is void", "Is foreign"], "a": 1, "e": "Crossed cheques go into accounts.", "d": 1},
    {"t": "A stale cheque is one that is:", "o": ["Recently written", "Too old to be honoured", "Post-dated", "Crossed"], "a": 1, "e": "Stale cheques are outdated.", "d": 1},
    {"t": "A post-dated cheque is dated:", "o": ["In the past", "In the future", "Today", "Never"], "a": 1, "e": "Post-dated cheques are for the future.", "d": 1},
]

build("acc", "Financial Accounting", QUESTIONS[:200])
