from _common import build

QUESTIONS = [
    # ── Lexis: Synonyms ──
    {"t": "Choose the option nearest in meaning to the word 'lucid'.", "o": ["Obscure", "Clear", "Lengthy", "Turbid"], "a": 1, "e": "'Lucid' means expressed clearly or easy to understand, so 'clear' is nearest in meaning.", "d": 1},
    {"t": "The word 'meticulous' most nearly means:", "o": ["Careless", "Hasty", "Very careful", "Generous"], "a": 2, "e": "'Meticulous' means showing great attention to detail; very careful and precise.", "d": 2},
    {"t": "Choose the option nearest in meaning to 'impeccable'.", "o": ["Faultless", "Doubtful", "Expensive", "Ordinary"], "a": 0, "e": "'Impeccable' means in accordance with the highest standards; faultless.", "d": 2},
    {"t": "'Benevolent' is closest in meaning to:", "o": ["Hostile", "Kind", "Strict", "Wealthy"], "a": 1, "e": "'Benevolent' means well-meaning and kindly, i.e. kind.", "d": 1},
    {"t": "Choose the word nearest in meaning to 'abundant'.", "o": ["Scarce", "Plentiful", "Expensive", "Rare"], "a": 1, "e": "'Abundant' means existing or available in large quantities; plentiful.", "d": 1},
    {"t": "'Candid' most nearly means:", "o": ["Deceitful", "Secretive", "Frank", "Rude"], "a": 2, "e": "'Candid' means truthful and straightforward; frank.", "d": 2},
    {"t": "Choose the option nearest in meaning to 'diligent'.", "o": ["Lazy", "Hard-working", "Slow", "Careless"], "a": 1, "e": "'Diligent' means having or showing care and conscientiousness in one's work.", "d": 1},
    {"t": "'Vigilant' is closest in meaning to:", "o": ["Sleepy", "Alert", "Brave", "Quiet"], "a": 1, "e": "'Vigilant' means keeping careful watch for possible danger; alert.", "d": 1},
    {"t": "Choose the word nearest in meaning to 'coherent'.", "o": ["Confused", "Logical", "Broken", "Silent"], "a": 1, "e": "'Coherent' means logical, consistent and orderly; easy to follow.", "d": 2},
    {"t": "'Adequate' most nearly means:", "o": ["Insufficient", "Excessive", "Enough", "Minimal"], "a": 2, "e": "'Adequate' means satisfactory or acceptable in quality or quantity; enough.", "d": 1},
    {"t": "Choose the option nearest in meaning to 'obsolete'.", "o": ["Modern", "Outdated", "Valuable", "Repaired"], "a": 1, "e": "'Obsolete' means no longer produced or used; out of date.", "d": 2},
    {"t": "'Eloquent' is closest in meaning to:", "o": ["Fluent", "Silent", "Blunt", "Hesitant"], "a": 0, "e": "'Eloquent' means fluent or persuasive in speaking or writing.", "d": 2},
    {"t": "Choose the word nearest in meaning to 'genuine'.", "o": ["Fake", "Authentic", "Recent", "Common"], "a": 1, "e": "'Genuine' means truly what it is said to be; authentic.", "d": 1},
    {"t": "'Inevitable' most nearly means:", "o": ["Avoidable", "Unavoidable", "Improbable", "Desirable"], "a": 1, "e": "'Inevitable' means certain to happen; unavoidable.", "d": 2},
    {"t": "Choose the option nearest in meaning to 'reluctant'.", "o": ["Willing", "Eager", "Unwilling", "Ready"], "a": 2, "e": "'Reluctant' means unwilling and hesitant; disinclined.", "d": 1},
    {"t": "'Transparent' in the sense of openness is closest in meaning to:", "o": ["Opaque", "Honest", "Fragile", "Colourful"], "a": 1, "e": "Figuratively, 'transparent' means open and honest, without hidden motives.", "d": 2},
    {"t": "Choose the word nearest in meaning to 'commence'.", "o": ["Finish", "Begin", "Pause", "Delay"], "a": 1, "e": "'Commence' means to begin or start.", "d": 1},
    {"t": "'Abandon' most nearly means:", "o": ["Adopt", "Support", "Desert", "Embrace"], "a": 2, "e": "'Abandon' means to give up completely or desert.", "d": 1},
    {"t": "Choose the option nearest in meaning to 'proficient'.", "o": ["Skilled", "Amateur", "Ignorant", "Careless"], "a": 0, "e": "'Proficient' means competent or skilled in doing something.", "d": 2},
    {"t": "'Cumbersome' is closest in meaning to:", "o": ["Light", "Awkward", "Portable", "Simple"], "a": 1, "e": "'Cumbersome' means large, heavy, or difficult to handle; awkward.", "d": 2},

    # ── Lexis: Antonyms ──
    {"t": "Choose the option opposite in meaning to 'scarcity'.", "o": ["Shortage", "Abundance", "Dearth", "Lack"], "a": 1, "e": "'Scarcity' means shortage, so its opposite is 'abundance'.", "d": 1},
    {"t": "The word opposite in meaning to 'vague' is:", "o": ["Unclear", "Definite", "Hazy", "Ambiguous"], "a": 1, "e": "'Vague' means unclear, so the opposite is 'definite'.", "d": 1},
    {"t": "Choose the option opposite in meaning to 'frugal'.", "o": ["Thrifty", "Economical", "Extravagant", "Prudent"], "a": 2, "e": "'Frugal' means sparing with money, so the opposite is 'extravagant'.", "d": 2},
    {"t": "The opposite of 'optimist' is:", "o": ["Realist", "Pessimist", "Idealist", "Enthusiast"], "a": 1, "e": "An optimist expects good outcomes; a pessimist expects bad ones.", "d": 1},
    {"t": "Choose the option opposite in meaning to 'temporary'.", "o": ["Brief", "Momentary", "Permanent", "Fleeting"], "a": 2, "e": "'Temporary' means lasting a short time; opposite is 'permanent'.", "d": 1},
    {"t": "The opposite of 'humble' is:", "o": ["Modest", "Arrogant", "Meek", "Simple"], "a": 1, "e": "'Humble' means modest; opposite is 'arrogant'.", "d": 1},
    {"t": "Choose the option opposite in meaning to 'expand'.", "o": ["Enlarge", "Contract", "Stretch", "Increase"], "a": 1, "e": "'Expand' means to make larger; opposite is 'contract' (make smaller).", "d": 1},
    {"t": "The opposite of 'transparent' is:", "o": ["Clear", "Opaque", "Glass", "Obvious"], "a": 1, "e": "'Transparent' means see-through; 'opaque' means not see-through.", "d": 1},
    {"t": "Choose the option opposite in meaning to 'courage'.", "o": ["Bravery", "Cowardice", "Valour", "Daring"], "a": 1, "e": "'Courage' means bravery; opposite is 'cowardice'.", "d": 1},
    {"t": "The opposite of 'permanent' is:", "o": ["Lasting", "Stable", "Temporary", "Durable"], "a": 2, "e": "'Permanent' means lasting forever; opposite is 'temporary'.", "d": 1},
    {"t": "Choose the option opposite in meaning to 'compulsory'.", "o": ["Mandatory", "Voluntary", "Required", "Binding"], "a": 1, "e": "'Compulsory' means required; opposite is 'voluntary'.", "d": 1},
    {"t": "The opposite of 'decrease' is:", "o": ["Reduce", "Diminish", "Increase", "Lower"], "a": 2, "e": "'Decrease' means to become smaller; opposite is 'increase'.", "d": 1},
    {"t": "Choose the option opposite in meaning to 'hostile'.", "o": ["Friendly", "Aggressive", "Unfriendly", "Warlike"], "a": 0, "e": "'Hostile' means unfriendly; opposite is 'friendly'.", "d": 1},
    {"t": "The opposite of 'barren' is:", "o": ["Desolate", "Fertile", "Empty", "Dry"], "a": 1, "e": "'Barren' means unable to produce life/crops; opposite is 'fertile'.", "d": 2},
    {"t": "Choose the option opposite in meaning to 'victory'.", "o": ["Triumph", "Success", "Defeat", "Win"], "a": 2, "e": "'Victory' means a win; opposite is 'defeat'.", "d": 1},
    {"t": "The opposite of 'modern' is:", "o": ["Current", "Ancient", "New", "Recent"], "a": 1, "e": "'Modern' means present-day; opposite is 'ancient'.", "d": 1},
    {"t": "Choose the option opposite in meaning to 'artificial'.", "o": ["Synthetic", "Natural", "Fake", "Manufactured"], "a": 1, "e": "'Artificial' means made by humans; opposite is 'natural'.", "d": 1},
    {"t": "The opposite of 'praise' is:", "o": ["Commend", "Blame", "Applaud", "Honour"], "a": 1, "e": "'Praise' means to express approval; opposite is 'blame'.", "d": 1},
    {"t": "Choose the option opposite in meaning to 'arid'.", "o": ["Dry", "Wet", "Barren", "Parched"], "a": 1, "e": "'Arid' means very dry; opposite is 'wet' or 'humid'.", "d": 2},
    {"t": "The opposite of 'accept' is:", "o": ["Receive", "Agree", "Reject", "Take"], "a": 2, "e": "'Accept' means to receive willingly; opposite is 'reject'.", "d": 1},

    # ── Sentence interpretation ──
    {"t": "Select the option that best interprets the sentence: 'The new policy is a double-edged sword.'", "o": ["It is very sharp", "It has both advantages and disadvantages", "It is illegal", "It is very expensive"], "a": 1, "e": "A 'double-edged sword' is something that can help and harm at the same time.", "d": 2},
    {"t": "'She decided to bury the hatchet with her rival.' This means she decided to:", "o": ["Hide a weapon", "End their quarrel", "Dig a hole", "Attack her rival"], "a": 1, "e": "To 'bury the hatchet' means to end a quarrel and make peace.", "d": 2},
    {"t": "Select the option that best interprets: 'He is the black sheep of the family.'", "o": ["He keeps sheep", "He is the most successful", "He is a disreputable member", "He is the youngest"], "a": 2, "e": "A 'black sheep' is a member of a group regarded as a disgrace or odd one out.", "d": 2},
    {"t": "'The teacher turned a blind eye to the noise.' This means the teacher:", "o": ["Could not see", "Pretended not to notice", "Closed the window", "Was blind"], "a": 1, "e": "To 'turn a blind eye' means to deliberately ignore something.", "d": 2},
    {"t": "Select the option that best interprets: 'Don't count your chickens before they hatch.'", "o": ["Chickens are unreliable", "Don't plan on things that may not happen", "Count eggs carefully", "Buy more chickens"], "a": 1, "e": "The proverb warns against assuming success before it actually occurs.", "d": 2},
    {"t": "'It is raining cats and dogs.' This means:", "o": ["Animals are falling", "It is raining heavily", "There is a storm warning", "The weather is fine"], "a": 1, "e": "'Raining cats and dogs' is an idiom meaning very heavy rain.", "d": 1},
    {"t": "Select the option that best interprets: 'He let the cat out of the bag.'", "o": ["He released a cat", "He revealed a secret", "He bought a bag", "He made a mistake"], "a": 1, "e": "To 'let the cat out of the bag' means to reveal a secret carelessly.", "d": 2},
    {"t": "'She is feeling under the weather.' This means she is:", "o": ["Enjoying the rain", "Unwell", "Very happy", "Travelling"], "a": 1, "e": "'Under the weather' means slightly unwell or sick.", "d": 1},
    {"t": "Select the option that best interprets: 'The ball is in your court now.'", "o": ["You must play tennis", "It is your turn to act", "You have lost", "The game is over"], "a": 1, "e": "'The ball is in your court' means it is now your responsibility to act.", "d": 2},
    {"t": "'They saw eye to eye on the issue.' This means they:", "o": ["Disagreed strongly", "Agreed with each other", "Looked at each other", "Avoided the topic"], "a": 1, "e": "To 'see eye to eye' means to be in full agreement.", "d": 2},
    {"t": "Select the option that best interprets: 'The plan was a flash in the pan.'", "o": ["It succeeded briefly", "It was a huge success", "It was dangerous", "It took long to prepare"], "a": 0, "e": "A 'flash in the pan' is a sudden success that is not repeated; brief.", "d": 2},
    {"t": "'Stop beating about the bush.' This means stop:", "o": ["Cutting trees", "Avoiding the main point", "Fighting", "Working slowly"], "a": 1, "e": "To 'beat about the bush' means to avoid coming to the point.", "d": 2},
    {"t": "Select the option that best interprets: 'A stitch in time saves nine.'", "o": ["Sewing is important", "Acting early prevents bigger problems", "Nine stitches are enough", "Time is money"], "a": 1, "e": "The proverb means dealing with a problem early saves more work later.", "d": 2},
    {"t": "'He is a jack of all trades.' This means he:", "o": ["Is a trader", "Can do many things reasonably well", "Is an expert in one thing", "Sells tools"], "a": 1, "e": "A 'jack of all trades' is someone skilled in many areas (often none mastered).", "d": 2},
    {"t": "Select the option that best interprets: 'The news came like a bolt from the blue.'", "o": ["It was expected", "It was sudden and unexpected", "It was good news", "It was delayed"], "a": 1, "e": "A 'bolt from the blue' is a sudden, unexpected event.", "d": 2},
    {"t": "'She has an axe to grind with him.' This means she:", "o": ["Wants to sharpen a tool", "Has a private grievance", "Wants to help him", "Is indifferent"], "a": 1, "e": "To 'have an axe to grind' means to have a personal grievance or agenda.", "d": 2},
    {"t": "Select the option that best interprets: 'Every cloud has a silver lining.'", "o": ["Clouds are white", "Difficulties contain hope", "Weather changes", "Rain is coming"], "a": 1, "e": "The proverb means even bad situations have some positive aspect.", "d": 2},
    {"t": "'He gave her the cold shoulder.' This means he:", "o": ["Gave her a coat", "Ignored her deliberately", "Comforted her", "Scolded her"], "a": 1, "e": "To 'give the cold shoulder' means to intentionally ignore someone.", "d": 2},
    {"t": "Select the option that best interprets: 'It cost him an arm and a leg.'", "o": ["It was cheap", "It was very expensive", "He was injured", "He lost his limbs"], "a": 1, "e": "'Cost an arm and a leg' means extremely expensive.", "d": 2},
    {"t": "'Birds of a feather flock together.' This means:", "o": ["Birds are social", "People associate with those similar to themselves", "Birds migrate", "People avoid each other"], "a": 1, "e": "The proverb means similar people tend to associate together.", "d": 2},

    # ── Grammar: concord & tense ──
    {"t": "Choose the correct option: 'Neither of the boys ___ present.'", "o": ["were", "are", "was", "have been"], "a": 2, "e": "'Neither' is singular, so it takes the singular verb 'was'.", "d": 2},
    {"t": "Select the correct form: 'The committee ___ divided on the issue.'", "o": ["are", "is", "were", "have"], "a": 1, "e": "When a collective noun acts as a single unit, it takes a singular verb ('is').", "d": 2},
    {"t": "Choose the correct option: 'One of the girls ___ missing.'", "o": ["are", "were", "is", "have been"], "a": 2, "e": "The subject is 'one', which is singular, so 'is' is correct.", "d": 2},
    {"t": "Select the correct form: 'The news ___ good today.'", "o": ["are", "is", "were", "have been"], "a": 1, "e": "'News' is an uncountable noun and takes a singular verb.", "d": 2},
    {"t": "Choose the correct option: 'Each of the students ___ a book.'", "o": ["have", "are having", "has", "were having"], "a": 2, "e": "'Each' is singular, so it takes 'has'.", "d": 2},
    {"t": "Select the correct form: 'Ten thousand naira ___ a lot of money.'", "o": ["are", "is", "were", "have been"], "a": 1, "e": "Sums of money treated as a single amount take a singular verb.", "d": 2},
    {"t": "Choose the correct option: 'Either John or his friends ___ to blame.'", "o": ["is", "are", "was", "has been"], "a": 1, "e": "With 'either...or', the verb agrees with the nearer subject 'friends' (plural).", "d": 3},
    {"t": "Select the correct form: 'The pair of shoes ___ expensive.'", "o": ["are", "is", "were", "have been"], "a": 1, "e": "'Pair' is the subject and is singular, so 'is' is correct.", "d": 2},
    {"t": "Choose the correct option: 'Everyone ___ invited to the party.'", "o": ["are", "were", "is", "have been"], "a": 2, "e": "'Everyone' is an indefinite singular pronoun, taking 'is'.", "d": 2},
    {"t": "Select the correct form: 'The number of students ___ increasing.'", "o": ["are", "is", "were", "have been"], "a": 1, "e": "'The number' is singular, so 'is' is correct. ('A number of' would be plural.)", "d": 3},
    {"t": "Choose the correct option: 'Politics ___ a difficult subject.'", "o": ["are", "were", "is", "have been"], "a": 2, "e": "'Politics' (as a field of study) takes a singular verb.", "d": 2},
    {"t": "Select the correct form: 'I ___ him yesterday.'", "o": ["see", "saw", "seen", "have seen"], "a": 1, "e": "A completed action in the past ('yesterday') takes the simple past 'saw'.", "d": 1},
    {"t": "Choose the correct option: 'She ___ to school every day.'", "o": ["go", "goes", "going", "gone"], "a": 1, "e": "Third person singular present simple takes 'goes'.", "d": 1},
    {"t": "Select the correct form: 'They have ___ their homework.'", "o": ["do", "did", "done", "doing"], "a": 2, "e": "After 'have', the past participle 'done' is used.", "d": 1},
    {"t": "Choose the correct option: 'By next year, I ___ for ten years.'", "o": ["work", "will have worked", "worked", "working"], "a": 1, "e": "The future perfect 'will have worked' expresses completion before a future point.", "d": 3},
    {"t": "Select the correct form: 'He ___ when the rain started.'", "o": ["walk", "was walking", "walks", "walked"], "a": 1, "e": "Past continuous 'was walking' is used for an action in progress when another interrupted it.", "d": 2},
    {"t": "Choose the correct option: 'I have been living here ___ 2010.'", "o": ["for", "since", "from", "during"], "a": 1, "e": "'Since' is used with a specific starting point in time (2010).", "d": 2},
    {"t": "Select the correct form: 'She has been waiting ___ two hours.'", "o": ["since", "for", "during", "by"], "a": 1, "e": "'For' is used with a duration of time (two hours).", "d": 2},
    {"t": "Choose the correct option: 'The children ___ playing when I arrived.'", "o": ["is", "was", "were", "has been"], "a": 2, "e": "'Children' is plural, so the past continuous takes 'were'.", "d": 1},
    {"t": "Select the correct form: 'If I ___ rich, I would travel.'", "o": ["am", "were", "is", "be"], "a": 1, "e": "The unreal conditional uses the subjunctive 'were' for all persons.", "d": 3},

    # ── Parts of speech & structure ──
    {"t": "Identify the part of speech of the underlined word: 'She runs FAST.'", "o": ["Adjective", "Adverb", "Noun", "Verb"], "a": 1, "e": "'Fast' modifies the verb 'runs', so it is an adverb.", "d": 2},
    {"t": "In 'The quick brown fox', the word 'quick' is a(n):", "o": ["Noun", "Verb", "Adjective", "Adverb"], "a": 2, "e": "'Quick' describes the noun 'fox', so it is an adjective.", "d": 1},
    {"t": "Identify the part of speech of the underlined word: 'He spoke to the CROWD.'", "o": ["Verb", "Noun", "Adjective", "Adverb"], "a": 1, "e": "'Crowd' is a thing/person named, so it is a noun.", "d": 1},
    {"t": "In 'She sang beautifully', the word 'beautifully' is a(n):", "o": ["Adjective", "Noun", "Adverb", "Pronoun"], "a": 2, "e": "'Beautifully' modifies the verb 'sang', making it an adverb.", "d": 1},
    {"t": "Identify the part of speech: 'They will arrive SOON.'", "o": ["Adjective", "Adverb", "Preposition", "Conjunction"], "a": 1, "e": "'Soon' tells when, modifying the verb; it is an adverb of time.", "d": 2},
    {"t": "In 'The book ON the table is mine', 'on' is a:", "o": ["Conjunction", "Preposition", "Adverb", "Adjective"], "a": 1, "e": "'On' shows the relationship between 'book' and 'table', so it is a preposition.", "d": 1},
    {"t": "Identify the part of speech: 'AND' in 'I eat and sleep.'", "o": ["Preposition", "Adverb", "Conjunction", "Interjection"], "a": 2, "e": "'And' joins two words/clauses, so it is a conjunction.", "d": 1},
    {"t": "In 'She is a doctor', the word 'is' is a:", "o": ["Main verb", "Linking verb", "Auxiliary only", "Adverb"], "a": 1, "e": "'Is' links the subject to its complement, so it is a linking verb.", "d": 2},
    {"t": "Identify the part of speech: 'WOW! That is amazing.'", "o": ["Noun", "Interjection", "Adjective", "Adverb"], "a": 1, "e": "'Wow!' expresses sudden emotion, making it an interjection.", "d": 1},
    {"t": "In 'He gave HER the book', 'her' is a:", "o": ["Possessive adjective", "Object pronoun", "Subject pronoun", "Reflexive pronoun"], "a": 1, "e": "'Her' is the indirect object here, functioning as an object pronoun.", "d": 2},
    {"t": "Choose the correct option: 'Neither the teacher nor the students ___ ready.'", "o": ["is", "was", "are", "has been"], "a": 2, "e": "With 'neither...nor', the verb agrees with the nearer subject 'students' (plural).", "d": 3},
    {"t": "Select the correct form: 'The man, together with his sons, ___ arrived.'", "o": ["have", "are", "has", "were"], "a": 2, "e": "'Together with' does not make the subject plural; the subject is 'the man' (singular).", "d": 3},
    {"t": "Choose the correct option: 'I look forward to ___ from you.'", "o": ["hear", "hearing", "heard", "hears"], "a": 1, "e": "After the preposition 'to' in this phrase, the gerund 'hearing' is used.", "d": 2},
    {"t": "Select the correct form: 'She is good ___ mathematics.'", "o": ["in", "on", "at", "for"], "a": 2, "e": "The correct preposition after 'good' is 'at'.", "d": 1},
    {"t": "Choose the correct option: 'He is interested ___ music.'", "o": ["at", "on", "in", "with"], "a": 2, "e": "'Interested' takes the preposition 'in'.", "d": 1},
    {"t": "Select the correct form: 'We arrived ___ the station at noon.'", "o": ["to", "at", "on", "in"], "a": 1, "e": "'Arrive at' is used for a specific point or place.", "d": 2},
    {"t": "Choose the correct option: 'She is afraid ___ dogs.'", "o": ["of", "from", "with", "by"], "a": 0, "e": "'Afraid' takes the preposition 'of'.", "d": 1},
    {"t": "Select the correct form: 'He complained ___ the noise.'", "o": ["for", "about", "on", "at"], "a": 1, "e": "'Complain about' is the standard collocation.", "d": 2},
    {"t": "Choose the correct option: 'I prefer tea ___ coffee.'", "o": ["than", "to", "over", "from"], "a": 1, "e": "'Prefer X to Y' is the correct structure.", "d": 2},
    {"t": "Select the correct form: 'She is married ___ a doctor.'", "o": ["with", "to", "for", "by"], "a": 1, "e": "'Married to' is the standard collocation.", "d": 2},

    # ── Sentence types ──
    {"t": "What type of sentence is: 'The sun rises in the east.'?", "o": ["Compound", "Complex", "Simple", "Compound-complex"], "a": 2, "e": "It has one independent clause with one subject and predicate: a simple sentence.", "d": 1},
    {"t": "'I wanted to go, but it was raining.' is a:", "o": ["Simple sentence", "Compound sentence", "Complex sentence", "Fragment"], "a": 1, "e": "Two independent clauses joined by 'but' form a compound sentence.", "d": 2},
    {"t": "'Although he was tired, he finished the work.' is a:", "o": ["Simple sentence", "Compound sentence", "Complex sentence", "Compound-complex sentence"], "a": 2, "e": "It has one independent clause and one dependent clause: a complex sentence.", "d": 2},
    {"t": "'She laughed and the baby clapped.' is a:", "o": ["Simple sentence", "Compound sentence", "Complex sentence", "Phrase"], "a": 1, "e": "Two independent clauses joined by 'and' make a compound sentence.", "d": 2},
    {"t": "Identify the sentence type: 'Because it was late, we left, and we went home.'", "o": ["Simple", "Compound", "Complex", "Compound-complex"], "a": 3, "e": "It has a dependent clause plus two independent clauses: compound-complex.", "d": 3},
    {"t": "Which of these is a simple sentence?", "o": ["He ran fast and won.", "He ran fast, but he lost.", "Because he ran fast, he won.", "He ran fast and he won the race."], "a": 0, "e": "A simple sentence has one subject and a compound predicate; 'He ran fast and won' has one clause.", "d": 3},
    {"t": "'Stop!' is which kind of sentence by function?", "o": ["Declarative", "Interrogative", "Imperative", "Exclamatory"], "a": 2, "e": "'Stop!' gives a command, so it is imperative.", "d": 1},
    {"t": "'What a beautiful day!' is a(n) ___ sentence.", "o": ["Declarative", "Interrogative", "Imperative", "Exclamatory"], "a": 3, "e": "It expresses strong emotion, so it is exclamatory.", "d": 1},
    {"t": "'Did you finish the test?' is a(n) ___ sentence.", "o": ["Declarative", "Interrogative", "Imperative", "Exclamatory"], "a": 1, "e": "It asks a question, so it is interrogative.", "d": 1},
    {"t": "'The meeting starts at nine.' is a(n) ___ sentence.", "o": ["Declarative", "Interrogative", "Imperative", "Exclamatory"], "a": 0, "e": "It makes a statement, so it is declarative.", "d": 1},
    {"t": "Identify the main clause in: 'When the bell rang, the students rushed out.'", "o": ["When the bell rang", "the students rushed out", "When the bell", "rushed out"], "a": 1, "e": "'The students rushed out' can stand alone, so it is the main (independent) clause.", "d": 2},
    {"t": "In 'If you study hard, you will pass', the subordinate clause is:", "o": ["you will pass", "If you study hard", "study hard", "you will pass the exam"], "a": 1, "e": "'If you study hard' cannot stand alone; it is the subordinate (dependent) clause.", "d": 2},
    {"t": "A sentence that contains two or more independent clauses and at least one dependent clause is:", "o": ["Simple", "Compound", "Complex", "Compound-complex"], "a": 3, "e": "That is the definition of a compound-complex sentence.", "d": 2},
    {"t": "Which sentence is correctly punctuated?", "o": ["He asked, are you ready?", "He asked 'are you ready?'", "He asked, 'Are you ready?'", "He asked are you ready?"], "a": 2, "e": "Direct speech needs a comma before the quote and a capital letter inside it.", "d": 2},

    # ── Punctuation & spelling ──
    {"t": "Choose the correctly spelt word.", "o": ["Occurence", "Ocurrence", "Occurrence", "Occurencee"], "a": 2, "e": "The correct spelling is 'occurrence' (double c, double r).", "d": 2},
    {"t": "Select the correctly spelt word.", "o": ["Neccessary", "Necessary", "Necesary", "Necassary"], "a": 1, "e": "'Necessary' has one c and double s.", "d": 2},
    {"t": "Choose the correctly spelt word.", "o": ["Seperate", "Separate", "Sepparate", "Separet"], "a": 1, "e": "The correct spelling is 'separate'.", "d": 1},
    {"t": "Select the correctly spelt word.", "o": ["Recieve", "Receive", "Receeve", "Recive"], "a": 1, "e": "'Receive' follows the 'i before e except after c' rule.", "d": 2},
    {"t": "Choose the correctly spelt word.", "o": ["Definately", "Definitely", "Definitly", "Definetely"], "a": 1, "e": "The correct spelling is 'definitely'.", "d": 2},
    {"t": "Select the correctly spelt word.", "o": ["Accomodation", "Accommodation", "Acomodation", "Accommodattion"], "a": 1, "e": "'Accommodation' has double c and double m.", "d": 2},
    {"t": "Choose the correctly spelt word.", "o": ["Government", "Goverment", "Governement", "Govermnent"], "a": 0, "e": "The correct spelling is 'government'.", "d": 1},
    {"t": "Select the correctly spelt word.", "o": ["Embarass", "Embarrass", "Embaras", "Embarras"], "a": 1, "e": "'Embarrass' has double r and double s.", "d": 2},
    {"t": "Choose the correctly spelt word.", "o": ["Maintainance", "Maintenance", "Maintenence", "Maintanance"], "a": 1, "e": "The correct spelling is 'maintenance'.", "d": 2},
    {"t": "Select the correctly spelt word.", "o": ["Privilege", "Priviledge", "Privelege", "Priveledge"], "a": 0, "e": "The correct spelling is 'privilege' (no 'd').", "d": 2},
    {"t": "Which sentence uses the apostrophe correctly?", "o": ["The boys' books are here.", "The boy's are here.", "The boys book's are here.", "The boy's books are here's."], "a": 0, "e": "'Boys'' shows plural possessive (books of the boys).", "d": 2},
    {"t": "Choose the correctly punctuated sentence.", "o": ["I need to buy eggs milk and bread.", "I need to buy eggs, milk, and bread.", "I need to buy, eggs milk and bread.", "I need, to buy eggs milk and bread."], "a": 1, "e": "Items in a list are separated by commas.", "d": 1},
    {"t": "Which sentence correctly uses a semicolon?", "o": ["He was tired; so he slept.", "He was tired; he slept.", "He; was tired he slept.", "He was tired, he; slept."], "a": 1, "e": "A semicolon joins two related independent clauses without a conjunction.", "d": 2},
    {"t": "Select the correct use of 'their', 'there' or 'they're'.", "o": ["Their going home now.", "There going home now.", "They're going home now.", "They going home now."], "a": 2, "e": "'They're' is the contraction of 'they are'.", "d": 2},
    {"t": "Which word completes the sentence correctly: 'It's ___ book.'", "o": ["your", "you're", "you", "yours"], "a": 0, "e": "'Your' is the possessive adjective needed before the noun 'book'.", "d": 2},

    # ── Oral forms: vowels & consonants ──
    {"t": "How many vowel sounds are there in the English language?", "o": ["5", "12", "20", "26"], "a": 2, "e": "English has 20 vowel sounds (12 monophthongs and 8 diphthongs).", "d": 2},
    {"t": "How many consonant sounds are there in English?", "o": ["20", "24", "26", "21"], "a": 1, "e": "English has 24 consonant sounds.", "d": 2},
    {"t": "The word 'ship' contains which vowel sound?", "o": ["Long /iː/", "Short /ɪ/", "Long /æ/", "Short /ʌ/"], "a": 1, "e": "'Ship' has the short vowel /ɪ/, as in 'sit'.", "d": 2},
    {"t": "The vowel sound in 'seat' is a:", "o": ["Short vowel", "Long vowel", "Diphthong", "Consonant"], "a": 1, "e": "'Seat' contains the long vowel /iː/.", "d": 2},
    {"t": "Which of these words contains a diphthong?", "o": ["Cat", "Boy", "Bit", "Cup"], "a": 1, "e": "'Boy' contains the diphthong /ɔɪ/.", "d": 2},
    {"t": "The word 'chair' begins with which consonant sound?", "o": ["/k/", "/ʃ/", "/tʃ/", "/s/"], "a": 2, "e": "'Chair' begins with the affricate /tʃ/.", "d": 2},
    {"t": "The final sound in 'sing' is:", "o": ["/g/", "/n/", "/ŋ/", "/ng/"], "a": 2, "e": "'Sing' ends with the velar nasal /ŋ/.", "d": 2},
    {"t": "Which word has the /θ/ (voiceless 'th') sound?", "o": ["This", "Think", "They", "Mother"], "a": 1, "e": "'Think' has the voiceless /θ/; 'this' and 'they' have voiced /ð/.", "d": 2},
    {"t": "The word 'zoo' begins with a:", "o": ["Voiceless sound", "Voiced sound", "Vowel", "Nasal"], "a": 1, "e": "'Zoo' begins with the voiced /z/.", "d": 2},
    {"t": "In 'church', the initial sound is a(n):", "o": ["Plosive", "Affricate", "Fricative", "Nasal"], "a": 1, "e": "The /tʃ/ in 'church' is an affricate.", "d": 2},
    {"t": "The sound /b/ in 'bat' is classified as a:", "o": ["Fricative", "Plosive", "Nasal", "Lateral"], "a": 1, "e": "/b/ is a bilabial plosive (stop).", "d": 2},
    {"t": "The sound /s/ in 'sun' is a:", "o": ["Plosive", "Nasal", "Fricative", "Affricate"], "a": 2, "e": "/s/ is a voiceless alveolar fricative.", "d": 2},
    {"t": "Which word contains the /ʒ/ sound (as in 'measure')?", "o": ["Ship", "Vision", "Chair", "King"], "a": 1, "e": "'Vision' contains the voiced /ʒ/ sound.", "d": 2},
    {"t": "The 'l' in 'little' is a:", "o": ["Nasal", "Lateral", "Plosive", "Vowel"], "a": 1, "e": "/l/ is a lateral consonant, made with air flowing around the sides of the tongue.", "d": 2},
    {"t": "The word 'cat' contains how many consonant sounds?", "o": ["1", "2", "3", "4"], "a": 1, "e": "'Cat' has two consonants (/k/ and /t/) and one vowel.", "d": 2},

    # ── Oral forms: stress & intonation ──
    {"t": "In the word 'important', the primary stress falls on the:", "o": ["First syllable", "Second syllable", "Third syllable", "All syllables equally"], "a": 1, "e": "'imPORtant' — stress is on the second syllable.", "d": 2},
    {"t": "Which syllable is stressed in 'education'?", "o": ["e-", "du-", "ca-", "tion"], "a": 2, "e": "'eduCAtion' — primary stress is on the third syllable 'ca'.", "d": 2},
    {"t": "The word 'record' is stressed differently depending on whether it is used as a noun or a verb. As a NOUN, the stress is on the:", "o": ["First syllable", "Second syllable", "Both equally", "Neither"], "a": 0, "e": "Nouns take first-syllable stress (REcord); verbs take second (reCORD).", "d": 3},
    {"t": "In 'photograph', the stressed syllable is:", "o": ["PHO-", "to-", "graph", "Equal stress"], "a": 0, "e": "'PHOtograph' — stress is on the first syllable.", "d": 2},
    {"t": "Which word has its stress on the first syllable?", "o": ["Believe", "Teacher", "Police", "Machine"], "a": 1, "e": "'TEACHer' is stressed on the first syllable; the others on the second.", "d": 2},
    {"t": "The rise and fall of the pitch of the voice when speaking is called:", "o": ["Stress", "Intonation", "Rhyme", "Rhythm"], "a": 1, "e": "Intonation is the variation in pitch across speech.", "d": 1},
    {"t": "The pattern of stressed and unstressed syllables in poetry is called:", "o": ["Meter", "Rhyme", "Stanza", "Theme"], "a": 0, "e": "Meter is the rhythmic pattern of stressed/unstressed syllables.", "d": 2},
    {"t": "Which of the following words is a homophone of 'write'?", "o": ["Ride", "Right", "Rite (both b and c)", "Rate"], "a": 2, "e": "'Write', 'right' and 'rite' all sound alike but differ in spelling/meaning.", "d": 2},
    {"t": "A word that has the same spelling but different meanings is a:", "o": ["Homophone", "Homograph", "Synonym", "Antonym"], "a": 1, "e": "A homograph is spelt the same but has different meanings (e.g. 'bank').", "d": 2},
    {"t": "'Sea' and 'see' are examples of:", "o": ["Synonyms", "Homophones", "Homographs", "Antonyms"], "a": 1, "e": "They sound alike but differ in spelling and meaning: homophones.", "d": 1},
    {"t": "In a declarative statement, the intonation pattern is typically:", "o": ["Rising", "Falling", "Level", "Rising-falling"], "a": 1, "e": "Statements normally end with falling intonation.", "d": 2},
    {"t": "Yes/no questions typically end with ___ intonation.", "o": ["Falling", "Rising", "Level", "Monotone"], "a": 1, "e": "Yes/no questions use rising intonation at the end.", "d": 2},

    # ── Comprehension / vocabulary in context ──
    {"t": "In a passage, if an author describes a character as 'frugal', the character is:", "o": ["Wasteful", "Careful with money", "Dishonest", "Generous"], "a": 1, "e": "'Frugal' means economical and careful about spending.", "d": 2},
    {"t": "The primary purpose of a persuasive passage is to:", "o": ["Narrate a story", "Describe a place", "Convince the reader", "List facts only"], "a": 2, "e": "Persuasive writing aims to convince or persuade the reader.", "d": 2},
    {"t": "In comprehension, the main idea of a passage is best found by:", "o": ["Reading only the first word", "Identifying the central point the writer makes", "Counting paragraphs", "Ignoring the title"], "a": 1, "e": "The main idea is the central point or message of the passage.", "d": 2},
    {"t": "A summary of a passage should:", "o": ["Be longer than the original", "Include the key points only", "Copy sentences word-for-word", "Add the reader's opinion"], "a": 1, "e": "A summary condenses a passage to its key points without copying.", "d": 2},
    {"t": "The word 'emigrate' means to:", "o": ["Enter a country", "Leave one's country to live elsewhere", "Travel for fun", "Return home"], "a": 1, "e": "'Emigrate' means to leave one's country to settle in another.", "d": 2},
    {"t": "'Immigrate' means to:", "o": ["Leave a country", "Enter and settle in a new country", "Visit briefly", "Become a citizen automatically"], "a": 1, "e": "'Immigrate' means to come into a country to live there.", "d": 2},
    {"t": "Choose the correct option: 'The lecture was so boring that most students ___ off.'", "o": ["dozed", "dazed", "drowsed", "dozes"], "a": 0, "e": "'Dozed off' is the correct phrasal verb meaning to fall asleep briefly.", "d": 2},
    {"t": "Select the correct option: 'He was accused ___ stealing.'", "o": ["for", "of", "with", "about"], "a": 1, "e": "'Accused of' is the correct collocation.", "d": 2},
    {"t": "Choose the correct option: 'She was absorbed ___ her book.'", "o": ["in", "at", "on", "by"], "a": 0, "e": "'Absorbed in' is the standard collocation.", "d": 2},
    {"t": "Select the correct option: 'The boys were divided ___ two groups.'", "o": ["into", "in", "on", "with"], "a": 0, "e": "'Divided into' is the correct collocation.", "d": 1},
    {"t": "Choose the correct option: 'I am fed up ___ this noise.'", "o": ["of", "with", "by", "for"], "a": 1, "e": "'Fed up with' is the standard expression.", "d": 2},
    {"t": "Select the correct option: 'He congratulated her ___ her success.'", "o": ["for", "on", "at", "with"], "a": 1, "e": "'Congratulate someone on something' is correct.", "d": 2},
    {"t": "Choose the correct option: 'The teacher insisted ___ punctuality.'", "o": ["for", "on", "at", "in"], "a": 1, "e": "'Insist on' is the correct collocation.", "d": 2},
    {"t": "Select the correct option: 'We should always aim ___ excellence.'", "o": ["at", "for", "on", "to"], "a": 0, "e": "'Aim at' is the standard collocation.", "d": 2},
    {"t": "Choose the option nearest in meaning to 'candid' in: 'He gave a candid account of the event.'", "o": ["False", "Frank", "Brief", "Biased"], "a": 1, "e": "'Candid' here means frank and truthful.", "d": 2},
    {"t": "In the sentence 'The drought devastated the crops', 'devastated' means:", "o": ["Improved", "Destroyed", "Watered", "Harvested"], "a": 1, "e": "'Devastated' means ruined or destroyed completely.", "d": 2},
    {"t": "Choose the option nearest in meaning to the word in italics: 'His ARGUMENT was compelling.'", "o": ["Weak", "Convincing", "Long", "Confusing"], "a": 1, "e": "'Compelling' means convincing and persuasive.", "d": 2},
    {"t": "The word 'scanty' in 'scanty rainfall' means:", "o": ["Plentiful", "Meagre", "Heavy", "Regular"], "a": 1, "e": "'Scanty' means small or insufficient in amount; meagre.", "d": 2},
    {"t": "'The officer was impartial in his judgment.' 'Impartial' means:", "o": ["Biased", "Unfair", "Neutral", "Harsh"], "a": 2, "e": "'Impartial' means fair and unbiased; neutral.", "d": 2},
    {"t": "Choose the option that best completes: 'Her sudden wealth was ___ by envy among her peers.'", "o": ["welcomed", "greeted", "followed", "preceded"], "a": 2, "e": "'Followed by' fits the context: wealth then envy.", "d": 2},

    # ── More lexis & structure (mixed) ──
    {"t": "Choose the option nearest in meaning to 'procrastinate'.", "o": ["Hurry", "Delay", "Plan", "Decide"], "a": 1, "e": "'Procrastinate' means to delay or postpone action.", "d": 2},
    {"t": "'Ambiguous' most nearly means:", "o": ["Clear", "Having more than one possible meaning", "Exact", "Short"], "a": 1, "e": "'Ambiguous' means open to more than one interpretation.", "d": 2},
    {"t": "Choose the option nearest in meaning to 'concise'.", "o": ["Long-winded", "Brief and clear", "Detailed", "Boring"], "a": 1, "e": "'Concise' means giving much information clearly in few words.", "d": 2},
    {"t": "'Hostile' in 'a hostile environment' means:", "o": ["Friendly", "Unfriendly and harsh", "Comfortable", "Quiet"], "a": 1, "e": "'Hostile' means unfriendly, harsh, or adverse.", "d": 1},
    {"t": "Choose the option nearest in meaning to 'exhausted'.", "o": ["Rested", "Very tired", "Excited", "Hungry"], "a": 1, "e": "'Exhausted' means extremely tired.", "d": 1},
    {"t": "'Vanish' most nearly means:", "o": ["Appear", "Disappear", "Return", "Grow"], "a": 1, "e": "'Vanish' means to disappear suddenly.", "d": 1},
    {"t": "Choose the option nearest in meaning to 'triumph'.", "o": ["Defeat", "Victory", "Struggle", "Loss"], "a": 1, "e": "'Triumph' means a great victory or achievement.", "d": 1},
    {"t": "'Audacious' most nearly means:", "o": ["Cowardly", "Bold", "Timid", "Careful"], "a": 1, "e": "'Audacious' means daring and bold.", "d": 2},
    {"t": "Choose the option nearest in meaning to 'obstinate'.", "o": ["Flexible", "Stubborn", "Obedient", "Kind"], "a": 1, "e": "'Obstinate' means stubbornly refusing to change one's mind.", "d": 2},
    {"t": "'Serene' most nearly means:", "o": ["Noisy", "Calm", "Stormy", "Busy"], "a": 1, "e": "'Serene' means calm, peaceful, and untroubled.", "d": 1},
    {"t": "Choose the option opposite in meaning to 'acquit'.", "o": ["Free", "Convict", "Release", "Pardon"], "a": 1, "e": "'Acquit' means to declare innocent; opposite is 'convict'.", "d": 2},
    {"t": "The opposite of 'attract' is:", "o": ["Draw", "Repel", "Charm", "Pull"], "a": 1, "e": "'Attract' means to draw toward; opposite is 'repel'.", "d": 1},
    {"t": "Choose the option opposite in meaning to 'assemble'.", "o": ["Gather", "Disperse", "Build", "Collect"], "a": 1, "e": "'Assemble' means to gather; opposite is 'disperse'.", "d": 1},
    {"t": "The opposite of 'ancient' is:", "o": ["Old", "Modern", "Primitive", "Antique"], "a": 1, "e": "'Ancient' means very old; opposite is 'modern'.", "d": 1},
    {"t": "Choose the option opposite in meaning to 'confess'.", "o": ["Admit", "Deny", "Reveal", "Acknowledge"], "a": 1, "e": "'Confess' means to admit; opposite is 'deny'.", "d": 1},
    {"t": "The opposite of 'generous' is:", "o": ["Kind", "Stingy", "Giving", "Charitable"], "a": 1, "e": "'Generous' means freely giving; opposite is 'stingy'.", "d": 1},
    {"t": "Choose the option opposite in meaning to 'applaud'.", "o": ["Cheer", "Boo", "Praise", "Clap"], "a": 1, "e": "'Applaud' means to show approval; opposite is 'boo'.", "d": 1},
    {"t": "The opposite of 'arrival' is:", "o": ["Coming", "Departure", "Entry", "Advent"], "a": 1, "e": "'Arrival' means coming; opposite is 'departure'.", "d": 1},
    {"t": "Choose the option opposite in meaning to 'sorrow'.", "o": ["Sadness", "Joy", "Grief", "Pain"], "a": 1, "e": "'Sorrow' means sadness; opposite is 'joy'.", "d": 1},
    {"t": "The opposite of 'swift' is:", "o": ["Fast", "Slow", "Quick", "Rapid"], "a": 1, "e": "'Swift' means fast; opposite is 'slow'.", "d": 1},
    {"t": "Select the correctly punctuated sentence.", "o": ["Where are you going?", "Where are you going.", "Where, are you going?", "Where are you going?!"], "a": 0, "e": "A question must end with a single question mark.", "d": 1},
    {"t": "Choose the correct option: 'I ___ my keys; I can't find them anywhere.'", "o": ["lose", "have lost", "am losing", "lost yesterday"], "a": 1, "e": "The present perfect 'have lost' is used for a past action with present relevance.", "d": 2},
    {"t": "Select the correct form: 'By the time we arrived, the film ___.'", "o": ["started", "has started", "had started", "starts"], "a": 2, "e": "Past perfect 'had started' is used for an action completed before another past action.", "d": 2},
    {"t": "Choose the correct option: 'Hardly had he left ___ it began to rain.'", "o": ["than", "when", "then", "as"], "a": 1, "e": "'Hardly...when' is the correct correlative structure.", "d": 3},
    {"t": "Select the correct form: 'No sooner did she arrive ___ the meeting started.'", "o": ["when", "than", "then", "that"], "a": 1, "e": "'No sooner...than' is the correct correlative structure.", "d": 3},
    {"t": "Choose the correct option: 'Scarcely had we sat down ___ the lights went out.'", "o": ["than", "then", "when", "that"], "a": 2, "e": "'Scarcely...when' is the correct structure.", "d": 3},
    {"t": "Select the correct form: 'The boy, ___ father is a doctor, is my friend.'", "o": ["who", "whom", "whose", "which"], "a": 2, "e": "'Whose' shows possession (the boy's father).", "d": 2},
    {"t": "Choose the correct option: 'This is the house ___ I was born.'", "o": ["where", "which", "who", "whom"], "a": 0, "e": "'Where' refers to a place.", "d": 1},
    {"t": "Select the correct form: 'The man ___ you met is my uncle.'", "o": ["which", "whom", "whose", "what"], "a": 1, "e": "'Whom' is the object of 'met', referring to the man.", "d": 2},
    {"t": "Choose the correct option: 'I saw ___ interesting film yesterday.'", "o": ["a", "an", "the", "no article"], "a": 1, "e": "'An' is used before a vowel sound (interesting).", "d": 1},
    {"t": "Select the correct form: 'He is ___ honest man.'", "o": ["a", "an", "the", "no article"], "a": 1, "e": "'An' is used before a silent 'h' vowel sound (honest).", "d": 2},
    {"t": "Choose the correct option: 'She goes to ___ church every Sunday.'", "o": ["a", "an", "the", "no article"], "a": 2, "e": "'The' is used before places of regular institutional activity.", "d": 2},
    {"t": "Select the correct form: '___ Nile is the longest river in Africa.'", "o": ["A", "An", "The", "No article"], "a": 2, "e": "'The' is used before names of rivers.", "d": 1},
    {"t": "Choose the correct option: 'I enjoy ___ football.'", "o": ["play", "to play", "playing", "played"], "a": 2, "e": "'Enjoy' is followed by the gerund 'playing'.", "d": 2},
    {"t": "Select the correct form: 'He refused ___ the bribe.'", "o": ["accepting", "to accept", "accept", "accepted"], "a": 1, "e": "'Refuse' is followed by the infinitive 'to accept'.", "d": 2},
    {"t": "Choose the correct option: 'She suggested ___ early.'", "o": ["to leave", "leaving", "leave", "left"], "a": 1, "e": "'Suggest' is followed by the gerund 'leaving'.", "d": 2},
    {"t": "Select the correct form: 'I can't help ___ at his jokes.'", "o": ["to laugh", "laughing", "laugh", "laughed"], "a": 1, "e": "'Can't help' is followed by the gerund 'laughing'.", "d": 2},
    {"t": "Choose the correct option: 'It is no use ___ over spilt milk.'", "o": ["cry", "to cry", "crying", "cried"], "a": 2, "e": "'It is no use' is followed by the gerund 'crying'.", "d": 2},
    {"t": "Select the correct form: 'He is used to ___ late.'", "o": ["work", "working", "worked", "works"], "a": 1, "e": "'Be used to' is followed by the gerund 'working'.", "d": 2},
    {"t": "Choose the correct option: 'Neither of them ___ willing to help.'", "o": ["are", "were", "is", "have been"], "a": 2, "e": "'Neither' is singular, so 'is' is correct.", "d": 2},
    {"t": "Select the correct form: 'A lot of money ___ been spent.'", "o": ["have", "has", "are", "were"], "a": 1, "e": "'A lot of money' is uncountable and singular, taking 'has'.", "d": 2},
    {"t": "Choose the correct option: 'The scissors ___ on the table.'", "o": ["is", "are", "was", "has been"], "a": 1, "e": "'Scissors' is plural and always takes a plural verb.", "d": 2},
    {"t": "Select the correct form: 'Measles ___ a contagious disease.'", "o": ["are", "were", "is", "have been"], "a": 2, "e": "'Measles' (the disease) is singular, taking 'is'.", "d": 2},
    {"t": "Choose the correct option: 'The police ___ investigating the case.'", "o": ["is", "was", "are", "has been"], "a": 2, "e": "'Police' is a collective plural noun, taking 'are'.", "d": 2},
    {"t": "Select the correct form: 'This is one of the books that ___ missing.'", "o": ["is", "are", "was", "has been"], "a": 1, "e": "The relative clause refers to 'books' (plural), so 'are' is correct.", "d": 3},
    {"t": "Choose the option nearest in meaning to 'curtail'.", "o": ["Extend", "Reduce", "Support", "Begin"], "a": 1, "e": "'Curtail' means to reduce or cut short.", "d": 2},
    {"t": "'Alleviate' most nearly means:", "o": ["Worsen", "Ease", "Cause", "Ignore"], "a": 1, "e": "'Alleviate' means to make (pain/suffering) less severe.", "d": 2},
    {"t": "Choose the option nearest in meaning to 'abhor'.", "o": ["Love", "Detest", "Tolerate", "Admire"], "a": 1, "e": "'Abhor' means to regard with disgust and hatred.", "d": 2},
    {"t": "'Elated' most nearly means:", "o": ["Sad", "Very happy", "Angry", "Tired"], "a": 1, "e": "'Elated' means ecstatically happy.", "d": 2},
    {"t": "Choose the option nearest in meaning to 'tedious'.", "o": ["Exciting", "Boring and long", "Short", "Simple"], "a": 1, "e": "'Tedious' means too long, slow, or dull; boring.", "d": 2},
    {"t": "'Punctual' most nearly means:", "o": ["Late", "On time", "Early", "Absent"], "a": 1, "e": "'Punctual' means happening or doing something at the agreed time.", "d": 1},
    {"t": "Choose the option opposite in meaning to 'ample'.", "o": ["Enough", "Insufficient", "Plentiful", "Large"], "a": 1, "e": "'Ample' means plenty; opposite is 'insufficient'.", "d": 2},
    {"t": "The opposite of 'commence' is:", "o": ["Start", "Conclude", "Begin", "Initiate"], "a": 1, "e": "'Commence' means to begin; opposite is 'conclude'.", "d": 1},
    {"t": "Choose the option opposite in meaning to 'chaos'.", "o": ["Disorder", "Order", "Confusion", "Mess"], "a": 1, "e": "'Chaos' means complete disorder; opposite is 'order'.", "d": 1},
    {"t": "The opposite of 'ignorant' is:", "o": ["Unaware", "Knowledgeable", "Foolish", "Blind"], "a": 1, "e": "'Ignorant' means lacking knowledge; opposite is 'knowledgeable'.", "d": 1},
    {"t": "Choose the option opposite in meaning to 'rigid'.", "o": ["Stiff", "Flexible", "Firm", "Hard"], "a": 1, "e": "'Rigid' means stiff/inflexible; opposite is 'flexible'.", "d": 1},
    {"t": "The opposite of 'tame' is:", "o": ["Gentle", "Wild", "Domestic", "Calm"], "a": 1, "e": "'Tame' means domesticated; opposite is 'wild'.", "d": 1},
    {"t": "Choose the option that best completes: 'The two brothers are as different as chalk and ___.'", "o": ["stone", "cheese", "water", "sand"], "a": 1, "e": "The idiom is 'as different as chalk and cheese'.", "d": 2},
    {"t": "Select the correct option: 'The project was completed in the nick of ___.'", "o": ["time", "clock", "hour", "day"], "a": 0, "e": "The idiom is 'in the nick of time' (just in time).", "d": 2},
    {"t": "Choose the correct option: 'He turned a deaf ___ to their pleas.'", "o": ["ear", "hand", "eye", "head"], "a": 0, "e": "The idiom is 'turned a deaf ear' (refused to listen).", "d": 2},
    {"t": "Select the correct option: 'She is the apple of her father's ___.'", "o": ["eye", "heart", "mind", "soul"], "a": 0, "e": "The idiom is 'the apple of one's eye' (a cherished person).", "d": 2},
    {"t": "Choose the correct option: 'We must learn to make ___ meet.'", "o": ["ends", "money", "ways", "plans"], "a": 0, "e": "The idiom is 'make ends meet' (manage on limited income).", "d": 2},
    {"t": "Select the correct option: 'His advice fell on deaf ___.'", "o": ["ears", "eyes", "heads", "minds"], "a": 0, "e": "The idiom is 'fell on deaf ears' (was ignored).", "d": 2},
]

build("eng", "English Language", QUESTIONS[:200])
