from _common import build

QUESTIONS = [
    # ── Genres & general principles ──
    {"t": "The three main genres of literature are:", "o": ["Prose, poetry and drama", "Novel, story, essay", "Tragedy, comedy, satire", "Fiction, non-fiction, myth"], "a": 0, "e": "Literature divides into prose, poetry and drama.", "d": 1},
    {"t": "A literary work written in ordinary (non-verse) language is:", "o": ["Poetry", "Prose", "Drama", "Lyric"], "a": 1, "e": "Prose uses ordinary language.", "d": 1},
    {"t": "A literary work written in verse is:", "o": ["Prose", "Poetry", "Drama", "Essay"], "a": 1, "e": "Poetry is written in verse.", "d": 1},
    {"t": "A literary work intended to be performed on stage is:", "o": ["Prose", "Poetry", "Drama", "Novel"], "a": 2, "e": "Drama is written for performance.", "d": 1},
    {"t": "The term 'literature' broadly means:", "o": ["Only written poems", "Creative written or oral works of artistic value", "Only novels", "Only plays"], "a": 1, "e": "Literature is artistic written/oral expression.", "d": 1},
    {"t": "Oral literature is literature that is:", "o": ["Written", "Passed down by word of mouth", "Printed", "Translated"], "a": 1, "e": "Oral literature is transmitted by speech.", "d": 1},
    {"t": "A genre is a:", "o": ["Type or category of literature", "Single poem", "Figure of speech", "Stanza"], "a": 0, "e": "A genre is a category of literature.", "d": 1},
    {"t": "Fiction refers to writing that is:", "o": ["Factual", "Imaginary/invented", "Historical only", "Autobiographical"], "a": 1, "e": "Fiction is invented narrative.", "d": 1},
    {"t": "Non-fiction is writing based on:", "o": ["Imagination", "Facts and reality", "Fantasy", "Myth"], "a": 1, "e": "Non-fiction deals with real events/people.", "d": 1},
    {"t": "A short story is:", "o": ["A long novel", "A brief work of prose fiction", "A poem", "A play"], "a": 1, "e": "A short story is brief prose fiction.", "d": 1},
    {"t": "The author of a play is called a:", "o": ["Poet", "Playwright", "Novelist", "Essayist"], "a": 1, "e": "A playwright writes plays.", "d": 1},
    {"t": "The author of a poem is called a:", "o": ["Playwright", "Poet", "Novelist", "Critic"], "a": 1, "e": "A poet writes poems.", "d": 1},
    {"t": "The author of a novel is called a:", "o": ["Poet", "Novelist", "Playwright", "Dramatist"], "a": 1, "e": "A novelist writes novels.", "d": 1},

    # ── Drama ──
    {"t": "A drama that ends unhappily with the fall of the hero is a:", "o": ["Comedy", "Tragedy", "Farce", "Melodrama"], "a": 1, "e": "A tragedy ends with the hero's downfall.", "d": 1},
    {"t": "A drama that ends happily is a:", "o": ["Tragedy", "Comedy", "Tragicomedy", "Melodrama"], "a": 1, "e": "A comedy ends happily.", "d": 1},
    {"t": "A play that mixes tragic and comic elements is a:", "o": ["Comedy", "Tragicomedy", "Farce", "Satire"], "a": 1, "e": "Tragicomedy blends both.", "d": 1},
    {"t": "The major division of a play is an:", "o": ["Scene", "Act", "Stanza", "Chapter"], "a": 1, "e": "Plays are divided into acts.", "d": 1},
    {"t": "The subdivision of an act is a:", "o": ["Stanza", "Scene", "Chapter", "Canto"], "a": 1, "e": "Acts divide into scenes.", "d": 1},
    {"t": "The words spoken by characters in a play are:", "o": ["Dialogue", "Monologue", "Narration", "Stage direction"], "a": 0, "e": "Dialogue is characters' spoken words.", "d": 1},
    {"t": "A long speech by one character alone on stage is a:", "o": ["Dialogue", "Soliloquy", "Duologue", "Aside"], "a": 1, "e": "A soliloquy is a solo speech.", "d": 1},
    {"t": "A remark by a character meant to be heard by the audience but not other characters is an:", "o": ["Soliloquy", "Aside", "Monologue", "Dialogue"], "a": 1, "e": "An aside is heard only by the audience.", "d": 1},
    {"t": "The instructions in a play about action and setting are:", "o": ["Dialogue", "Stage directions", "Soliloquy", "Plot"], "a": 1, "e": "Stage directions guide performance.", "d": 1},
    {"t": "The main character in a play or story is the:", "o": ["Antagonist", "Protagonist", "Foil", "Narrator"], "a": 1, "e": "The protagonist is the main character.", "d": 1},
    {"t": "The character who opposes the main character is the:", "o": ["Protagonist", "Antagonist", "Heroine", "Foil"], "a": 1, "e": "The antagonist opposes the protagonist.", "d": 1},
    {"t": "The leading character who suffers a downfall in a tragedy is the:", "o": ["Villain", "Tragic hero", "Foil", "Clown"], "a": 1, "e": "The tragic hero suffers downfall.", "d": 1},
    {"t": "The sequence of events in a play or story is the:", "o": ["Theme", "Plot", "Setting", "Style"], "a": 1, "e": "The plot is the sequence of events.", "d": 1},
    {"t": "The time and place of a literary work is its:", "o": ["Theme", "Setting", "Plot", "Tone"], "a": 1, "e": "Setting = time and place.", "d": 1},
    {"t": "The central idea or message of a work is its:", "o": ["Plot", "Theme", "Setting", "Character"], "a": 1, "e": "Theme is the central message.", "d": 1},
    {"t": "The group of actors in a play is the:", "o": ["Audience", "Cast", "Crew", "Chorus"], "a": 1, "e": "The cast are the actors.", "d": 1},
    {"t": "The audience is the group of people who:", "o": ["Perform a play", "Watch a play", "Write a play", "Direct a play"], "a": 1, "e": "The audience watches the play.", "d": 1},
    {"t": "The director of a play is the person who:", "o": ["Writes it", "Supervises its performance", "Watches it", "Acts in it"], "a": 1, "e": "The director supervises production.", "d": 1},
    {"t": "A drama that ridicules human weakness to bring about reform is a:", "o": ["Farce", "Satire", "Melodrama", "Romance"], "a": 1, "e": "Satire ridicules to reform.", "d": 1},
    {"t": "A farce is a comedy characterised by:", "o": ["Serious themes", "Exaggerated, absurd situations", "Tragedy", "Realism"], "a": 1, "e": "Farce uses absurd, exaggerated situations.", "d": 1},

    # ── Prose ──
    {"t": "A long prose narrative is a:", "o": ["Short story", "Novel", "Poem", "Play"], "a": 1, "e": "A novel is a long prose narrative.", "d": 1},
    {"t": "A novella is:", "o": ["Longer than a novel", "Shorter than a novel but longer than a short story", "A poem", "A play"], "a": 1, "e": "A novella is mid-length fiction.", "d": 1},
    {"t": "The person who tells the story is the:", "o": ["Author", "Narrator", "Protagonist", "Editor"], "a": 1, "e": "The narrator tells the story.", "d": 1},
    {"t": "The first-person point of view uses the pronoun:", "o": ["He", "I", "They", "She"], "a": 1, "e": "First person uses 'I'.", "d": 1},
    {"t": "The third-person point of view uses pronouns like:", "o": ["I", "He/she/they", "We", "You"], "a": 1, "e": "Third person uses he/she/they.", "d": 1},
    {"t": "An all-knowing narrator is said to be:", "o": ["Limited", "Omniscient", "Unreliable", "First-person"], "a": 1, "e": "An omniscient narrator knows everything.", "d": 1},
    {"t": "The sequence of events in a story is the:", "o": ["Theme", "Plot", "Setting", "Style"], "a": 1, "e": "Plot is the sequence of events.", "d": 1},
    {"t": "The turning point of a story is the:", "o": ["Exposition", "Climax", "Denouement", "Falling action"], "a": 1, "e": "The climax is the turning point.", "d": 1},
    {"t": "The resolution at the end of a story is the:", "o": ["Exposition", "Denouement", "Climax", "Conflict"], "a": 1, "e": "The denouement resolves the plot.", "d": 1},
    {"t": "The beginning of a story that introduces characters and setting is the:", "o": ["Climax", "Exposition", "Resolution", "Conflict"], "a": 1, "e": "Exposition introduces the story's world.", "d": 1},
    {"t": "The struggle between opposing forces in a story is the:", "o": ["Theme", "Conflict", "Setting", "Style"], "a": 1, "e": "Conflict is the central struggle.", "d": 1},
    {"t": "A conflict between a character and another character is:", "o": ["Internal conflict", "External conflict", "Man vs self", "No conflict"], "a": 1, "e": "Character vs character is external conflict.", "d": 1},
    {"t": "A conflict within a character's mind is:", "o": ["External", "Internal conflict", "Social", "Physical"], "a": 1, "e": "Man vs self is internal conflict.", "d": 1},
    {"t": "A flashback is a:", "o": ["Look into the future", "Return to an earlier time in the story", "Jump in plot", "Type of ending"], "a": 1, "e": "A flashback goes back in time.", "d": 1},
    {"t": "Foreshadowing is:", "o": ["A flashback", "A hint of what is to come", "The climax", "The theme"], "a": 1, "e": "Foreshadowing hints at future events.", "d": 1},
    {"t": "A person's life story written by themselves is a(n):", "o": ["Biography", "Autobiography", "Novel", "Essay"], "a": 1, "e": "An autobiography is self-written life story.", "d": 1},
    {"t": "A person's life story written by another is a:", "o": ["Autobiography", "Biography", "Memoir", "Novel"], "a": 1, "e": "A biography is written by another person.", "d": 1},
    {"t": "An essay is a:", "o": ["Long novel", "Short piece of prose on a subject", "Poem", "Play"], "a": 1, "e": "An essay is a short prose composition.", "d": 1},
    {"t": "A fable is a story that:", "o": ["Is always true", "Teaches a moral, often with animals", "Is a poem", "Is a play"], "a": 1, "e": "Fables teach morals, often using animals.", "d": 1},
    {"t": "A myth is a traditional story that:", "o": ["Explains natural phenomena or origins", "Is factual", "Is a poem", "Is a novel"], "a": 0, "e": "Myths explain origins/phenomena.", "d": 1},
    {"t": "A legend is a story:", "o": ["Based on history but exaggerated", "Purely factual", "Purely imaginary", "A poem"], "a": 0, "e": "Legends have a historical basis with exaggeration.", "d": 1},
    {"t": "An allegory is a story with:", "o": ["One meaning", "A hidden/secondary meaning", "No meaning", "Only dialogue"], "a": 1, "e": "Allegories carry hidden meanings.", "d": 1},
    {"t": "A parable is a short story that:", "o": ["Is a poem", "Illustrates a moral or spiritual lesson", "Is a play", "Has no lesson"], "a": 1, "e": "Parables teach moral/spiritual lessons.", "d": 1},
    {"t": "An epic is a:", "o": ["Short poem", "Long narrative poem about heroic deeds", "Novel", "Play"], "a": 1, "e": "An epic is a long heroic narrative poem.", "d": 1},
    {"t": "A satire is a work that:", "o": ["Praises society", "Ridicules vices and follies", "Is always tragic", "Is factual"], "a": 1, "e": "Satire mocks vices/follies.", "d": 1},

    # ── Poetry ──
    {"t": "A line of poetry is called a:", "o": ["Stanza", "Verse", "Canto", "Line"], "a": 1, "e": "A line of poetry is a verse.", "d": 1},
    {"t": "A group of lines in a poem is a:", "o": ["Verse", "Stanza", "Canto", "Line"], "a": 1, "e": "A stanza is a group of lines.", "d": 1},
    {"t": "A stanza of two lines is a:", "o": ["Tercet", "Couplet", "Quatrain", "Sestet"], "a": 1, "e": "A couplet is two lines.", "d": 1},
    {"t": "A stanza of four lines is a:", "o": ["Couplet", "Quatrain", "Tercet", "Octave"], "a": 1, "e": "A quatrain is four lines.", "d": 1},
    {"t": "A stanza of three lines is a:", "o": ["Couplet", "Tercet", "Quatrain", "Sestet"], "a": 1, "e": "A tercet is three lines.", "d": 1},
    {"t": "A poem of fourteen lines is a:", "o": ["Ballad", "Sonnet", "Ode", "Epic"], "a": 1, "e": "A sonnet has 14 lines.", "d": 1},
    {"t": "A poem that tells a story is a:", "o": ["Lyric", "Narrative poem", "Ode", "Elegy"], "a": 1, "e": "Narrative poems tell stories.", "d": 1},
    {"t": "A poem expressing personal feelings is a:", "o": ["Narrative", "Lyric", "Epic", "Ballad"], "a": 1, "e": "Lyrics express personal emotion.", "d": 1},
    {"t": "A poem mourning the dead is an:", "o": ["Ode", "Elegy", "Sonnet", "Ballad"], "a": 1, "e": "An elegy laments the dead.", "d": 1},
    {"t": "A poem of praise is an:", "o": ["Elegy", "Ode", "Satire", "Epigram"], "a": 1, "e": "An ode praises a person/thing.", "d": 1},
    {"t": "A short, witty poem is an:", "o": ["Ode", "Epigram", "Epic", "Elegy"], "a": 1, "e": "An epigram is short and witty.", "d": 1},
    {"t": "A long poem celebrating heroic deeds is an:", "o": ["Lyric", "Epic", "Sonnet", "Ode"], "a": 1, "e": "An epic celebrates heroic deeds.", "d": 1},
    {"t": "A poem with no regular rhyme or metre is:", "o": ["Blank verse", "Free verse", "Sonnet", "Ballad"], "a": 1, "e": "Free verse has no regular pattern.", "d": 1},
    {"t": "Unrhymed poetry written in iambic pentameter is:", "o": ["Free verse", "Blank verse", "Sonnet", "Ode"], "a": 1, "e": "Blank verse is unrhymed iambic pentameter.", "d": 1},
    {"t": "The repetition of initial consonant sounds is:", "o": ["Assonance", "Alliteration", "Consonance", "Onomatopoeia"], "a": 1, "e": "Alliteration repeats initial consonants.", "d": 1},
    {"t": "The repetition of vowel sounds is:", "o": ["Alliteration", "Assonance", "Consonance", "Rhyme"], "a": 1, "e": "Assonance repeats vowel sounds.", "d": 1},
    {"t": "The repetition of consonant sounds within words is:", "o": ["Assonance", "Consonance", "Alliteration", "Onomatopoeia"], "a": 1, "e": "Consonance repeats consonants.", "d": 1},
    {"t": "The use of words that imitate sounds is:", "o": ["Alliteration", "Onomatopoeia", "Assonance", "Metaphor"], "a": 1, "e": "Onomatopoeia imitates sounds (buzz, hiss).", "d": 1},
    {"t": "The repetition of similar sounds at the end of lines is:", "o": ["Alliteration", "Rhyme", "Assonance", "Metre"], "a": 1, "e": "Rhyme repeats end sounds.", "d": 1},
    {"t": "The pattern of stressed and unstressed syllables is:", "o": ["Rhyme", "Metre", "Alliteration", "Stanza"], "a": 1, "e": "Metre is the rhythmic pattern.", "d": 1},
    {"t": "The repetition of a word or phrase at the start of successive lines is:", "o": ["Metaphor", "Anaphora", "Simile", "Irony"], "a": 1, "e": "Anaphora repeats opening words.", "d": 1},
    {"t": "The repetition of the same word or phrase at the end of successive clauses is:", "o": ["Anaphora", "Epistrophe", "Simile", "Hyperbole"], "a": 1, "e": "Epistrophe repeats ending words.", "d": 2},
    {"t": "The pattern of rhymes in a poem is the:", "o": ["Metre", "Rhyme scheme", "Stanza", "Refrain"], "a": 1, "e": "A rhyme scheme maps rhyming lines.", "d": 1},
    {"t": "A refrain is a:", "o": ["Single line", "Repeated line or group of lines", "Type of stanza", "Figure of speech"], "a": 1, "e": "A refrain repeats in a poem.", "d": 1},
    {"t": "The poet's attitude toward the subject is the:", "o": ["Theme", "Tone", "Setting", "Plot"], "a": 1, "e": "Tone reflects the poet's attitude.", "d": 1},
    {"t": "The atmosphere or feeling created in a literary work is the:", "o": ["Tone", "Mood", "Theme", "Style"], "a": 1, "e": "Mood is the emotional atmosphere.", "d": 1},

    # ── Figures of speech ──
    {"t": "A direct comparison using 'like' or 'as' is a:", "o": ["Metaphor", "Simile", "Personification", "Hyperbole"], "a": 1, "e": "A simile uses 'like' or 'as'.", "d": 1},
    {"t": "An implied comparison without 'like' or 'as' is a:", "o": ["Simile", "Metaphor", "Irony", "Allusion"], "a": 1, "e": "A metaphor compares directly.", "d": 1},
    {"t": "'She is as brave as a lion' is an example of:", "o": ["Metaphor", "Simile", "Personification", "Irony"], "a": 1, "e": "It uses 'as...as', so it is a simile.", "d": 1},
    {"t": "'The world is a stage' is a:", "o": ["Simile", "Metaphor", "Hyperbole", "Paradox"], "a": 1, "e": "It compares directly without 'like/as'.", "d": 1},
    {"t": "Giving human qualities to non-human things is:", "o": ["Metaphor", "Personification", "Simile", "Irony"], "a": 1, "e": "Personification gives human traits to things.", "d": 1},
    {"t": "'The wind whispered through the trees' is an example of:", "o": ["Simile", "Personification", "Metaphor", "Hyperbole"], "a": 1, "e": "The wind is given a human action.", "d": 1},
    {"t": "A deliberate exaggeration for effect is:", "o": ["Irony", "Hyperbole", "Understatement", "Simile"], "a": 1, "e": "Hyperbole is exaggeration.", "d": 1},
    {"t": "'I have a million things to do' is an example of:", "o": ["Simile", "Hyperbole", "Metaphor", "Irony"], "a": 1, "e": "It exaggerates for effect.", "d": 1},
    {"t": "Saying the opposite of what is meant is:", "o": ["Hyperbole", "Irony", "Metaphor", "Simile"], "a": 1, "e": "Irony means the opposite of what is said.", "d": 1},
    {"t": "The use of a part to represent the whole is:", "o": ["Irony", "Synecdoche", "Metonymy", "Hyperbole"], "a": 1, "e": "Synecdoche: part for whole (e.g. 'all hands').", "d": 1},
    {"t": "Substituting a related word for another (e.g. 'the crown' for monarchy) is:", "o": ["Synecdoche", "Metonymy", "Metaphor", "Simile"], "a": 1, "e": "Metonymy substitutes a related term.", "d": 1},
    {"t": "A reference to a well-known person or event is an:", "o": ["Metaphor", "Allusion", "Simile", "Irony"], "a": 1, "e": "An allusion references something known.", "d": 1},
    {"t": "Addressing an absent person or object is:", "o": ["Allusion", "Apostrophe", "Irony", "Simile"], "a": 1, "e": "Apostrophe addresses the absent.", "d": 1},
    {"t": "A statement that seems contradictory but contains truth is a:", "o": ["Irony", "Paradox", "Simile", "Hyperbole"], "a": 1, "e": "A paradox is apparently contradictory yet true.", "d": 1},
    {"t": "An oxymoron is:", "o": ["Two contradictory words together", "A metaphor", "A simile", "An allusion"], "a": 0, "e": "An oxymoron joins opposites ('deafening silence').", "d": 1},
    {"t": "'Deafening silence' is an example of:", "o": ["Simile", "Oxymoron", "Metaphor", "Irony"], "a": 1, "e": "It combines contradictory terms.", "d": 1},
    {"t": "Using polite language to soften harsh reality is:", "o": ["Irony", "Euphemism", "Hyperbole", "Metaphor"], "a": 1, "e": "A euphemism softens bluntness.", "d": 1},
    {"t": "'He passed away' instead of 'he died' is a:", "o": ["Simile", "Euphemism", "Hyperbole", "Paradox"], "a": 1, "e": "It is a mild expression for death.", "d": 1},
    {"t": "Repetition of a consonant at the start of words ('Peter Piper picked') is:", "o": ["Assonance", "Alliteration", "Rhyme", "Metre"], "a": 1, "e": "Alliteration repeats initial consonants.", "d": 1},
    {"t": "A rhetorical question is one that:", "o": ["Needs an answer", "Is asked for effect, not an answer", "Has no punctuation", "Is always literal"], "a": 1, "e": "Rhetorical questions seek no answer.", "d": 1},
    {"t": "The arrangement of words to create a pleasing sound is:", "o": ["Plot", "Euphony", "Irony", "Theme"], "a": 1, "e": "Euphony is pleasing sound.", "d": 1},
    {"t": "A harsh, discordant sound in poetry is:", "o": ["Euphony", "Cacophony", "Rhyme", "Metre"], "a": 1, "e": "Cacophony is harsh sound.", "d": 1},
    {"t": "The literal or dictionary meaning of a word is its:", "o": ["Connotation", "Denotation", "Irony", "Tone"], "a": 1, "e": "Denotation is literal meaning.", "d": 1},
    {"t": "The emotional association of a word is its:", "o": ["Denotation", "Connotation", "Syntax", "Metre"], "a": 1, "e": "Connotation is implied meaning.", "d": 1},
    {"t": "Imagery in literature appeals to the:", "o": ["Intellect only", "Senses", "Conscience", "None"], "a": 1, "e": "Imagery appeals to the senses.", "d": 1},
    {"t": "The use of symbols to represent ideas is:", "o": ["Imagery", "Symbolism", "Irony", "Satire"], "a": 1, "e": "Symbolism uses symbols for ideas.", "d": 1},
    {"t": "A recurring symbol or theme in a work is a:", "o": ["Symbol", "Motif", "Plot", "Setting"], "a": 1, "e": "A motif recurs throughout a work.", "d": 1},
    {"t": "The main character's speech pattern or word choice is:", "o": ["Plot", "Diction", "Setting", "Theme"], "a": 1, "e": "Diction is word choice.", "d": 1},
    {"t": "The deliberate arrangement of words in a sentence is:", "o": ["Diction", "Syntax", "Tone", "Mood"], "a": 1, "e": "Syntax is word arrangement.", "d": 1},

    # ── Literary appreciation ──
    {"t": "In a poem, 'the road not taken' often symbolises:", "o": ["A literal road", "A life choice", "A journey", "A map"], "a": 1, "e": "The road symbolises a choice in life.", "d": 2},
    {"t": "The phrase 'the golden sun smiled down' contains:", "o": ["Simile", "Personification", "Hyperbole", "Irony"], "a": 1, "e": "The sun is personified as smiling.", "d": 1},
    {"t": "'Time is money' is a:", "o": ["Simile", "Metaphor", "Personification", "Allusion"], "a": 1, "e": "It compares time to money directly.", "d": 1},
    {"t": "'The classroom was a zoo' is an example of:", "o": ["Simile", "Metaphor", "Hyperbole", "Irony"], "a": 1, "e": "Direct comparison without like/as.", "d": 1},
    {"t": "'He runs like the wind' is a:", "o": ["Metaphor", "Simile", "Personification", "Oxymoron"], "a": 1, "e": "It uses 'like', so it is a simile.", "d": 1},
    {"t": "'The early bird catches the worm' is a:", "o": ["Fable", "Proverb", "Myth", "Legend"], "a": 1, "e": "It is a proverb (wise saying).", "d": 1},
    {"t": "The term 'protagonist' is best described as the:", "o": ["Villain", "Main character", "Narrator", "Minor character"], "a": 1, "e": "The protagonist is the central character.", "d": 1},
    {"t": "The 'climax' of a story is its:", "o": ["Beginning", "Highest point of tension", "Ending", "Setting"], "a": 1, "e": "The climax is the peak of tension.", "d": 1},
    {"t": "A story told by a character within the story uses the ___ narrator.", "o": ["Omniscient", "First-person", "Third-person", "Objective"], "a": 1, "e": "A character narrator is first-person.", "d": 1},
    {"t": "The 'plot' of a story refers to its:", "o": ["Theme", "Sequence of events", "Setting", "Characters"], "a": 1, "e": "Plot = sequence of events.", "d": 1},
    {"t": "The 'characterisation' of a work refers to:", "o": ["The plot", "How characters are presented", "The setting", "The title"], "a": 1, "e": "Characterisation is how characters are built.", "d": 1},
    {"t": "A 'round' character is one who is:", "o": ["Flat", "Fully developed and complex", "Minor", "Static"], "a": 1, "e": "Round characters are complex.", "d": 1},
    {"t": "A 'flat' character is one who is:", "o": ["Complex", "One-dimensional/simple", "Main", "Dynamic"], "a": 1, "e": "Flat characters are simple.", "d": 1},
    {"t": "A character who changes during a story is:", "o": ["Static", "Dynamic", "Flat", "Minor"], "a": 1, "e": "Dynamic characters change.", "d": 1},
    {"t": "A character who does not change is:", "o": ["Dynamic", "Static", "Round", "Protagonist"], "a": 1, "e": "Static characters stay the same.", "d": 1},
    {"t": "The 'theme' of a work is its:", "o": ["Setting", "Central message/idea", "Plot", "Characters"], "a": 1, "e": "Theme is the central idea.", "d": 1},
    {"t": "The 'setting' of a work is its:", "o": ["Theme", "Time and place", "Plot", "Style"], "a": 1, "e": "Setting = time and place.", "d": 1},
    {"t": "The 'tone' of a work is the author's:", "o": ["Setting", "Attitude toward the subject", "Plot", "Characters"], "a": 1, "e": "Tone = author's attitude.", "d": 1},
    {"t": "The 'mood' of a work is the:", "o": ["Author's attitude", "Feeling/atmosphere evoked", "Plot", "Setting"], "a": 1, "e": "Mood is the evoked atmosphere.", "d": 1},
    {"t": "A 'flashback' in a narrative is used to:", "o": ["Predict the future", "Show past events", "End the story", "Introduce the title"], "a": 1, "e": "Flashbacks reveal the past.", "d": 1},
    {"t": "'Suspense' in a story is:", "o": ["The ending", "Anxious uncertainty about what will happen", "The setting", "The title"], "a": 1, "e": "Suspense builds tension about outcomes.", "d": 1},
    {"t": "The 'denouement' of a story is its:", "o": ["Beginning", "Final resolution", "Climax", "Conflict"], "a": 1, "e": "The denouement resolves the plot.", "d": 1},
    {"t": "A 'prologue' is found at the:", "o": ["End of a work", "Beginning of a work", "Middle", "Nowhere"], "a": 1, "e": "A prologue introduces at the start.", "d": 1},
    {"t": "An 'epilogue' is found at the:", "o": ["Beginning", "End of a work", "Middle", "Nowhere"], "a": 1, "e": "An epilogue concludes at the end.", "d": 1},
    {"t": "The 'subplot' of a story is a:", "o": ["Main plot", "Secondary plot", "Theme", "Setting"], "a": 1, "e": "A subplot is a secondary story line.", "d": 1},
    {"t": "A 'foil' character serves to:", "o": ["Replace the hero", "Contrast with and highlight the main character", "End the story", "Narrate"], "a": 1, "e": "A foil contrasts with the protagonist.", "d": 1},
    {"t": "The 'anti-hero' is a protagonist who:", "o": ["Is perfect", "Lacks conventional heroic qualities", "Is a villain", "Never appears"], "a": 1, "e": "Anti-heroes lack heroic traits.", "d": 1},
    {"t": "'Bildungsroman' is a novel about:", "o": ["War", "A character's growth from youth to maturity", "Romance", "Mystery"], "a": 1, "e": "Bildungsroman = coming-of-age novel.", "d": 2},
    {"t": "The 'omniscient' point of view means the narrator:", "o": ["Knows only one character", "Knows all characters' thoughts", "Knows nothing", "Is a character"], "a": 1, "e": "Omniscient narrators know everything.", "d": 1},
    {"t": "A 'dramatic monologue' is a poem in which:", "o": ["Many speak", "A single speaker addresses a silent audience", "Nobody speaks", "It is sung"], "a": 1, "e": "A dramatic monologue has one speaker.", "d": 1},
    {"t": "The 'chorus' in classical drama:", "o": ["Performs", "Comments on the action", "Writes the play", "Directs"], "a": 1, "e": "The chorus comments on action.", "d": 1},
    {"t": "A 'tragic flaw' is a:", "o": ["Perfect trait", "Character defect that causes the hero's downfall", "Setting", "Plot device"], "a": 1, "e": "A tragic flaw causes downfall.", "d": 1},
    {"t": "'Hamartia' means:", "o": ["Victory", "Tragic flaw/error", "Comedy", "Revenge"], "a": 1, "e": "Hamartia = tragic error/flaw.", "d": 2},
    {"t": "'Catharsis' in tragedy is the:", "o": ["Purging of emotions in the audience", "Climax", "Conflict", "Setting"], "a": 0, "e": "Catharsis purges pity and fear.", "d": 2},
    {"t": "The term 'in medias res' means beginning a story:", "o": ["At the beginning", "In the middle of action", "At the end", "With a flashback"], "a": 1, "e": "In medias res = in the middle of things.", "d": 2},
    {"t": "'Verisimilitude' in literature means:", "o": ["Exaggeration", "The appearance of being true/real", "Fantasy", "Symbolism"], "a": 1, "e": "Verisimilitude = lifelike realism.", "d": 2},
    {"t": "The 'persona' in a poem is the:", "o": ["Reader", "Voice/speaker of the poem", "Author", "Publisher"], "a": 1, "e": "The persona is the poem's speaker.", "d": 1},
    {"t": "A 'ballad' is a poem that:", "o": ["Tells a story, often meant to be sung", "Expresses feelings", "Praises someone", "Is 14 lines"], "a": 0, "e": "Ballads are narrative songs.", "d": 1},
    {"t": "The 'lyric I' refers to the:", "o": ["Reader", "First-person speaker in a lyric", "Author", "Editor"], "a": 1, "e": "The lyric I is the first-person speaker.", "d": 2},
    {"t": "A 'rhetorical device' is used to:", "o": ["Confuse the reader", "Persuade or create effect", "End a story", "Set the scene"], "a": 1, "e": "Rhetorical devices persuade/effect.", "d": 1},
    {"t": "'Diction' refers to the writer's:", "o": ["Plot", "Choice of words", "Setting", "Characters"], "a": 1, "e": "Diction = word choice.", "d": 1},
    # ── More: appreciation & terms ──
    {"t": "The 'subject matter' of a poem is its:", "o": ["Rhyme", "Topic/content", "Metre", "Length"], "a": 1, "e": "Subject matter = what the poem is about.", "d": 1},
    {"t": "A 'monologue' is a:", "o": ["Dialogue", "Long speech by one person", "Song", "Chorus"], "a": 1, "e": "A monologue is one person's speech.", "d": 1},
    {"t": "The 'style' of a writer refers to:", "o": ["The plot", "The distinctive way they write", "The setting", "The title"], "a": 1, "e": "Style is the writer's distinctive manner.", "d": 1},
    {"t": "A 'simile' and a 'metaphor' both are forms of:", "o": ["Rhyme", "Comparison", "Narration", "Setting"], "a": 1, "e": "Both are comparisons.", "d": 1},
    {"t": "'Her eyes were stars' is a:", "o": ["Simile", "Metaphor", "Hyperbole", "Personification"], "a": 1, "e": "Direct comparison (no like/as).", "d": 1},
    {"t": "'He is as cunning as a fox' is a:", "o": ["Metaphor", "Simile", "Irony", "Paradox"], "a": 1, "e": "Uses 'as...as', so it is a simile.", "d": 1},
    {"t": "'The trees danced in the wind' uses:", "o": ["Simile", "Personification", "Irony", "Metaphor"], "a": 1, "e": "Trees are given human action.", "d": 1},
    {"t": "'I've told you a thousand times' is:", "o": ["Irony", "Hyperbole", "Simile", "Metaphor"], "a": 1, "e": "Exaggeration = hyperbole.", "d": 1},
    {"t": "'He is so kind that he'd give you the shirt off his back' suggests the man is:", "o": ["Selfish", "Generous", "Poor", "Careless"], "a": 1, "e": "The expression implies generosity.", "d": 2},
    {"t": "The 'plot' of a narrative is usually arranged in:", "o": ["Random order", "Beginning, middle and end", "No order", "Alphabetical order"], "a": 1, "e": "Plots follow a structured sequence.", "d": 1},
    {"t": "A 'narrative' is a:", "o": ["Poem only", "Story or account of events", "Play only", "Song"], "a": 1, "e": "A narrative tells a story.", "d": 1},
    {"t": "The 'setting' of a story includes its:", "o": ["Plot", "Time and place", "Characters", "Theme"], "a": 1, "e": "Setting = time and place.", "d": 1},
    {"t": "A 'dialogue' is:", "o": ["A solo speech", "Conversation between characters", "Stage direction", "Narration"], "a": 1, "e": "Dialogue is spoken exchange.", "d": 1},
    {"t": "The 'villain' of a story is the:", "o": ["Hero", "Evil character", "Narrator", "Setting"], "a": 1, "e": "The villain is the evil character.", "d": 1},
    {"t": "The 'hero' of a story is the:", "o": ["Villain", "Main admirable character", "Narrator", "Setting"], "a": 1, "e": "The hero is the admirable protagonist.", "d": 1},
    {"t": "The 'heroine' is the:", "o": ["Male hero", "Female hero", "Villain", "Narrator"], "a": 1, "e": "The heroine is a female hero.", "d": 1},
    {"t": "A 'protagonist' and an 'antagonist' are:", "o": ["The same", "Opposing forces/characters", "Narrators", "Settings"], "a": 1, "e": "They oppose each other.", "d": 1},
    {"t": "The 'exposition' of a story is its:", "o": ["Ending", "Introductory part", "Climax", "Conflict"], "a": 1, "e": "Exposition introduces the story.", "d": 1},
    {"t": "The 'rising action' builds toward the:", "o": ["Exposition", "Climax", "Denouement", "Prologue"], "a": 1, "e": "Rising action leads to the climax.", "d": 1},
    {"t": "The 'falling action' follows the:", "o": ["Exposition", "Climax", "Prologue", "Conflict"], "a": 1, "e": "Falling action comes after the climax.", "d": 1},
    {"t": "A 'play' is divided into:", "o": ["Chapters", "Acts and scenes", "Stanzas", "Cantos"], "a": 1, "e": "Plays divide into acts and scenes.", "d": 1},
    {"t": "A 'novel' is divided into:", "o": ["Acts", "Chapters", "Stanzas", "Scenes"], "a": 1, "e": "Novels divide into chapters.", "d": 1},
    {"t": "A 'poem' is divided into:", "o": ["Chapters", "Stanzas", "Acts", "Scenes"], "a": 1, "e": "Poems divide into stanzas.", "d": 1},
    {"t": "The 'plot' of a drama is its:", "o": ["Setting", "Story/sequence of events", "Theme", "Cast"], "a": 1, "e": "Plot = the story's events.", "d": 1},
    {"t": "A 'proverb' is a:", "o": ["Long story", "Short wise saying", "Poem", "Play"], "a": 1, "e": "A proverb is a short wise saying.", "d": 1},
    {"t": "A 'riddle' is a:", "o": ["Story", "Puzzle or question to be solved", "Poem", "Proverb"], "a": 1, "e": "A riddle is a puzzle.", "d": 1},
    {"t": "An 'idiom' is a:", "o": ["Literal phrase", "Phrase whose meaning is not literal", "Single word", "Poem"], "a": 1, "e": "Idioms have non-literal meanings.", "d": 1},
    {"t": "The 'moral' of a story is its:", "o": ["Plot", "Lesson", "Setting", "Characters"], "a": 1, "e": "The moral is the lesson taught.", "d": 1},
    {"t": "A 'novel of ideas' focuses on:", "o": ["Action only", "Exploring concepts/ideas", "Romance only", "Setting"], "a": 1, "e": "It explores ideas/themes.", "d": 2},
    {"t": "'Irony' occurs when:", "o": ["Everything is as expected", "There is a contrast between expectation and reality", "Only happy things happen", "Nothing happens"], "a": 1, "e": "Irony is a contrast of expectation/reality.", "d": 1},
    {"t": "'Dramatic irony' occurs when:", "o": ["The audience knows what characters do not", "Nobody knows anything", "Characters are honest", "The play is happy"], "a": 0, "e": "Audience knows more than characters.", "d": 1},
    {"t": "'Situational irony' is:", "o": ["Expected outcome", "An outcome opposite to what was expected", "A metaphor", "A simile"], "a": 1, "e": "Situational irony reverses expectations.", "d": 1},
    {"t": "'Verbal irony' is:", "o": ["Saying what you mean", "Saying the opposite of what you mean", "Silence", "Exaggeration"], "a": 1, "e": "Verbal irony says the opposite.", "d": 1},
    {"t": "A 'sonnet' has how many lines?", "o": ["12", "14", "16", "10"], "a": 1, "e": "A sonnet has 14 lines.", "d": 1},
    {"t": "The 'octave' of a sonnet has:", "o": ["6 lines", "8 lines", "4 lines", "2 lines"], "a": 1, "e": "The octave is 8 lines.", "d": 1},
    {"t": "The 'sestet' of a sonnet has:", "o": ["8 lines", "6 lines", "4 lines", "14 lines"], "a": 1, "e": "The sestet is 6 lines.", "d": 1},
    {"t": "The Shakespearean sonnet ends with a:", "o": ["Sestet", "Rhyming couplet", "Octave", "Quatrain"], "a": 1, "e": "It ends with a rhyming couplet.", "d": 2},
    {"t": "The Petrarchan sonnet divides into:", "o": ["Two quatrains", "An octave and a sestet", "Three quatrains", "Six couplets"], "a": 1, "e": "Octave + sestet.", "d": 2},
    {"t": "A 'haiku' is a poem with:", "o": ["14 lines", "Three lines (5-7-5 syllables)", "Four lines", "Two lines"], "a": 1, "e": "Haiku has three lines.", "d": 2},
    {"t": "An 'epitaph' is:", "o": ["A love poem", "An inscription on a tomb", "A war poem", "A song"], "a": 1, "e": "An epitaph is on a tombstone.", "d": 1},
    {"t": "A 'eulogy' is a speech or writing:", "o": ["Criticising someone", "In praise of someone (often dead)", "About war", "About nature"], "a": 1, "e": "A eulogy praises the dead.", "d": 1},
    {"t": "A 'dirge' is a:", "o": ["Happy song", "Song of mourning", "Love poem", "Comedy"], "a": 1, "e": "A dirge mourns the dead.", "d": 1},
    {"t": "The 'meter' of a poem refers to its:", "o": ["Meaning", "Rhythmic pattern", "Length", "Title"], "a": 1, "e": "Meter is the rhythm pattern.", "d": 1},
    {"t": "'Iambic pentameter' has ___ feet per line.", "o": ["Four", "Five", "Six", "Eight"], "a": 1, "e": "Pentameter = five metrical feet.", "d": 2},
    {"t": "A 'couplet' is:", "o": ["Four lines", "Two consecutive rhyming lines", "Six lines", "Eight lines"], "a": 1, "e": "A couplet is two rhyming lines.", "d": 1},
    {"t": "The 'refrain' of a poem is its:", "o": ["Title", "Repeated line(s)", "Last line", "First line"], "a": 1, "e": "A refrain repeats.", "d": 1},
    {"t": "'Enjambment' is the:", "o": ["End of a poem", "Continuation of a sentence beyond a line break", "A rhyme", "A stanza"], "a": 1, "e": "Enjambment runs on across lines.", "d": 2},
    {"t": "A 'caesura' is a:", "o": ["Rhyme", "Pause within a line", "Stanza", "Poem type"], "a": 1, "e": "A caesura is a pause in a line.", "d": 2},
    {"t": "The 'speaker' of a poem is the:", "o": ["Author", "Persona/voice", "Reader", "Critic"], "a": 1, "e": "The speaker is the poem's voice.", "d": 1},
    {"t": "The 'audience' of a play is:", "o": ["The actors", "The viewers", "The director", "The critics"], "a": 1, "e": "The audience watches.", "d": 1},
    {"t": "The 'costume' in drama refers to:", "o": ["The script", "The clothing worn by actors", "The stage", "The lights"], "a": 1, "e": "Costumes are actors' clothing.", "d": 1},
    {"t": "The 'props' in a play are:", "o": ["Characters", "Objects used on stage", "Lines", "Songs"], "a": 1, "e": "Props are stage objects.", "d": 1},
]

build("lit", "Literature in English", QUESTIONS[:200])
